### ISSUE TITLE
App Crashes = Landscape & Minimize/Reopen

### ISSUE THREAD

**Issue by DarkCrypt** [fast4x/RiMusic#144]
### Steps to reproduce the bug

Landscape:
1. Open app.
2. Turn phone sideways.
3. App crashes.

Minimize/Reopen:
1. While app is open, minimize.
2. Reopen app.
3. App crashes.

### Expected behavior

App should work properly.

### Actual behavior

App crashes.

### Screenshots/Screen recordings

Screen recording shows both crashes.

https://github.com/fast4x/RiMusic/assets/121076677/8098f1b7-4e46-4e59-b4f7-6be9a70e6433

### RiMusic version

v0.6.10.1

### Android version

Android 13

### Additional information

None.

**Comment by fast4x** [comment]
Hello, try to open the player and rotate. Give me confirmation if it crashes there too.

**Comment by DarkCrypt** [comment]
Not crashing when rotating or minimize/reopen app when player's open.

After opening player, app seems to function correctly.

Closing out and reopening app starts the issues again until player is used.

**Comment by fast4x** [comment]
Ok thanks

**Comment by ikanakova** [comment]
Same problem - Android 10, v0.6.10.1.

crash.log
```
FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 7783
java.lang.RuntimeException: Unable to create service it.vfsfitvnm.vimusic.service.PlayerService: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /storage/emulated/0/Android/data/it.fast4x.rimusic/files
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3966)
	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /storage/emulated/0/Android/data/it.fast4x.rimusic/files
	at k3.z.<init>(SourceFile:95)
	at it.vfsfitvnm.vimusic.service.PlayerService.onCreate(SourceFile:483)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3954)
	... 8 more
```

dump.log
```
1700920315.085  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.085  1002  2158  2842 I Avrcp_ext: updatePlayStatusForDevice: device: null
1700920315.085  1002  2158  2842 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=0, position=0, buffered position=0, speed=0.0, updated=0, actions=4927, custom actions=[], active item id=-1, error=null}(0), new=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}(2)
1700920315.085  1002  2158  2842 I Avrcp_ext: Exit updatePlayStatusForDevice
1700920315.085  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.085  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.085  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.085  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.085  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.085  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.085  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.085  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.085  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.085  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.085  1002  2158  2842 V Avrcp_ext: Exit updatePlayerStateAndPosition
1700920315.085  1002  2158  2842 D Avrcp_ext: Exit onSessionDestroyed
1700920315.085  1002  2158  2842 V Avrcp_ext: updateCurrentMediaState: mMediaController: null
1700920315.086  1002  2158  2842 V Avrcp_ext: isMusicActive: false getBluetoothPlayState: 2
1700920315.086  1002  2158  2842 V Avrcp_ext: updateCurrentMediaState: isPlaying = false
1700920315.086  1002  2158  2842 V Avrcp_ext: updateCurrentMediaState: mMediaController or getPlaybackState() null
1700920315.086  1002  2158  2842 V Avrcp_ext: Media update: id -1➡-1? [MediaAttributes: none] : [MediaAttributes: none]
1700920315.086  1002  2158  2842 V Avrcp_ext: newPlayStatus:2mReportedPlayStatus:-1
1700920315.086  1002  2158  2842 V Avrcp_ext: updatePlaybackState, state: PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null} device: null
1700920315.086  1002  2158  2842 V Avrcp_ext: Device: no name:
1700920315.086  1002  2158  2842 I chatty  : uid=1002(bluetooth) BluetoothAvrcpH identical 3 lines
1700920315.086  1002  2158  2842 V Avrcp_ext: Device: no name:
1700920315.086  1002  2158  2842 V Avrcp_ext: updatePlayerStateAndPosition, old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}, state=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}
1700920315.086  1002  2158  2842 V Avrcp_ext: old state = PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}, new state= PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}
1700920315.086  1002  2158  2842 D HeadsetService: getHeadsetService(): returning com.android.bluetooth.hfp.HeadsetService@e033069
1700920315.087  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.087  1002  2158  2842 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
1700920315.087  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.087  1002  2158  2842 I Avrcp_ext: updatePlayStatusForDevice: device: null
1700920315.087  1002  2158  2842 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}(2), new=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}(2)
1700920315.087  1002  2158  2842 I Avrcp_ext: Exit updatePlayStatusForDevice
1700920315.088  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.088  1002  2158  2842 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
1700920315.088 10157  2179  2179 I OpaLayout: Setting opa enabled to false
1700920315.088 10157  2179  2179 I OpaLayout: Setting opa enabled to false
1700920315.088  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.088  1002  2158  2842 I Avrcp_ext: updatePlayStatusForDevice: device: null
1700920315.088  1002  2158  2842 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}(2), new=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}(2)
1700920315.088  1002  2158  2842 I Avrcp_ext: Exit updatePlayStatusForDevice
1700920315.089  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.089  1002  2158  2842 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
1700920315.089  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.089  1002  2158  2842 I Avrcp_ext: updatePlayStatusForDevice: device: null
1700920315.089  1002  2158  2842 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}(2), new=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}(2)
1700920315.089  1002  2158  2842 I Avrcp_ext: Exit updatePlayStatusForDevice
1700920315.090  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.090  1002  2158  2842 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
1700920315.090  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.090  1002  2158  2842 I Avrcp_ext: updatePlayStatusForDevice: device: null
1700920315.091  1002  2158  2842 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}(2), new=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}(2)
1700920315.091  1002  2158  2842 I Avrcp_ext: Exit updatePlayStatusForDevice
1700920315.091  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.091  1002  2158  2842 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
1700920315.091  1002  2158  2842 D HeadsetService:  isAudioOn: The number of audio connected devices 0
1700920315.092  1002  2158  2842 I Avrcp_ext: updatePlayStatusForDevice: device: null
1700920315.092  1002  2158  2842 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220685, actions=0, custom actions=[], active item id=-1, error=null}(2), new=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=220690, actions=0, custom actions=[], active item id=-1, error=null}(2)
1700920315.092  1002  2158  2842 I Avrcp_ext: Exit updatePlayStatusForDevice
1700920315.092  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.092  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.092  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.092  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.092  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.092  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.092  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.092  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.092  1002  2158  2842 D Avrcp_ext: Enter sendPlayPosNotificationRsp
1700920315.092  1002  2158  2842 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
1700920315.092  1002  2158  2842 V Avrcp_ext: Exit updatePlayerStateAndPosition
1700920315.126  root   690  7854 E ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
1700920315.226  1000  1728  2512 D CompatibilityInfo: mCompatibilityFlags - 0
1700920315.226  1000  1728  2512 D CompatibilityInfo: applicationDensity - 420
1700920315.226  1000  1728  2512 D CompatibilityInfo: applicationScale - 1.0
1700920315.227  1000   568   568 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1728 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
1700920315.568  root   690  7857 E ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
1700920315.771  root   690  7864 E ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
1700920315.778  1000  3351  6410 D FileOperator: Mode change to WRITE_MODE!
1700920315.913 10199  7783  7783 D AndroidRuntime: Shutting down VM
1700920315.913 10199  7783  7783 E AndroidRuntime: FATAL EXCEPTION: main
1700920315.913 10199  7783  7783 E AndroidRuntime: Process: it.fast4x.rimusic, PID: 7783
1700920315.913 10199  7783  7783 E AndroidRuntime: java.lang.RuntimeException: Unable to create service it.vfsfitvnm.vimusic.service.PlayerService: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /storage/emulated/0/Android/data/it.fast4x.rimusic/files
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3966)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
1700920315.913 10199  7783  7783 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /storage/emulated/0/Android/data/it.fast4x.rimusic/files
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at k3.z.<init>(SourceFile:95)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at it.vfsfitvnm.vimusic.service.PlayerService.onCreate(SourceFile:483)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3954)
1700920315.913 10199  7783  7783 E AndroidRuntime: 	... 8 more
1700920315.918  1000  1728  7106 W ActivityTaskManager:   Force finishing activity it.fast4x.rimusic/it.vfsfitvnm.vimusic.MainActivity
1700920315.918  1000  1728  7866 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

Sometimes v0.6.10.1 crashes right when I try to open it.

**Comment by fast4x** [comment]
Yes, it's same issue

**Comment by fast4x** [comment]
Fixed, available from version 0.6.11

**Comment by NEVARLeVrai** [comment]
Also when u changing the app language and.sometimes randomly

**Comment by fast4x** [comment]
Yes I ficed it a few days ago

**Comment by DarkCrypt** [comment]
> Fixed, available from version 0.6.11

Issues are gone, thank you for fixing.

After updating to v0.6.11, I did receive a playback error. No songs would play. Force stopping the app fixed it.

**Comment by fast4x** [comment]
So after closing and reopening the app, it worked?

**Comment by DarkCrypt** [comment]
Correct. Close app, force stop, and reopen. Working!

**Comment by DarkCrypt** [comment]
> After updating to v0.6.11, I did receive a playback error. No songs would play. Force stopping the app fixed it.

Unfortunately, this is a constantly recurring issue.
