### ISSUE TITLE
RiMusic crashes in the local area

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#1522]
### Steps to reproduce the bug

1. Go to Library
2. go To local 
3. scroll down and RiMusic crashes
See logs

### Expected behavior

X

### Actual behavior

X

### Logs

FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 17060
java.lang.IllegalArgumentException: place is called on a deactivated node
	at q0.L.m0(SourceFile:116)
	at q0.L.Y(SourceFile:105)
	at o0.Z.l(SourceFile:28)
	at o0.Z.m(SourceFile:13)
	at w.A.c(SourceFile:296)
	at s.B.c(SourceFile:356)
	at o0.A.d(SourceFile:37)
	at w.z.d(SourceFile:3)
	at o0.C.d(SourceFile:14)
	at r.L.b(SourceFile:109)
	at r.L.d(SourceFile:89)
	at J.l.e(SourceFile:60)
	at T.A.a(SourceFile:48)
	at T.B.c(SourceFile:153)
	at q0.p0.a(SourceFile:3)
	at q0.L.r(SourceFile:128)
	at q0.L.l0(SourceFile:124)
	at q0.x.Y(SourceFile:18)
	at o0.Z.c(SourceFile:33)
	at o0.Z.d(SourceFile:5)
	at s.l.a(SourceFile:18)
	at s.l.c(SourceFile:16)
	at q0.O.d(SourceFile:7)
	at q0.C.Y(SourceFile:16)
	at o0.Z.j(SourceFile:32)
	at o0.Z.k(SourceFile:13)
	at s.l.a(SourceFile:51)
	at s.l.c(SourceFile:22)
	at q0.O.d(SourceFile:7)
	at q0.C.Y(SourceFile:16)
	at o0.Z.j(SourceFile:32)
	at o0.Z.k(SourceFile:13)
	at s.t.h(SourceFile:25)
	at s.t.c(SourceFile:422)
	at q0.O.d(SourceFile:7)
	at q0.C.Y(SourceFile:16)
	at o0.Z.g(SourceFile:69)
	at q.D.a(SourceFile:76)
	at q.D.c(SourceFile:82)
	at q0.O.d(SourceFile:7)
	at q0.C.Y(SourceFile:16)
	at o0.Z.e(SourceFile:29)
	at s.Z.a(SourceFile:368)
	at s.Z.d(SourceFile:96)
	at J.l.e(SourceFile:60)
	at T.A.a(SourceFile:48)
	at T.B.c(SourceFile:153)
	at q0.p0.a(SourceFile:3)
	at q0.L.m0(SourceFile:98)
	at androidx.compose.ui.node.a.M(SourceFile:32)
	at q0.T.k(SourceFile:217)
	at q0.T.h(SourceFile:77)
	at androidx.compose.ui.platform.AndroidComposeView.u(SourceFile:34)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:17)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5440)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### RiMusic version

06.30

### Android version

Android 12

**Comment by fast4x** [comment]
I'm sorry but i can't reproduce this bug

**Comment by fast4x** [comment]
Try next version 0.6.31, available soon.

**Comment by siggi1984** [comment]
> Try next version 0.6.31, available soon.

Okay
