### ISSUE TITLE
App crashes upon clicking albums by artists in artists page

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1588]
Upon clicking on an album in an artists page, the application crashes.

Log:

`FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 28269
java.lang.IllegalArgumentException: Cannot navigate to NavDeepLinkRequest{ uri=android-app://androidx.navigation/album/MPREb_k2N4cVKXrXM }. Navigation graph has not been set for NavController z2.D@f3dbe68.
	at z2.r.k(SourceFile:150)
	at z2.p.b(SourceFile:69)
	at z2.p.c(SourceFile:190)
	at h5.o.a(SourceFile:38)
	at h5.o.d(SourceFile:20)
	at o.w.c(SourceFile:286)
	at t.D1.t(SourceFile:134)
	at C5.a.i(SourceFile:9)
	at M2.a.Z0(SourceFile:79)
	at T5.h.r(SourceFile:100)
	at T5.h.E(SourceFile:33)
	at T5.h.i(SourceFile:17)
	at l0.N.w0(SourceFile:51)
	at l0.N.a0(SourceFile:31)
	at s.f.a0(SourceFile:5)
	at s.d.a0(SourceFile:5)
	at l0.i.f(SourceFile:157)
	at l0.i.f(SourceFile:136)
	at l0.i.f(SourceFile:136)
	at l0.i.f(SourceFile:136)
	at l0.i.f(SourceFile:136)
	at l0.i.f(SourceFile:136)
	at l0.i.f(SourceFile:136)
	at l0.e.b(SourceFile:30)
	at l0.y.a(SourceFile:122)
	at androidx.compose.ui.platform.AndroidComposeView.F(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.n(SourceFile:214)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:915)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
	at g.y.dispatchTouchEvent(SourceFile:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:873)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: Y5.h: [androidx.compose.ui.platform.D0@e482767, J.g@1645914, v0{Cancelling}@45635bd, c0@a42a7b2]`

**Comment by fast4x** [comment]
do you mean artist page followed or in search..?

**Comment by privacyfreak84** [comment]
Artist page (example- Taylor Swift's artist page displays all her songs, singles, albums etc.)

**Comment by fast4x** [comment]
I like it but I couldn’t play the problem, please send a short video.

**Comment by privacyfreak84** [comment]
OK; sending shortly

**Comment by privacyfreak84** [comment]
https://github.com/fast4x/RiMusic/assets/90613992/53b2c247-aff5-4058-94b3-186608af550c


Clicked on 1989 by the way.
Weird thing is, this seems to not happen with all artists 🤔

**Comment by fast4x** [comment]
Fixed, available from version 0.6.32

**Comment by privacyfreak84** [comment]
Thanks!
