### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1869]
### Steps to reproduce the bug

Pause song and remove notification of the app (Keep the app open)

### Expected behavior

App shouldn't crash

### Actual behavior

App crashed

### Logs

FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 29388
java.lang.IllegalStateException
	at E0.j.h(SourceFile:6)
	at J1.y.m(SourceFile:7)
	at D.G.b(SourceFile:222)
	at a6.r.h0(SourceFile:125)
	at h6.k.s(SourceFile:12)
	at N5.a.m(SourceFile:9)
	at e6.I.run(SourceFile:95)
	at androidx.compose.ui.platform.c0.t0(SourceFile:7)
	at androidx.compose.ui.platform.b0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: j6.h: [androidx.compose.ui.platform.D0@e8ae6f8, J.g@f5417d1, u0{Cancelling}@2b60236, c0@7ef9537]

### RiMusic version

0.6.34

### Android version

Android 12

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here

**Comment by NikunjKhangwal** [comment]
Can't reproduce yet so closing
