### ISSUE TITLE
App crashes when trying to reproduce latest downloaded songs

### ISSUE THREAD

**Issue by Ozzy4042** [fast4x/RiMusic#1886]
### Steps to reproduce the bug

1. Go to downloaded
2. Select organize by Date added
3. Scroll down to the last songs
4. App crashes
![Imagen de WhatsApp 2024-05-17 a las 12 25 22_ff73f332](https://github.com/fast4x/RiMusic/assets/170123063/5d9ae372-f7ee-40ad-824e-405e8966f3c8)
![Imagen de WhatsApp 2024-05-17 a las 12 24 03_a5824c4c](https://github.com/fast4x/RiMusic/assets/170123063/7797834e-9621-456d-98dd-b9fedc3e661a)
![Imagen de WhatsApp 2024-05-17 a las 12 24 04_1272d1c3](https://github.com/fast4x/RiMusic/assets/170123063/c3a2a0fd-26cd-4591-a88c-e293274af792)

### Expected behavior

The App shouldn't crash and I can play that song(s)

### Actual behavior

App crashes

### RiMusic version

0.6.34

### Android version

14

**Comment by fast4x** [comment]
click ok Information of app and paste log please

**Comment by Ozzy4042** [comment]
Sorry it is my first time, but how can I look the log?

**Comment by fast4x** [comment]
yes, thanks I'll check it

**Comment by Ozzy4042** [comment]
Hello, I installed version 0.6.35 and the crash is still there

**Comment by fast4x** [comment]
it's normal I'll check it later

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here

**Comment by fast4x** [comment]
Please paste here crash log from RiMusic miscellaneous settings

**Comment by Ozzy4042** [comment]
--------- beginning of crash
2024-06-14 15:14:25.890 17763-17763 AndroidRuntime          it.fast4x.rimusic                    E  FATAL EXCEPTION: main
                                                                                                    Process: it.fast4x.rimusic, PID: 17763
                                                                                                    e2.v
                                                                                                    	at o2.G.V(SourceFile:63)
                                                                                                    	at S5.k.B2(SourceFile:38)
                                                                                                    	at io.ktor.client.engine.cio.e.d(SourceFile:136)
                                                                                                    	at t.G.a(SourceFile:14)
                                                                                                    	at t.G.c(SourceFile:12)
                                                                                                    	at v.s1.r(SourceFile:320)
                                                                                                    	at W6.a.m(SourceFile:9)
                                                                                                    	at o7.B.V(SourceFile:79)
                                                                                                    	at o7.h.p(SourceFile:100)
                                                                                                    	at o7.h.E(SourceFile:33)
                                                                                                    	at o7.h.m(SourceFile:17)
                                                                                                    	at v0.M.A0(SourceFile:51)
                                                                                                    	at v0.M.y(SourceFile:31)
                                                                                                    	at t.j.y(SourceFile:112)
                                                                                                    	at v0.i.f(SourceFile:157)
                                                                                                    	at v0.i.f(SourceFile:136)
                                                                                                    	at v0.i.f(SourceFile:136)
                                                                                                    	at v0.i.f(SourceFile:136)
                                                                                                    	at v0.e.b(SourceFile:30)
                                                                                                    	at v0.x.a(SourceFile:126)
                                                                                                    	at B0.z.J(SourceFile:79)
                                                                                                    	at B0.z.p(SourceFile:373)
                                                                                                    	at B0.z.dispatchTouchEvent(SourceFile:76)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:776)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4531)
                                                                                                    	at h.B.dispatchTouchEvent(SourceFile:3)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:734)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:16476)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8482)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8233)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7562)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7619)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7585)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7788)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7593)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7845)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7566)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7619)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7585)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7593)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7566)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11103)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10985)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10941)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11237)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:296)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:187)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    	Suppressed: t7.h: [B0.S0@8bb421a, Q.i@ffb414b, u0{Cancelling}@6e1d728, m0@ea6fc41]
2024-06-14 15:14:25.941 17763-17763 Process                 it.fast4x.rimusic                    I  Sending signal. PID: 17763 SIG: 9

**Comment by fast4x** [comment]
Maybe in next version it's fixed

**Comment by Ozzy4042** [comment]
Well I have the version 0.6.41, and unfortunately it does not, but I don't think it is as necessary to fix it as before
