### ISSUE TITLE
Not able to play songs

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#1945]
### Steps to reproduce the bug

Open Rimusic
Try to play songs
App closes but works in the background
See the prompt rimusic is crashing choose send feedback or cancel if not choosen app works in the background but for removing the prompt u have to chose the option and close the app

### Expected behavior

The app should play song without any crashing

### Actual behavior

The app closes works in background get a prompt rimusic isnt responding send feedback to miui or cancel without these options the prompt never goes and cant listen to any songs

### Logs

java.lang.ClassCastException: b3.d cannot be cast to b3.p
	at C0.l.n1(SourceFile:95)
	at H5.h.v(SourceFile:11)
	at O5.a.l(SourceFile:9)
	at k6.w.v(SourceFile:7)
	at f6.a.l(SourceFile:23)
	at O5.a.l(SourceFile:32)
	at f6.I.run(SourceFile:95)
	at androidx.compose.ui.platform.d0.t0(SourceFile:7)
	at androidx.compose.ui.platform.c0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
	Suppressed: k6.h: [androidx.compose.ui.platform.D0@c1168e5, J.g@77d9fba, u0{Cancelling}@b03de6b, d0@2c7dc8]

### RiMusic version

0.6.35

### Android version

MIUI11 A10

### Additional information

Have started experiencing it before a day haven't tried anything feel free to provide thr suggestions have tried cleaning the cache

**Comment by ALMIGHTY-VC** [comment]
After reinstalling it works
