### ISSUE TITLE
App crashed while opening

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1963]
### Steps to reproduce the bug

Open the app

### Expected behavior

The app should work as intended

### Actual behavior

App randomly crashed

### Logs

`FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 20796
java.lang.ClassCastException: b3.d cannot be cast to b3.p
	at C0.l.n1(SourceFile:95)
	at H5.h.v(SourceFile:11)
	at O5.a.l(SourceFile:9)
	at k6.w.v(SourceFile:7)
	at f6.a.l(SourceFile:23)
	at O5.a.l(SourceFile:32)
	at f6.I.run(SourceFile:95)
	at androidx.compose.ui.platform.d0.t0(SourceFile:7)
	at androidx.compose.ui.platform.c0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: k6.h: [androidx.compose.ui.platform.D0@2ce723b, J.g@d56cd58, u0{Cancelling}@a966eb1, d0@5ad3f96]`

### RiMusic version

0.6.35

### Android version

Android 12

**Comment by fast4x** [comment]
offline online mode?

**Comment by NikunjKhangwal** [comment]
Online

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here

**Comment by NikunjKhangwal** [comment]
I can't reproduce it yet. It happened once. Closing the issue for now.
