### ISSUE TITLE
App Crash on cache settings after changing UI mode settings

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#202]
### Steps to reproduce the bug

1. Change theme to ViMusic
2. Go to the Cache category

### Expected behavior

Not Crashing

### Actual behavior

It's crashing

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/104271365/24a760c4-b3ee-4f75-8ca8-29e34d94b37c

### Logs

Sorry idk how to do it

### RiMusic version

0.6.12

### Android version

Android 14 with OneUI 6

**Comment by NikunjKhangwal** [comment]
Happened me with once as well

My Logs:-
FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 9984
java.lang.IllegalStateException
	at j7.l.b0(SourceFile:1)
	at i3.y.g(SourceFile:1)
	at f9.j.a(SourceFile:35)
	at f9.j.i(SourceFile:12)
	at s5.j.K(SourceFile:64)
	at d0.k0.g(SourceFile:283)
	at d0.k0.i(SourceFile:16)
	at d0.b0.v(SourceFile:47)
	at d0.g0.a(SourceFile:24)
	at d0.g0.c(SourceFile:13)
	at d0.k0.getValue(SourceFile:11)
	at kb.e.i(SourceFile:1849)
	at f9.c.a(SourceFile:190)
	at f9.c.B(SourceFile:53)
	at k0.c.B(SourceFile:59)
	at f8.b.d(SourceFile:183)
	at l0.g.f(SourceFile:121)
	at f9.b0.a(SourceFile:37)
	at f9.b0.T(SourceFile:25)
	at k0.c.b(SourceFile:51)
	at k0.c.T(SourceFile:1)
	at n.j.b(SourceFile:102)
	at n.j.A(SourceFile:562)
	at k0.c.a(SourceFile:51)
	at k0.c.A(SourceFile:1)
	at f8.c.a(SourceFile:1705)
	at f8.c.b(SourceFile:290)
	at n.k.a(SourceFile:270)
	at n.k.B(SourceFile:29)
	at k0.c.B(SourceFile:59)
	at f8.b.b(SourceFile:1033)
	at f8.b.a(SourceFile:235)
	at kb.e.K(SourceFile:75)
	at f9.c0.a(SourceFile:231)
	at f9.c0.A(SourceFile:19)
	at k0.c.a(SourceFile:51)
	at p.t.a(SourceFile:135)
	at p.t.B(SourceFile:90)
	at d0.w.L(SourceFile:284)
	at d0.w.Y(SourceFile:34)
	at j7.l.v(SourceFile:175)
	at z.e1.z(SourceFile:81)
	at f9.c.a(SourceFile:120)
	at f9.c.B(SourceFile:41)
	at d0.w.L(SourceFile:284)
	at p.d2.b(SourceFile:828)
	at p.d2.i(SourceFile:234)
	at f8.b.q0(SourceFile:43)
	at d0.w.o(SourceFile:134)
	at d0.w.K(SourceFile:36)
	at d0.b0.u(SourceFile:18)
	at d0.u1.q(SourceFile:117)
	at o.a1.b(SourceFile:417)
	at o.a1.c(SourceFile:105)
	at androidx.compose.ui.platform.o0.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.m0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1135)
	at android.view.Choreographer.doCallbacks(Choreographer.java:920)
	at android.view.Choreographer.doFrame(Choreographer.java:829)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: h5.e: [d0.f1@d177beb, androidx.compose.ui.platform.o1@d838d48, v1{Cancelling}@3bf47e1, n0@95e5906]

**Comment by fast4x** [comment]
> Happened me with once as well
> 
> My Logs:-
> FATAL EXCEPTION: main
> Process: it.fast4x.rimusic, PID: 9984
> java.lang.IllegalStateException
> 	at j7.l.b0(SourceFile:1)
> 	at i3.y.g(SourceFile:1)
> 	at f9.j.a(SourceFile:35)
> 	at f9.j.i(SourceFile:12)
> 	at s5.j.K(SourceFile:64)
> 	at d0.k0.g(SourceFile:283)
> 	at d0.k0.i(SourceFile:16)
> 	at d0.b0.v(SourceFile:47)
> 	at d0.g0.a(SourceFile:24)
> 	at d0.g0.c(SourceFile:13)
> 	at d0.k0.getValue(SourceFile:11)
> 	at kb.e.i(SourceFile:1849)
> 	at f9.c.a(SourceFile:190)
> 	at f9.c.B(SourceFile:53)
> 	at k0.c.B(SourceFile:59)
> 	at f8.b.d(SourceFile:183)
> 	at l0.g.f(SourceFile:121)
> 	at f9.b0.a(SourceFile:37)
> 	at f9.b0.T(SourceFile:25)
> 	at k0.c.b(SourceFile:51)
> 	at k0.c.T(SourceFile:1)
> 	at n.j.b(SourceFile:102)
> 	at n.j.A(SourceFile:562)
> 	at k0.c.a(SourceFile:51)
> 	at k0.c.A(SourceFile:1)
> 	at f8.c.a(SourceFile:1705)
> 	at f8.c.b(SourceFile:290)
> 	at n.k.a(SourceFile:270)
> 	at n.k.B(SourceFile:29)
> 	at k0.c.B(SourceFile:59)
> 	at f8.b.b(SourceFile:1033)
> 	at f8.b.a(SourceFile:235)
> 	at kb.e.K(SourceFile:75)
> 	at f9.c0.a(SourceFile:231)
> 	at f9.c0.A(SourceFile:19)
> 	at k0.c.a(SourceFile:51)
> 	at p.t.a(SourceFile:135)
> 	at p.t.B(SourceFile:90)
> 	at d0.w.L(SourceFile:284)
> 	at d0.w.Y(SourceFile:34)
> 	at j7.l.v(SourceFile:175)
> 	at z.e1.z(SourceFile:81)
> 	at f9.c.a(SourceFile:120)
> 	at f9.c.B(SourceFile:41)
> 	at d0.w.L(SourceFile:284)
> 	at p.d2.b(SourceFile:828)
> 	at p.d2.i(SourceFile:234)
> 	at f8.b.q0(SourceFile:43)
> 	at d0.w.o(SourceFile:134)
> 	at d0.w.K(SourceFile:36)
> 	at d0.b0.u(SourceFile:18)
> 	at d0.u1.q(SourceFile:117)
> 	at o.a1.b(SourceFile:417)
> 	at o.a1.c(SourceFile:105)
> 	at androidx.compose.ui.platform.o0.doFrame(Unknown Source:6)
> 	at androidx.compose.ui.platform.m0.doFrame(SourceFile:48)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1135)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:920)
> 	at android.view.Choreographer.doFrame(Choreographer.java:829)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:210)
> 	at android.os.Looper.loop(Looper.java:299)
> 	at android.app.ActivityThread.main(ActivityThread.java:8280)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
> 	Suppressed: h5.e: [d0.f1@d177beb, androidx.compose.ui.platform.o1@d838d48, v1{Cancelling}@3bf47e1, n0@95e5906]

Your Android version?

**Comment by NikunjKhangwal** [comment]
@fast4x Android 12

**Comment by fast4x** [comment]
Is the crash always there or sometimes?

**Comment by fast4x** [comment]
this error solved?

**Comment by OrangeZXZ** [comment]
> this error solved?

yes
