### ISSUE TITLE
App crashing when playing certain songs from favourites

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2058]
### Steps to reproduce the bug

1. Add [this](https://music.youtube.com/watch?v=s7yvqysENYY) song in favourites for example
2. Try to play it from favourites

### Expected behavior

App shouldn't crash and songs should play normally

### Actual behavior

App is crashing

### Logs

`FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 2933
C4.U
	at d2.H.V(SourceFile:63)
	at Y5.l.s1(SourceFile:38)
	at io.ktor.client.engine.cio.e.d(SourceFile:136)
	at u.G.a(SourceFile:14)
	at u.G.c(SourceFile:12)
	at w.k1.s(SourceFile:320)
	at g6.a.r(SourceFile:9)
	at Y5.j.X1(SourceFile:79)
	at x6.h.p(SourceFile:100)
	at x6.h.E(SourceFile:33)
	at x6.h.r(SourceFile:17)
	at w0.M.z0(SourceFile:51)
	at w0.M.P(SourceFile:31)
	at u.j.P(SourceFile:112)
	at w0.i.f(SourceFile:157)
	at w0.i.f(SourceFile:136)
	at w0.i.f(SourceFile:136)
	at w0.i.f(SourceFile:136)
	at w0.e.b(SourceFile:30)
	at w0.x.a(SourceFile:126)
	at C0.z.I(SourceFile:79)
	at C0.z.n(SourceFile:373)
	at C0.z.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:572)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4274)
	at i.z.dispatchTouchEvent(SourceFile:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:530)
	at android.view.View.dispatchPointerEvent(View.java:15165)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6919)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6698)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6135)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6192)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6158)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6323)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6166)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6380)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6139)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6192)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6158)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6166)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6139)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9271)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9211)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9168)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9416)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:280)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:340)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: C6.h: [C0.S0@d3aa00c, R.i@401fd55, u0{Cancelling}@4c6f36a, n0@4dc205b]`

### RiMusic version

0.6.36.1

### Android version

Android 12

### Additional information

This problem gets solved when removing and re-adding the song in favourites but still it's a bug that could affect other users in future.

**Comment by NikunjKhangwal** [comment]
Ok so it isn't related to certain songs but it happens when you click on last 4 songs in the favourites

**Comment by aneesh1122** [comment]
Not happening on my device.

**Comment by NikunjKhangwal** [comment]
Maybe another bug limited to Vimusic mode

**Comment by aneesh1122** [comment]
> Maybe another bug limited to Vimusic mode

I'm using ViMusic mode. Are you offline? Try changing the player's background. Try  'background from theme'.

**Comment by NikunjKhangwal** [comment]
Why do you think player background has anything to do with favourites list?

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here

**Comment by NikunjKhangwal** [comment]
2024-06-08T08:32:30.275:	e2.v
	 o2.G.V(SourceFile:63) 
	 S5.k.B2(SourceFile:38) 
	 io.ktor.client.engine.cio.e.d(SourceFile:136) 
	 t.G.a(SourceFile:14) 
	 t.G.c(SourceFile:12) 
	 v.s1.r(SourceFile:320) 
	 W6.a.m(SourceFile:9) 
	 o7.B.V(SourceFile:79) 
	 o7.h.p(SourceFile:100) 
	 o7.h.E(SourceFile:33) 
	 o7.h.m(SourceFile:17) 
	 v0.M.A0(SourceFile:51) 
	 v0.M.y(SourceFile:31) 
	 t.j.y(SourceFile:112) 
	 v0.i.f(SourceFile:157) 
	 v0.i.f(SourceFile:136) 
	 v0.i.f(SourceFile:136) 
	 v0.i.f(SourceFile:136) 
	 v0.e.b(SourceFile:30) 
	 v0.x.a(SourceFile:126) 
	 B0.z.J(SourceFile:79) 
	 B0.z.p(SourceFile:373) 
	 B0.z.dispatchTouchEvent(SourceFile:76) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834) 
	 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:572) 
	 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895) 
	 android.app.Activity.dispatchTouchEvent(Activity.java:4274) 
	 h.B.dispatchTouchEvent(SourceFile:3) 
	 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:530) 
	 android.view.View.dispatchPointerEvent(View.java:15165) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6919) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6698) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6135) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6192) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6158) 
	 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6323) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6166) 
	 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6380) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6139) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6192) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6158) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6166) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6139) 
	 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9271) 
	 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9211) 
	 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9168) 
	 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9416) 
	 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:280) 
	 android.os.MessageQueue.nativePollOnce(Native Method) 
	 android.os.MessageQueue.next(MessageQueue.java:340) 
	 android.os.Looper.loopOnce(Looper.java:168) 
	 android.os.Looper.loop(Looper.java:299) 
	 android.app.ActivityThread.main(ActivityThread.java:8280) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by fast4x** [comment]
In new version song is reproduced without problem, wait for 0.6.44
