### ISSUE TITLE
App crashing while tapping the translate lyrics button

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#206]
### Steps to reproduce the bug

Enable Lyrics and press the translate button

### Expected behavior

The lyrics should be translated

### Actual behavior

The app is crashing

### Logs

FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 32114
qa.d: Exception caught from HTTP request
	at qa.f.k(SourceFile:1)
	at qa.f.A(SourceFile:16)
	at q6.w.a(SourceFile:129)
	at q6.s.k(SourceFile:186)
	at p9.a.h(SourceFile:1)
	at fa.i0.run(SourceFile:1)
	at kotlinx.coroutines.internal.f.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: h5.e: [androidx.compose.ui.platform.o1@343638a, d0.e@2c19dfb, v1{Cancelling}@5b4ee18, n0@d24e071]
Caused by: java.util.concurrent.CancellationException: v1 was cancelled
	at n6.f.a(SourceFile:49)
	at n6.f.c(SourceFile:23)
	at fa.b1.y(SourceFile:1)
	at fa.l1.V(SourceFile:1)
	at fa.l1.r(SourceFile:184)
	at fa.m.y(SourceFile:9)
	at fa.l1.V(SourceFile:1)
	at fa.l1.r(SourceFile:184)
	at fa.l1.t(SourceFile:1)
	at fa.l1.f(SourceFile:13)
	at d0.w0.c(SourceFile:6)
	at d0.a0.b(SourceFile:38)
	at d0.b0.g(SourceFile:78)
	at d0.b0.f(SourceFile:6)
	at o.a1.b(SourceFile:255)
	at o.a1.c(SourceFile:105)
	at androidx.compose.ui.platform.o0.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.m0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1135)
	at android.view.Choreographer.doCallbacks(Choreographer.java:920)
	at android.view.Choreographer.doFrame(Choreographer.java:829)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

### RiMusic version

0.6.12

### Android version

12

### Additional information

Looks like it's clashing with Zygote process. I'm on a rooted device.

**Comment by NikunjKhangwal** [comment]
This was already mentioned in #161 but the issue is closed and it's still happening so i made a seperate issue. I don't know if it's happening for the same reason or not.

**Comment by fast4x** [comment]
What if there’s no internet?
#161 is old bug

**Comment by NikunjKhangwal** [comment]
There was internet connection. Even if there's not, the app should keep loading instead of crashing right?

**Comment by fast4x** [comment]
Correct, app must not crash.

Fixed, available from version 0.6.13
