### ISSUE TITLE
Keeps crashing the app after viewing the "My Top 200" playlist

### ISSUE THREAD

**Issue by TimWasNotHere** [fast4x/RiMusic#2468]
### Steps to reproduce the bug

1. Go to songs
2. Go to the top 200
3. It crashes

### Expected behavior

Should just show the songs

### Actual behavior

Crashes the app and I cant get back in because it constantly crashes

### Logs

FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 21530
java.lang.NullPointerException
	at C6.X.a(SourceFile:72)
	at s7.K.e(SourceFile:5)
	at s7.J.w(SourceFile:140)
	at s7.J.a(SourceFile:1)
	at r7.M.f(SourceFile:125)
	at r7.k.t(SourceFile:12)
	at W6.a.k(SourceFile:9)
	at o7.J.run(SourceFile:95)
	at G0.b0.h0(SourceFile:7)
	at G0.a0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: t7.g: [G0.H0@a5a45e5, T.h@dd9b8ba, w0{Cancelling}@5d8836b, b0@4fcbec8]

### RiMusic version

0.6.40.1

### Android version

Android 14

### Additional information

This happened in the last version, too, and I had to uninstall and reinstall the app to fix it. I thought it was fixed in the newest version because I could view it the first time, but then I went back to it a second time, and it crashed. It happened two times in the last version, both after trying to view "my top 200" songs and after each time I had to uninstall and reinstall the app, and it just happened again on the new version viewing "my top 200". 
Also, the backup data doesn't save all settings and preferences, but I dunno if its supposed to or not.

**Comment by fast4x** [comment]
This is the crash log?

**Comment by TimWasNotHere** [comment]
It was the app's crash log provided by Logfox. I know there are debug logs on the app, but it seems even if I enabled that, I wouldn't be able to access it since I'd need to get into the app again to copy the crash log.

Is there a way to access the crash logs without getting on the app?
