### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2534]
### Steps to reproduce the bug

Idk
I switched from my browser to RiMusic which was running in background and it crashed.

### Expected behavior

Shouldn't crash

### Actual behavior

It crashed

### Logs

FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 31628
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at q0.k.a(SourceFile:125)
	at n0.f.onPreDraw(SourceFile:34)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3652)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2389)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9369)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1137)
	at android.view.Choreographer.doCallbacks(Choreographer.java:920)
	at android.view.Choreographer.doFrame(Choreographer.java:834)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

### RiMusic version

0.6.41

### Android version

Android 12

**Comment by fast4x** [comment]
Maybe it's fixed, available from version 0.6.42
