### ISSUE TITLE
"My Top 10" Crash

### ISSUE THREAD

**Issue by Lambdasond** [fast4x/RiMusic#2611]
### Steps to reproduce the bug

Go to: Songs -> My Top 10

### Expected behavior

Open My Top 10 Tab

### Actual behavior

Crash (There is a chance that the application will crash every time you turn it on after that)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/153488917/523aa15a-dad4-45ad-a7a8-c748b8919972

### Logs

FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 10541
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a5dba37 u0 it.fast4x.rimusic/.service.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### RiMusic version

0.6.41

### Android version

Andoid 14, One UI 6.1

**Comment by fast4x** [comment]
Fixed, available from version 0.6.42

**Comment by Nitin927** [comment]
Crash in few seconds

**Comment by fast4x** [comment]
Next version... I'm talk about next version
