### ISSUE TITLE
Crash listening songs with lyrics enabled for about 5 minutes always

### ISSUE THREAD

**Issue by jcgomezv00** [fast4x/RiMusic#2640]
### Steps to reproduce the bug

- search for a song
- open the player
- enable lyrics
- listen for about 5 minutes with lyrics enabled

### Expected behavior

Listen to music without freezing or closing unespectedly

### Actual behavior

The app freezes or closes it self completely

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/68335368/e430cfdc-7036-451a-9362-2f36fe2ea9d8

### Logs

2024-07-04 12:49:12:202 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-04 12:49:17:436 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 12:49:17:520 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 12:49:18:191 ERROR: b - The request's data is null.
2024-07-04 12:49:18:192 ERROR: b - The request's data is null.
2024-07-04 12:49:18:193 ERROR: b - The request's data is null.
2024-07-04 12:49:18:193 ERROR: b - The request's data is null.
2024-07-04 12:49:18:199 ERROR: b - The request's data is null.
2024-07-04 12:49:18:201 ERROR: b - The request's data is null.
2024-07-04 12:49:18:201 ERROR: b - The request's data is null.
2024-07-04 12:49:18:202 ERROR: b - The request's data is null.
2024-07-04 12:56:44:335 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 12:56:45:114 ERROR: b - The request's data is null.
2024-07-04 12:56:45:116 ERROR: b - The request's data is null.
2024-07-04 12:56:45:117 ERROR: b - The request's data is null.
2024-07-04 12:56:45:117 ERROR: b - The request's data is null.
2024-07-04 12:56:45:120 ERROR: b - The request's data is null.
2024-07-04 12:56:45:121 ERROR: b - The request's data is null.
2024-07-04 12:56:45:122 ERROR: b - The request's data is null.
2024-07-04 12:56:45:123 ERROR: b - The request's data is null.
2024-07-04 01:08:41:342 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:08:42:123 ERROR: b - The request's data is null.
2024-07-04 01:08:42:125 ERROR: b - The request's data is null.
2024-07-04 01:08:42:126 ERROR: b - The request's data is null.
2024-07-04 01:08:42:127 ERROR: b - The request's data is null.
2024-07-04 01:08:42:130 ERROR: b - The request's data is null.
2024-07-04 01:08:42:131 ERROR: b - The request's data is null.
2024-07-04 01:08:42:132 ERROR: b - The request's data is null.
2024-07-04 01:08:42:133 ERROR: b - The request's data is null.
2024-07-04 01:22:21:003 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-04 01:22:21:151 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:22:21:227 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:22:21:857 ERROR: b - The request's data is null.
2024-07-04 01:22:21:859 ERROR: b - The request's data is null.
2024-07-04 01:22:21:860 ERROR: b - The request's data is null.
2024-07-04 01:22:21:860 ERROR: b - The request's data is null.
2024-07-04 01:22:21:866 ERROR: b - The request's data is null.
2024-07-04 01:22:21:868 ERROR: b - The request's data is null.
2024-07-04 01:22:21:869 ERROR: b - The request's data is null.
2024-07-04 01:22:21:870 ERROR: b - The request's data is null.
2024-07-04 01:22:26:169 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:22:26:216 ERROR: b - The request's data is null.
2024-07-04 01:22:26:217 ERROR: b - The request's data is null.
2024-07-04 01:22:26:219 ERROR: b - The request's data is null.
2024-07-04 01:22:26:221 ERROR: b - The request's data is null.
2024-07-04 01:22:26:224 ERROR: b - The request's data is null.
2024-07-04 01:22:26:225 ERROR: b - The request's data is null.
2024-07-04 01:22:26:227 ERROR: b - The request's data is null.
2024-07-04 01:22:26:228 ERROR: b - The request's data is null.
2024-07-04 01:25:19:239 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:25:19:272 ERROR: b - The request's data is null.
2024-07-04 01:25:19:273 ERROR: b - The request's data is null.
2024-07-04 01:25:19:274 ERROR: b - The request's data is null.
2024-07-04 01:25:19:275 ERROR: b - The request's data is null.
2024-07-04 01:25:19:277 ERROR: b - The request's data is null.
2024-07-04 01:25:19:278 ERROR: b - The request's data is null.
2024-07-04 01:25:19:279 ERROR: b - The request's data is null.
2024-07-04 01:25:19:280 ERROR: b - The request's data is null.
2024-07-04 01:25:19:301 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:29:18:977 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:29:33:168 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:29:33:195 ERROR: b - The request's data is null.
2024-07-04 01:29:33:196 ERROR: b - The request's data is null.
2024-07-04 01:29:33:197 ERROR: b - The request's data is null.
2024-07-04 01:29:33:198 ERROR: b - The request's data is null.
2024-07-04 01:29:33:200 ERROR: b - The request's data is null.
2024-07-04 01:29:33:201 ERROR: b - The request's data is null.
2024-07-04 01:29:33:202 ERROR: b - The request's data is null.
2024-07-04 01:29:33:203 ERROR: b - The request's data is null.
2024-07-04 01:31:13:444 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:31:13:490 ERROR: b - The request's data is null.
2024-07-04 01:31:13:491 ERROR: b - The request's data is null.
2024-07-04 01:31:13:492 ERROR: b - The request's data is null.
2024-07-04 01:31:13:492 ERROR: b - The request's data is null.
2024-07-04 01:31:13:495 ERROR: b - The request's data is null.
2024-07-04 01:31:13:496 ERROR: b - The request's data is null.
2024-07-04 01:31:13:497 ERROR: b - The request's data is null.
2024-07-04 01:31:13:498 ERROR: b - The request's data is null.
2024-07-04 01:32:53:610 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-04 01:34:42:158 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-04 01:34:42:292 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:34:42:373 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:34:43:021 ERROR: b - The request's data is null.
2024-07-04 01:34:43:022 ERROR: b - The request's data is null.
2024-07-04 01:34:43:023 ERROR: b - The request's data is null.
2024-07-04 01:34:43:024 ERROR: b - The request's data is null.
2024-07-04 01:34:43:030 ERROR: b - The request's data is null.
2024-07-04 01:34:43:031 ERROR: b - The request's data is null.
2024-07-04 01:34:43:032 ERROR: b - The request's data is null.
2024-07-04 01:34:43:033 ERROR: b - The request's data is null.
2024-07-04 01:36:07:065 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:36:07:110 ERROR: b - The request's data is null.
2024-07-04 01:36:07:111 ERROR: b - The request's data is null.
2024-07-04 01:36:07:112 ERROR: b - The request's data is null.
2024-07-04 01:36:07:113 ERROR: b - The request's data is null.
2024-07-04 01:36:07:116 ERROR: b - The request's data is null.
2024-07-04 01:36:07:117 ERROR: b - The request's data is null.
2024-07-04 01:36:07:118 ERROR: b - The request's data is null.
2024-07-04 01:36:07:119 ERROR: b - The request's data is null.
2024-07-04 01:40:09:630 DEBUG: d - CheckMonthlyPlaylist false
2024-07-04 01:40:09:686 ERROR: b - The request's data is null.
2024-07-04 01:40:09:687 ERROR: b - The request's data is null.
2024-07-04 01:40:09:688 ERROR: b - The request's data is null.
2024-07-04 01:40:09:689 ERROR: b - The request's data is null.
2024-07-04 01:40:09:693 ERROR: b - The request's data is null.
2024-07-04 01:40:09:694 ERROR: b - The request's data is null.
2024-07-04 01:40:09:694 ERROR: b - The request's data is null.
2024-07-04 01:40:09:695 ERROR: b - The request's data is null.
2024-07-04 09:04:46:208 INFO: p -  sdk int 31
2024-07-04 09:04:51:842 ERROR: a - Failed to load bitmap No album art found
2024-07-04 09:09:09:540 INFO: p -  sdk int 31
2024-07-04 09:09:25:885 ERROR: a - Failed to load bitmap No album art found
2024-07-04 09:10:27:260 ERROR: a - Failed to load bitmap No album art found
2024-07-04 09:24:14:841 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-05 06:25:49:891 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-05 06:25:50:140 INFO: m -  sdk int 31
2024-07-05 06:25:55:461 ERROR: i - Failed to load bitmap java.io.FileNotFoundException: No album art found
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1518)
	at G3.b.a(SourceFile:587)
	at H3.i.c(SourceFile:197)
	at H3.i.b(SourceFile:295)
	at H3.g.u(SourceFile:38)
	at g7.a.i(SourceFile:9)
	at y7.J.run(SourceFile:95)
	at D7.i.run(SourceFile:239)
	at F7.k.run(SourceFile:3)
	at F7.a.run(SourceFile:96)

2024-07-05 06:34:20:202 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-05 06:45:18:303 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

### RiMusic version

0.6.42

### Android version

Android 12

### Additional information

It worked in previous version 0.6.36

**Comment by fast4x** [comment]
Try to change player background type without cover...

It work?

**Comment by fast4x** [comment]
Improved, available from version 0.6.43

**Comment by jcgomezv00** [comment]
Changing player background did not work. Will wait version 0.6.43.

Thank you.

**Comment by jcgomezv00** [comment]
I took this crash log today.

2024-07-06T10:51:49.990:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 A5.a.u(SourceFile:38) 
	 g7.a.i(SourceFile:9) 
	 y7.J.run(SourceFile:95) 
	 D7.i.run(SourceFile:239) 
	 F7.k.run(SourceFile:3) 
	 F7.a.run(SourceFile:96) 

2024-07-06T23:09:30.253:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 A5.a.u(SourceFile:38) 
	 g7.a.i(SourceFile:9) 
	 y7.J.run(SourceFile:95) 
	 D7.i.run(SourceFile:239) 
	 F7.k.run(SourceFile:3) 
	 F7.a.run(SourceFile:96)

**Comment by fast4x** [comment]
Too many open files is an error in your system, caused by any limit.

**Comment by jcgomezv00** [comment]
First of all i want to thank you for this great work and this wanderfull app.

In my case, there is no way to change that limit without rooting the device.

I will keep on version 0.6.35 as a rollback, becouse it does not contain the bug or is not being affected by my android version. Will be testing each new release. 

Thank you team!.

**Comment by AMZMA** [comment]
![Screenshot_2024-07-13-20-19-57-541_it fast4x rimusic](https://github.com/user-attachments/assets/21caf26b-a0b9-4626-9f57-ce2bed8358a4)

v0.6.43, still facing the same problem as v0.6.42.

im going back to v0.6.35 as [jcgomezv00](https://github.com/jcgomezv00) mentioned.

**Comment by jcgomezv00** [comment]
This behavior is still in v0.6.43

Opening the app fresh installed:

Choose a song, open lyrics, play synchronized:

https://github.com/user-attachments/assets/9fdf2858-57dc-426e-8005-3ec869c96018

After ~5 minutes playing the music with lyrics open and synchronized the app closes completely.

https://github.com/user-attachments/assets/967ef38f-4c94-436e-9bea-3373d82673e5

Debug Log:

2024-07-14T11:50:33.086:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 A5.a.u(SourceFile:38) 
	 g7.a.i(SourceFile:9) 
	 y7.J.run(SourceFile:95) 
	 D7.i.run(SourceFile:239) 
	 F7.k.run(SourceFile:3) 
	 F7.a.run(SourceFile:96)

**Comment by fast4x** [comment]
Try to disable all background cover and blurred cover theme...
l

**Comment by jcgomezv00** [comment]
Hello. Didn't work, I have disabled background, changed theme, used through vpn, installed fresh copy, tested wi-fi and mobile, used the super service option, tested vimusic theme, and many other things. Something happened with the function from 0.6.36+, the newer versions carried de problem until now. Again im back to v0.6.35 as a working rollback after testing the new releases as they appear without success.

**Comment by fast4x** [comment]
You use lyrics in full screen?

**Comment by fast4x** [comment]
#2768 try new lyrics like in this ticket

**Comment by AMZMA** [comment]
i have tested v0.6.44 and it working fine on my phone. (uninstall before installing latest version). no more crash.
but when I tested it on Android TV it still crashed (neither Layout 1 nor Layout 2 works).
it's all fine on my phone since default lyrics display is no more on full screen display.

turned out, the culprit was the option "**Show thumbnail for lyrics**". disabled it and **now everything is works flawlessly**.
tested it emulator, works fine too.

==
could you make the landscape layout still able showing lyrics without need to enter fullscreen lyrics display?
like still showing music control, info, or even album art.
thank you.


and add option to increase/decrease lyrics delay (500ms).
thank you so much.
