### ISSUE TITLE
Can't login into piped account 

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#2782]
### Steps to reproduce the bug

1. Go to settings
2. Then go to miscellaneous 
3. Turn on enable piper synchronisation 
4. Then i tried to log into my piped account 

### Expected behavior

It should login

### Actual behavior

But it is showing login failed even with correct password 

### Screenshots/Screen recordings

![Screenshot_20240718-114910_RiMusic](https://github.com/user-attachments/assets/6343477f-70df-46ab-a540-3a5ccaf5d53b)

### Logs

2024-07-18 11:49:53:662 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-18 11:50:07:477 ERROR: w - Failed piped login n5.e: Client request(POST https://pipedapi.kavin.rocks/login) invalid: 401 . Text: "{"error":"The username or password you have entered is incorrect."}"
	at n5.j.u(SourceFile:244)
	at n5.j.j(SourceFile:13)
	at n5.t.b(SourceFile:113)
	at B7.v.u(SourceFile:643)
	at g7.a.i(SourceFile:9)
	at y7.J.run(SourceFile:95)
	at I0.d0.h0(SourceFile:7)
	at I0.c0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

### RiMusic version

0.6.43

### Android version

Android 14

**Comment by fast4x** [comment]
Piped said "The username or password you have entered is incorrect"

Go to Piped and reset your password.

**Comment by aneesh1122** [comment]
one more thing is, if your username is "abcd123" then RiMusic won't login if you put space anywhere. For example, "abcd123 " will not be accepted.
