### ISSUE TITLE
Album Details broken/not showing

### ISSUE THREAD

**Issue by HydeZero** [fast4x/RiMusic#2861]
### Steps to reproduce the bug

1. Open any album in RiMusic
2. Scroll to the bottom or view right below the title

### Expected behavior

Album details (info and/or alternate versions) are shown. Right below the title, album year is shown.

### Actual behavior

Album details (info and/or alternate versions) are shown. Right below the title, album year is not shown

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/57988a5b-f5f1-44d1-b914-d422d46a1796

(Video resolution shrunk down and video sped up 2x to allow GitHub upload)

### Logs

2024-07-21 21:01:10:587 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-21 21:01:10:700 ERROR: PlayerService - Failed onDestroy in PlayerService java.lang.IllegalArgumentException: Receiver not registered: E6.A@513a211
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1751)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1933)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:837)
	at it.fast4x.rimusic.service.PlayerService.onDestroy(SourceFile:64)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

2024-07-21 21:01:10:746 ERROR: M - maybeRestorePlayerQueue startForegroundService android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service it.fast4x.rimusic/.service.PlayerService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6457)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1967)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847)
	at y1.c.b(SourceFile:1)
	at E6.M.u(SourceFile:155)
	at i7.a.n(SourceFile:9)
	at A7.L.run(SourceFile:113)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### RiMusic version

0.6.44

### Android version

Android 14

### Additional information

This isn't isolated to just one album.

**Comment by fast4x** [comment]
Download the custom version it's fixed
