### ISSUE TITLE
My infinite skipping issue

### ISSUE THREAD

**Issue by SunsetSamu** [fast4x/RiMusic#2904]
### Steps to reproduce the bug

1. Play a song
2. Tap the mini player to open Full player 
3. ✨✨My songs are skipping without touch em ✨✨

### Expected behavior

Not skipping 

### Actual behavior

Skipping 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d5d6f1c8-7e65-43fb-b9ea-608d5d3c6847

### Logs
```
2024-07-13 17:13:48:926 DEBUG: W - CheckMonthlyPlaylist false
2024-07-13 17:13:51:565 DEBUG: W - CheckMonthlyPlaylist false
2024-07-13 17:13:52:422 INFO: m -  sdk int 33
2024-07-13 17:14:14:779 ERROR: i - Failed to load bitmap java.io.FileNotFoundException: No album art found
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1518)
	at G3.b.a(SourceFile:587)
	at H3.i.c(SourceFile:197)
	at H3.i.b(SourceFile:295)
	at H3.g.u(SourceFile:38)
	at g7.a.i(SourceFile:9)
	at y7.J.run(SourceFile:95)
	at D7.i.run(SourceFile:239)
	at F7.k.run(SourceFile:3)
	at F7.a.run(SourceFile:96)

2024-07-13 17:24:50:392 DEBUG: W - CheckMonthlyPlaylist false
2024-07-13 17:24:53:265 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at X7.b.e(SourceFile:6)
	at X7.n.d(SourceFile:245)
	at b8.f.a(SourceFile:201)
	at b8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at Z7.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at c8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at c8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at b8.j.g(SourceFile:97)
	at b8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

2024-07-13 17:34:44:076 DEBUG: W - CheckMonthlyPlaylist false
2024-07-13 17:34:46:737 DEBUG: W - CheckMonthlyPlaylist false
2024-07-24 14:12:13:827 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-24 14:12:16:003 DEBUG: Y - CheckMonthlyPlaylist false
2024-07-24 14:12:16:527 DEBUG: Y - CheckMonthlyPlaylist false
2024-07-24 14:12:16:767 DEBUG: Y - CheckMonthlyPlaylist false
2024-07-24 14:12:17:232 DEBUG: Y - CheckMonthlyPlaylist false
2024-07-24 14:13:33:191 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

2024-07-24 14:13:36:417 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:14:36:916 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

2024-07-24 14:14:40:056 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:14:52:375 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:14:57:690 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-24 14:16:27:647 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:16:30:810 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:16:43:385 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:17:20:619 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:17:23:958 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:17:36:835 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:18:14:030 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 18 more

2024-07-24 14:18:17:325 ERROR: i - Failed to load bitmap java.net.UnknownHostException: Unable to resolve host "lh3.googleusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at Z7.b.e(SourceFile:6)
	at Z7.n.d(SourceFile:247)
	at d8.f.a(SourceFile:201)
	at d8.a.a(SourceFile:64)
	at D.C.f(SourceFile:128)
	at b8.b.a(SourceFile:141)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:640)
	at D.C.f(SourceFile:128)
	at e8.a.a(SourceFile:158)
	at D.C.f(SourceFile:128)
	at d8.j.g(SourceFile:97)
	at d8.g.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:13
```
### RiMusic version

0.6.44

### Android version

Android 13

### Additional information

If you leave the app it still skiping

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings, after crash copy and paste here  logs

**Comment by privacyfreak84** [comment]
> Enable debug in miscellaneous settings, after crash copy and paste here logs

Can't @fast4x . It says log unavailable

**Comment by privacyfreak84** [comment]
Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand

**Comment by aneesh1122** [comment]
> Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand

if you ever feel like listening to a specific duration of every song for some reason, medley is your friend.

**Comment by SunsetSamu** [comment]
> Enable debug in miscellaneous settings, after crash copy and paste here  logs

It isn't crashing...

**Comment by SunsetSamu** [comment]
> Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand

For some reason, the minimum it allows me is 1

**Comment by SunsetSamu** [comment]
> Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand

For some reason, the minimum it allows me is 1

**Comment by aneesh1122** [comment]
> > Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand
> 
> For some reason, the minimum it allows me is 1

Touch the icon. It will reset to 0

**Comment by SunsetSamu** [comment]
> > > Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand
> > 
> > For some reason, the minimum it allows me is 1
> 
> Touch the hourglass icon. It will reset to 0

LMAO it worked

**Comment by aneesh1122** [comment]
> > > > Its working after setting medley duration to 0 by tapping on the hourglass icon. What does medley do? I don't understand
> > > 
> > > For some reason, the minimum it allows me is 1
> > 
> > Touch the hourglass icon. It will reset to 0
> 
> LMAO it worked

Glad I could make your mental health a little more stable 😅
