### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2923]
### Steps to reproduce the bug

Opened rimusic it crashed

### Expected behavior

It should stay stable

### Actual behavior

It crashed

### Logs

java.lang.IllegalStateException
	at m2.b.h(SourceFile:6)
	at q2.x.l(SourceFile:7)
	at L6.B.m(SourceFile:105)
	at D7.Q.f(SourceFile:125)
	at D7.l.u(SourceFile:12)
	at i7.a.n(SourceFile:9)
	at A7.L.run(SourceFile:113)
	at I0.d0.h0(SourceFile:7)
	at I0.c0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
	Suppressed: F7.g: [I0.J0@97bc12b, V.g@ce8988, A0{Cancelling}@d082f21, d0@f5e4f46]

Here's log from my miui device 

### RiMusic version

0.6.44

### Android version

MIUI 11 A10

### Additional information

Now i retried opening it opens but just in case for future

**Comment by ALMIGHTY-VC** [comment]
Again faced an unexpected crash
java.lang.IndexOutOfBoundsException
	at k2.d0.p(SourceFile:3)
	at O2.d.f(SourceFile:14)
	at B8.d.K(SourceFile:1275)
	at J.m0.e(SourceFile:255)
	at e0.a.d(SourceFile:44)
	at e0.a.e(SourceFile:9)
	at j.e(SourceFile:143)
	at e0.a.d(SourceFile:44)
	at e0.a.e(SourceFile:9)
	at N6.d.f(SourceFile:870)
	at e0.a.f(SourceFile:52)
	at O.T.f(SourceFile:170)
	at e0.a.f(SourceFile:52)
	at W.c.b(SourceFile:150)
	at T.R1.a(SourceFile:113)
	at T.U0.b(SourceFile:56)
	at T.H0.f(SourceFile:214)
	at e0.a.f(SourceFile:52)
	at T.W0.f(SourceFile:258)
	at e0.a.f(SourceFile:52)
	at T.B0.a(SourceFile:52)
	at B.k.f(SourceFile:1325)
	at e0.a.f(SourceFile:52)
	at W.c.b(SourceFile:150)
	at J0.s0.a(SourceFile:395)
	at D.i.f(SourceFile:2438)
	at e0.a.f(SourceFile:52)
	at W.c.b(SourceFile:150)
	at J0.U.a(SourceFile:617)
	at J0.B1.f(SourceFile:250)
	at e0.a.f(SourceFile:52)
	at W.c.a(SourceFile:233)
	at J0.B1.f(SourceFile:213)
	at e0.a.f(SourceFile:52)
	at W.c.O(SourceFile:15)
	at W.p.p(SourceFile:236)
	at W.p.K(SourceFile:32)
	at W.t.w(SourceFile:22)
	at W.t0.t(SourceFile:101)
	at W.q0.b(SourceFile:515)
	at J0.e0.doFrame(SourceFile:7)
	at J0.c0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:785)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
	Suppressed: J7.g: [J0.f0@b576655, J0.J0@22a86a, A0{Cancelling}@a0e315b, d0@276edf8]

**Comment by ALMIGHTY-VC** [comment]
Again in crashed in the background when phone was locked
java.lang.IllegalArgumentException: Progress percentage must be within 0.0f inclusive to 1.0f inclusive. Value: 1.0000594
	at l8.d.x(SourceFile:33)
	at e7.f.g(SourceFile:1671)
	at i6.c.O(SourceFile:257)
	at B8.d.K(SourceFile:1290)
	at V6.t0.f(SourceFile:72)
	at W.p.M(SourceFile:438)
	at W.p.T(SourceFile:137)
	at W.p.p(SourceFile:244)
	at W.p.K(SourceFile:32)
	at W.t.w(SourceFile:22)
	at W.t0.t(SourceFile:101)
	at W.q0.b(SourceFile:515)
	at J0.e0.doFrame(SourceFile:7)
	at J0.c0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:785)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
	Suppressed: J7.g: [J0.f0@da09532, J0.J0@180f283, A0{Cancelling}@21d5c00, d0@885c39]

**Comment by ALMIGHTY-VC** [comment]
New crash 3
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at t0.k.a(SourceFile:125)
	at q0.f.onPreDraw(SourceFile:34)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2826)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1799)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7770)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by fast4x** [comment]
try latest please

**Comment by ALMIGHTY-VC** [comment]
> try latest please

Well yeah latest doesnt have these its been ages since i opened it Lol closing it thanks for fixing the bugs
