### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#2992]
App is crashing randomly, like when listening to songs, opening the queue (especially this, it's also extremely laggy and almost unusable) etc.

Crash Log:

```
2024-07-28T23:16:36.697:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:246) 
	 android.app.ActivityThread.main(ActivityThread.java:8653) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

Full log:

```
2024-07-28 22:55:42:357 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-28 22:58:08:122 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 22:58:13:676 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 22:59:37:257 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:02:46:019 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:08:40:676 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:08:53:136 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:12:10:730 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:12:43:969 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:16:38:113 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-28 23:16:50:186 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-07-28 23:17:31:041 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:8392)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5256)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
Thanks for the log...

**Comment by aneesh1122** [comment]
Try the new custom version and see if you're still getting errors

**Comment by privacyfreak84** [comment]
Closing as fixed

**Comment by fast4x** [comment]
Wow thanks
