### ISSUE TITLE
App se cierra al intentar cargar letra

### ISSUE THREAD

**Issue by Nisselle** [fast4x/RiMusic#3000]
### Steps to reproduce the bug

1. Entro a la aplicación 
2. Seleccionó una canción para reproducir
3. Le doy click a la miniatura para visualizar la letra
4. Se queda cargando
5. No termina de cargar la letra y se cierra la app

### Expected behavior

Que se cargue la letra de las canciones y que no se cierra la app al intentar cargar la letra de la canción 

### Actual behavior

Se cierra al intentar cargar la letra de la canción 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0b472211-b70e-4f53-9471-417fd67e23e7

### RiMusic version

0.6.45.1

### Android version

Android 11

### Additional information

Pobre reiniciando mi celular e igualmente lo intente en otro celular distinto y paso lo mismo

**Comment by fast4x** [comment]
Require that you paste here RiMusic log, please enable in miscellaneous settings and after crash paste log here.

**Comment by Nisselle** [comment]
2024-07-29 02:45:12:862 DEBUG: MainApplication - Log enabled at
/data/user/0/it.fast4x.rimusic/files/logs
2024-07-29 02:45:13:128 DEBUG: z - CheckMonthlyPlaylist false
2024-07-29 02:45:13:267 DEBUG: z - CheckMonthlyPlaylist false
2024-07-29 02:45:13:295 DEBUG: z - CheckMonthlyPlaylist false
2024-07-29 02:45:24:969 ERROR: MainActivity - MainActivity.onPause
unregisterListener sensorListener java.lang.NullPointerException
at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
at android.app.Activity.performPause(Activity.java:8263)
at
android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1516)
at
android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5013)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4974)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4925)
at
android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
at
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:268)
at android.app.ActivityThread.main(ActivityThread.java:8019)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

2024-07-29 02:46:35:088 DEBUG: MainApplication - Log enabled at
/data/user/0/it.fast4x.rimusic/files/logs
2024-07-29 02:46:38:141 DEBUG: z - CheckMonthlyPlaylist false
2024-07-29 02:46:38:554 ERROR: MainActivity - MainActivity.onPause
unregisterListener sensorListener java.lang.NullPointerException
at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
at android.app.Activity.performPause(Activity.java:8263)
at
android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1516)
at
android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5013)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4974)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4925)
at
android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
at
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:268)
at android.app.ActivityThread.main(ActivityThread.java:8019)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

2024-07-29 02:46:39:114 DEBUG: z - CheckMonthlyPlaylist false
2024-07-29 02:46:40:963 DEBUG: z - CheckMonthlyPlaylist false

**Comment by Nisselle** [comment]
Ya probé la versión personalizada y me ayudó con el problema, muchas
gracias
