### ISSUE TITLE
App crashes after opening lyrics 

### ISSUE THREAD

**Issue by caltusv** [fast4x/RiMusic#3006]
### Steps to reproduce the bug

When i open lyrics for any song after few minutes app crashes

### Expected behavior

The app should not crash

### Actual behavior

App crashes 

### Logs

i copied that crash log
2024-07-29T12:08:26.143:java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
a.a.m(SourceFile:57) 
b7.K.u(SourceFile:41) 
r7.a.l(SourceFile:9) 
J7.K.run(SourceFile:113) 
J0.c0.h0(SourceFile:7) 
J0.b0.run(SourceFile:3) 
android.os.Handler.handleCallback(Handler.java:789) 
android.os.Handler.dispatchMessage(Handler.java:98) 
android.os.Looper.loop(Looper.java:164) 
android.app.ActivityThread.main(ActivityThread.java:6944) 
java.lang.reflect.Method.invoke(Native Method) 
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

### RiMusic version

0.6.45.1

### Android version

Android 8

### Additional information

And i copied that other log 
2024-07-29 12:06:20:360 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
at android.app.Activity.performPause(Activity.java:7451)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1414)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4115)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4092)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4066)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4040)
at android.app.ActivityThread.-wrap16(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

2024-07-29 12:06:23:065 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-29 12:07:03:115 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

**Comment by aneesh1122** [comment]
Download a custom version please, try if it work, thanks
 https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by frenchy82** [comment]
Hi, i have the same problem and this  custom version solved  the problem of crash with the lyrics for me.

**Comment by fast4x** [comment]
Thanks for feedback

**Comment by caltusv** [comment]
> Download a custom version please, try if it work, thanks https://github.com/fast4x/RiMusic/tree/master/customVersion



> Hi, i have the same problem and this custom version solved the problem of crash with the lyrics for me.

Thanks for advice custom version solved this problem for me but there is other problems but some people wrote same problem.
