### ISSUE TITLE
App crashes after pressing the star button

### ISSUE THREAD

**Issue by OofYeetMcGee** [fast4x/RiMusic#3063]
### Steps to reproduce the bug

I pressed or held the star button in the played ui.

### Expected behavior

I couldn't find any documentation about what that button does.

### Actual behavior

It changed the song then crashed. Subsequent crashes occurred upon opening the app. Once I was able to "unselect" the star button the crashes stopped.

 It crashed if I press and hold the star button.

### Screenshots/Screen recordings

![fc2deda3-2138-488c-aad6-ee747bce5e5f](https://github.com/user-attachments/assets/1e00b463-4b63-46bb-a795-fc32596c2783)

### Logs

```
type: crash
osVersion: google/panther/panther:14/AP2A.240705.004/2024072800:user/release-keys
package: it.fast4x.rimusic:46
process: it.fast4x.rimusic
processUptime: 10478 + 429 ms
installer: dev.imranr.obtainium.fdroid

java.lang.IndexOutOfBoundsException
	at n2.b.h(SourceFile:8)
	at D2.i0.p(SourceFile:6)
	at D2.w.p(SourceFile:3)
	at u2.b0.p(SourceFile:21)
	at O2.d.f(SourceFile:14)
	at B7.a.l(SourceFile:1214)
	at b7.s0.i(SourceFile:72)
	at W.p.M(SourceFile:438)
	at W.p.T(SourceFile:137)
	at W.p.p(SourceFile:244)
	at W.p.K(SourceFile:32)
	at W.t.w(SourceFile:22)
	at W.t0.t(SourceFile:102)
	at W.r0.b(SourceFile:515)
	at J0.d0.doFrame(SourceFile:7)
	at J0.b0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:941)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: O7.g: [J0.e0@b30eddf, J0.H0@5c96a2c, x0{Cancelling}@f23ccf5, c0@52f1a8a]
```

### RiMusic version

v0.6.45.1

### Android version

Android 14

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
It remove preferites and playlist songs from radio functionality, try custom version

**Comment by OofYeetMcGee** [comment]
How can I try the custom version? I got a 404 when clicking the app-release.apk

**Comment by fast4x** [comment]
I've published new version

**Comment by OofYeetMcGee** [comment]
Working great now, thanks!

**Comment by fast4x** [comment]
Thanks for feedback
