### ISSUE TITLE
Songs not playing or downloading after update

### ISSUE THREAD

**Issue by cheeslyanger** [fast4x/RiMusic#3134]
### Steps to reproduce the bug

The bug is some songs do not play nor download after the new update

### Expected behavior

If shouldve played  or downloaded some songs, as i have connection and not connected to any sort of vpn or proxy

### Actual behavior

It just wouldnt download or play some songs

### Screenshots/Screen recordings

![Screenshot_20240805_222355](https://github.com/user-attachments/assets/9bda7838-8861-4c58-b89c-63bf22600ccb)
![Screenshot_20240805_222339](https://github.com/user-attachments/assets/50a3fb6e-030f-4f2e-8468-70929f87ab22)

### Logs

XXXXX

### RiMusic version

0.6.46

### Android version

14

### Additional information

XXXXX

**Comment by cheeslyanger** [comment]
It wouldnt show logs at first because of me not enabling the feature but now i did
2024-08-05T23:30:02.939:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.I1.m(SourceFile:1351) 
	 e0.a.e(SourceFile:44) 
	 e0.a.m(SourceFile:9) 
	 J.n0.h(SourceFile:253) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1480) 
	 P6.q.i(SourceFile:307) 
	 e0.a.i(SourceFile:52) 
	 f3.c.b(SourceFile:958) 
	 f3.c.a(SourceFile:321) 
	 J3.a.m(SourceFile:887) 
	 W6.I.h(SourceFile:1404) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1131) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:236) 
	 W.p.K(SourceFile:32) 
	 W.t.w(SourceFile:22) 
	 W.t0.t(SourceFile:102) 
	 W.r0.b(SourceFile:515) 
	 J0.d0.doFrame(SourceFile:7) 
	 J0.b0.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1069) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by cheeslyanger** [comment]
Another log that isnt a crash 2024-08-05 23:29:50:385 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-05 23:29:50:573 DEBUG: z - CheckMonthlyPlaylist false
2024-08-05 23:29:50:673 DEBUG: z - CheckMonthlyPlaylist false
2024-08-05 23:29:50:682 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:29:50:682 DEBUG: z - SongsMostPlayed null
2024-08-05 23:29:50:700 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:29:50:701 DEBUG: z - SongsMostPlayed 0
2024-08-05 23:29:50:717 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:29:50:718 DEBUG: z - SongsMostPlayed 0
2024-08-05 23:29:59:556 DEBUG: z - CheckMonthlyPlaylist false
2024-08-05 23:29:59:630 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:29:59:631 DEBUG: z - SongsMostPlayed null
2024-08-05 23:29:59:678 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:29:59:679 DEBUG: z - SongsMostPlayed 0
2024-08-05 23:30:02:922 ERROR: I1 - Playback error: N6.h
2024-08-05 23:30:04:136 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-05 23:30:04:542 DEBUG: z - CheckMonthlyPlaylist false
2024-08-05 23:30:04:611 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:30:04:611 DEBUG: z - SongsMostPlayed null
2024-08-05 23:30:04:626 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:30:04:626 DEBUG: z - SongsMostPlayed 0
2024-08-05 23:30:04:643 DEBUG: z - CheckMonthlyPlaylist true
2024-08-05 23:30:04:643 DEBUG: z - SongsMostPlayed 0
2024-08-05 23:30:13:510 ERROR: MainActivity - MainActivity.onPause unregisterListener sensorListener java.lang.NullPointerException
	at it.fast4x.rimusic.MainActivity.onPause(SourceFile:6)
	at android.app.Activity.performPause(Activity.java:9188)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1657)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5770)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5731)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5683)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:234)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

2024-08-05 23:33:02:240 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-05 23:33:02:426 DEBUG: u - CheckMonthlyPlaylist false
2024-08-05 23:33:02:520 DEBUG: u - CheckMonthlyPlaylist true
2024-08-05 23:33:02:520 DEBUG: u - SongsMostPlayed null
2024-08-05 23:33:02:536 DEBUG: u - CheckMonthlyPlaylist true
2024-08-05 23:33:02:537 DEBUG: u - SongsMostPlayed 0
2024-08-05 23:33:02:552 DEBUG: u - CheckMonthlyPlaylist true
2024-08-05 23:33:02:553 DEBUG: u - SongsMostPlayed 0
2024-08-05 23:33:06:631 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:670 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:759 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:787 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:819 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:843 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:880 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:903 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:937 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:957 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:06:999 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:021 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:056 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:078 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:109 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:133 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:180 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:206 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:238 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:260 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:296 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:318 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:347 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:368 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:397 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:419 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:446 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:463 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:495 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:514 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:550 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:571 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:602 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:625 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:662 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:684 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:716 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:737 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:769 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:825 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:863 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:888 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:919 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:935 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:962 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:07:981 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:013 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:034 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:063 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:081 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:112 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:131 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:162 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:182 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:213 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:235 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:266 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:288 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:331 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:350 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:384 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:406 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:446 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:467 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:499 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:521 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:553 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:575 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:612 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:633 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:663 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:689 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:771 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:792 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:828 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:851 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:883 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:903 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:934 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:954 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:978 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:08:995 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:027 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:047 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:078 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:100 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:135 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:154 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:180 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:204 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:234 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:259 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:281 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:300 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:327 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:344 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:377 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:394 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:427 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:444 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:477 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:498 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:532 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:559 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:578 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:601 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:627 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:643 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:677 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:694 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:726 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:750 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:780 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:799 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:826 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:843 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:876 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:894 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:927 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:946 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:976 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:09:999 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:026 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:043 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:076 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:096 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:126 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:143 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:176 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:193 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:226 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:243 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:275 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:298 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:325 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:342 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:375 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:392 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:426 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:450 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:478 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:497 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:530 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:546 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:575 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:592 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:625 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:645 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:676 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:711 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:742 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:759 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:792 ERROR: M1 - Playback error: H6.i
2024-08-05 23:33:10:809 ERROR: M1 - Playback error: H6.i

**Comment by fast4x** [comment]
much strange, wait new version
