### ISSUE TITLE
Rimusic closes when the player is maximized on the screen after the last update

### ISSUE THREAD

**Issue by rj-ferreira** [fast4x/RiMusic#3199]
### Steps to reproduce the bug

1 - Chose a music
2 - Try to maximize the main player um the screen
3 - Tha app closes
4 - If the app is re-opened, it starts from the last point.

### Expected behavior

Whem maximize the player, the app should not close.

### Actual behavior

Rimusic's last update closes when I start a new music and maximize the player on screen.

### RiMusic version

0.6.47

### Android version

Android 9

### Additional information

Galaxy TabA 8" 2019 Stock firmware. 

The app has been updated, it is not a clean install.

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Stzyxh** [comment]
I habe an error
`FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 30968
android.content.res.Resources$NotFoundException: File res/ae.webp from xml type xml resource ID #0x7f0700dc
	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1217)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2530)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2506)
	at android.content.res.Resources.getXml(Resources.java:1312)
	at a.a.f0(SourceFile:59)
	at B3.a.i(SourceFile:631)
	at s7.o.n(SourceFile:717)
	at a6.b.c(SourceFile:261)
	at N6.j1.e(SourceFile:236)
	at e0.a.d(SourceFile:44)
	at e0.a.e(SourceFile:9)
	at s7.o.t(SourceFile:1345)
	at E6.l.e(SourceFile:255)
	at e0.a.d(SourceFile:44)
	at e0.a.e(SourceFile:9)
	at A6.i.e(SourceFile:198)
	at e0.a.d(SourceFile:44)
	at e0.a.e(SourceFile:9)
	at F6.d.g(SourceFile:442)
	at e0.a.g(SourceFile:52)
	at O.U.g(SourceFile:170)
	at e0.a.g(SourceFile:52)
	at W.c.b(SourceFile:150)
	at T.R1.a(SourceFile:113)
	at T.S0.b(SourceFile:56)
	at T.G0.g(SourceFile:214)
	at e0.a.g(SourceFile:52)
	at T.U0.g(SourceFile:258)
	at e0.a.g(SourceFile:52)
	at T.A0.a(SourceFile:52)
	at A6.z.g(SourceFile:1206)
	at e0.a.g(SourceFile:52)
	at W.c.b(SourceFile:150)
	at J0.p0.a(SourceFile:395)
	at A6.X.g(SourceFile:1216)
	at e0.a.g(SourceFile:52)
	at W.c.b(SourceFile:150)
	at J0.T.a(SourceFile:627)
	at J0.x1.g(SourceFile:250)
	at e0.a.g(SourceFile:52)
	at W.c.a(SourceFile:233)
	at J0.x1.g(SourceFile:213)
	at e0.a.g(SourceFile:52)
	at W.c.O(SourceFile:15)
	at W.q.p(SourceFile:203)
	at W.u.k(SourceFile:32)
	at W.u0.a(SourceFile:43)
	at W.n.a(SourceFile:5)
	at W.n.a(SourceFile:5)
	at W.u.l(SourceFile:9)
	at W.u.c(SourceFile:3)
	at B.j0.b(SourceFile:529)
	at J0.w.setOnViewTreeOwnersAvailable(SourceFile:7)
	at J0.y1.c(SourceFile:10)
	at J0.y1.m(SourceFile:19)
	at androidx.lifecycle.w.a(SourceFile:23)
	at androidx.lifecycle.x.a(SourceFile:217)
	at B.j0.b(SourceFile:498)
	at J0.w.onAttachedToWindow(SourceFile:120)
	at android.view.View.dispatchAttachedToWindow(View.java:21301)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2823)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2331)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9090)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
	at android.view.Choreographer.doFrame(Choreographer.java:916)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7932)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
	at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1122)
	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1201)
	... 80 more`

**Comment by fast4x** [comment]
Try custom version please 
https://github.com/fast4x/RiMusic/tree/master/customVersion
