### ISSUE TITLE
App crashes after update

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3201]
### Steps to reproduce the bug

1. Have 0.6.46 installed.
2. Update to 0.6.47 (manually as automatically does not work for older versions for now)
3. Start app

### Expected behavior

No Crash.

### Actual behavior

App crashes.

### Logs

<details><summary>Details</summary>
<p>

````
java.lang.IllegalArgumentException: Key "eU0gzQM5n2Q" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at G0.C.H(SourceFile:151)
	at E.T.a(SourceFile:34)
	at C.m.b(SourceFile:21)
	at d8.d.l0(SourceFile:25)
	at C.n.g(SourceFile:592)
	at A6.Y.g(SourceFile:758)
	at G0.E.g(SourceFile:74)
	at I0.u.a(SourceFile:38)
	at q0.Y.i(SourceFile:1)
	at I0.A.a(SourceFile:15)
	at B0.b.a(SourceFile:363)
	at e1.c.y(SourceFile:56)
	at h0.t.a(SourceFile:52)
	at h0.u.c(SourceFile:140)
	at I0.m0.a(SourceFile:3)
	at I0.K.s0(SourceFile:133)
	at I0.F.N(SourceFile:17)
	at I0.F.O(SourceFile:18)
	at I0.T.c(SourceFile:8)
	at I0.T.m(SourceFile:138)
	at I0.T.g(SourceFile:94)
	at I0.T.g(SourceFile:106)
	at I0.T.g(SourceFile:106)
	at I0.T.g(SourceFile:106)
	at I0.T.g(SourceFile:106)
	at I0.T.f(SourceFile:44)
	at I0.K.s0(SourceFile:60)
	at I0.K.a(SourceFile:91)
	at I6.O.g(SourceFile:962)
	at G0.E.g(SourceFile:74)
	at I0.u.a(SourceFile:38)
	at B0.b.a(SourceFile:363)
	at e1.c.y(SourceFile:114)
	at h0.t.a(SourceFile:52)
	at h0.u.c(SourceFile:140)
	at I0.m0.a(SourceFile:3)
	at I0.K.s0(SourceFile:133)
	at I0.F.N(SourceFile:17)
	at I0.F.O(SourceFile:18)
	at I0.T.c(SourceFile:8)
	at I0.T.m(SourceFile:138)
	at I0.T.j(SourceFile:90)
	at J0.w.v(SourceFile:36)
	at J0.w.dispatchDraw(SourceFile:17)
	at android.view.View.draw(View.java:25180)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1179)
	at android.view.View.draw(View.java:25180)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1161)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5706)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

````

</p>
</details> 

### RiMusic version

0.6.47.1

### Android version

14

### Additional information

The issue is still in 0.6.47.1. It can be that the app was previously opened in downloaded/cached which does not exist anymore as it is now unified.

**Comment by twistios** [comment]
It is similar to #3186, but maybe not the same.

**Comment by fast4x** [comment]
Try new custom version please
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
It seems to be fixed, thanks for your log.

**Comment by twistios** [comment]
New custom version seems to work.

**Comment by fast4x** [comment]
Perfect! Thanks
