### ISSUE TITLE
App crashes at startup after recent update

### ISSUE THREAD

**Issue by salvo91able** [fast4x/RiMusic#3315]
### Steps to reproduce the bug

Open app on Android 12 device
(In this case Xiaomi Redmi Note 10S / Rosemary)

### Expected behavior

App crashes at startup with no other way of using it

### Actual behavior

App crashes at startup

### Logs

java.lang.IllegalArgumentException: Key "VZkRAp9XMig was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.

at GO.C.H(SourceFile:151)

at E.T.a(SourceFile:34)

at C.m.b(SourceFile:21)

at dB.d.10(SourceFile:25)

at C.n.g(SourceFile:592)

at A6.Y.g(SourceFile:758)

at GO.Eg(SourceFile:74)

at 10.u.a(SourceFile:38)

at q0.Y.i(SourceFile:1)

at 10.A.a(SourceFile:15)

at BO.b.a(SourceFile:363)

at e1.c.y(SourceFile:56)

at ho.t.a (SourceFile:52)

at h0.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3) at 10.K.s0(SourceFile:133) at 10.K.a(SourceFile:91)

at B.t.g(SourceFile:256)

at 10.u.a(SourceFile:38)

at B.D.i(SourceFile:99)

at 10.A.a(SourceFile:15)

at B.D.I(SourceFile:99)

at 10.A.a(SourceFile:15) at BO.b.a (SourceFile:363)

at e1.c.y(SourceFile:56)

at ho.t.a(SourceFile:52)

at ho.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3)

at 10.K.s0(SourceFile:133)

at 10.K.a(SourceFile:91) at u.m.g(SourceFile:24)

at 10.u.a(SourceFile:38)

at u.B.i(SourceFile:240)

at 10.A.a(SourceFile:15)

at q0.p.i(SourceFile.1)

at 10.A.a(SourceFile:15)

at B.m0.e(SourceFile:37)

at GQ.y.i(SourceFile:B)

at 10.A.a(SourceFile:15)

at BO.b.a(SourceFile:363)

at e1.c.y(SourceFile:56)

at ho.t.a (SourceFile:52)

at h0.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3)

at 10.K.s0(SourceFile:133)

at 10.K.a(SourceFile:91)

at u.f.g(SourceFile:58)

at 10.u.a(SourceFile:38)

at B.S.i(SourceFile:33)

at 10.A.a(SourceFile:15)

at B.D.i(SourceFile:99)

at 10.A.a(SourceFile:15)

at BO.b.a(SourceFile:363)

at el.c.y(SourceFile:56)

at h0.t.a(SourceFile:52)

at h0.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3)

at 10.K.s0(SourceFile:133)

at 10.K.a(SourceFile:91)

at B.d.g(SourceFile:86)

at B.a0.g(SourceFile:40)

at 10.u.a (SourceFile:38)

at B.D.I(SourceFile:99)

at 10.A.a(SourceFile:15)

at BO.b.a (SourceFile:363)

at e1.c.y(SourceFile:56)

at hot.a(SourceFile:52)

at h0.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3)

at 10.K.50(SourceFile:133)

at 10.K.a(SourceFile:91)

at B.t.g(SourceFile:256)

at 10.u.a(SourceFile:38)

at B.D.i(SourceFile:99)

at 10.A.a(SourceFile:15)

at B.V.I(SourceFile:115)

at 10.A.a(SourceFile:15)

at BO.b.a(SourceFile:363)

at e1.c.y(SourceFile:56)

at h0.t.a(SourceFile:52)

at h0.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3)

at 10.K.s0(SourceFile:133)

at 10.K.a(SourceFile:91)

at 16.0.g(SourceFile:962)

at GO.E.g(SourceFile:74)

at 10.u.a(SourceFile:38)

at BO.b.a (SourceFile:363)

at e1.c.y(SourceFile:114)

at ho.t.a (SourceFile:52)

at h0.u.c(SourceFile:140)

at 10.m0.a(SourceFile:3)

at 10.K.s0(SourceFile:133)

at 10.F.N(SourceFile:17)

at 10.F.O(SourceFile:18)

at 10.T.c(SourceFile:8)

at 10. T.m(SourceFile:138)

at 10. T.j(SourceFile:90)

at J0.w.v(SourceFile:36)

at J0 w. dispatchDraw(SourceFile:17)

at android.view.View.draw(View.java:23156)

at

android.view.View.updateDisplayListIfDirty(View.java:2

1974)

at android.view.View.draw(View.java:22858)

android.view.ViewGroup.drawChild(ViewGroup.java:46

at

02)

at

android.view.ViewGroup.dispatchDraw(ViewGroup.jav

a:4360)

at

android.view.View.updateDisplayListifDirty(View.java:2

1965)

at android.view.View.draw(View.java:22858)

android.view.ViewGroup.drawChild(ViewGroup.java:46

at

02)

at

a:4360)

at

1965)

android.view.ViewGroup.dispatchDraw(ViewGroup.jav

android.view.View.updateDisplayListIfDirty(View.java:2

at android.view.View.draw(View.java:22858)

android.view.ViewGroup.drawChild(ViewGroup.java:46

android.view.ViewGroup.dispatch Draw(ViewGroup.jav

at

02)

at

a:4360)

at

android.view.View.updateDisplayListIfDirty(View.java:2

1965)

at android.view.View.draw(View.java:22858)

at

android.view.ViewGroup.drawChild(ViewGroup.java:46

02)

at

android.view.ViewGroup.dispatchDraw(ViewGroup.jav

a:4360)

at

android.view.View.updateDisplay ListifDirty(View.java:2

1965)

at android.view.View.draw(View.java:22858)

at

android.view.ViewGroup.drawChild(ViewGroup.java:46

02)

at

android.view.ViewGroup.dispatchDraw(ViewGroup.jav

a:4360)

at

android.view.View.updateDisplayListIfDirty(View.java:2 1965) at android.view.View.draw(View.java:22858)

at

android.view.ViewGroup.drawChild(ViewGroup.java:46

02)

at

android.view.ViewGroup.dispatchDraw(ViewGroup.jav

a:4360)

at android.view.View.draw(View.java:23156)

at

com.android.internal.policy DecorView.draw(DecorVie

w.java:888)

at

android.view.View.updateDisplayListifDirty(View.java:2 1974)

at

android.view. Threaded Renderer.updateView TreeDispla

yList(Threaded Renderer.java:534)

at

android.view. ThreadedRenderer.updateRootDisplayList

(ThreadedRenderer.java:542)

at

android.view. ThreadedRenderer.draw(Threaded Render

er.java:625)

at

android.view.ViewRootImpl.draw(ViewRootImpl.java:4

837)

at android.view.ViewRootImpl.performDraw(ViewRootim

pl.java:4543)

at

android.view.ViewRootimpl.perform Traversals(ViewRo

otimpl.java:3636)

at

android.view.ViewRootImpl.do Traversal (ViewRootImpl

java:2363)

at

android.view.ViewRootImpl$TraversalRunnable.run(Vi

ewRootImpl.java:9310)

at

android.view. Choreographer$CallbackRecord.run(Chor eographer.java:1129) at

android.view. Choreographer.doCallbacks (Choreograp

her.java:926)

at

android.view. Choreographer.doFrame(Choreographer.j

ava:840)

at

ver.run(Choreographer.java:1114) android.view.ChoreographerSFrameDisplayEventRecei

at android.os.Handler.handleCallback(Handler.java:938)

android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce (Looper.java:210) at android.os.Looper.loop(Looper.java:299)

at

at

android.app.ActivityThread.main(ActivityThread.java:8

298) at java.lang.reflect.Method.invoke(Native Method)

at

com.android.intemal.os.RuntimeInit$MethodAndArgs Caller.run(Runtimelnit.java:576)

at

a:1073)

com.android.internal.os.ZygoteInit.main(ZygoteInit.jav

### RiMusic version

0.6.47.1

### Android version

Android 12

### Additional information

Downgrading is not possible and can't backup my playlists

**Comment by faustaahmad** [comment]
Try update the app to latest version (0.6.48)

**Comment by fast4x** [comment]
You have duplicate songs maybe in download or ondevice. This cause crash, try to install custom version.
