### ISSUE TITLE
App crashes when download 

### ISSUE THREAD

**Issue by victormld** [fast4x/RiMusic#3319]
### Steps to reproduce the bug

1. Open the app
2. Press the download icon

### Expected behavior

Starts downloading the song

### Actual behavior

App crashes

### Logs

2024-08-19T07:05:00.419:	java.lang.RuntimeException: Unable to create service it.fast4x.rimusic.service.MyDownloadService: java.lang.IllegalArgumentException: No such service ComponentInfo{it.fast4x.rimusic/androidx.media3.exoplayer.scheduler.PlatformScheduler$PlatformSchedulerService}
	 android.app.ActivityThread.handleCreateService(ActivityThread.java:4482) 
	 android.app.ActivityThread.access$1900(ActivityThread.java:257) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loop(Looper.java:268) 
	 android.app.ActivityThread.main(ActivityThread.java:8017) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
Caused by:	java.lang.IllegalArgumentException: No such service ComponentInfo{it.fast4x.rimusic/androidx.media3.exoplayer.scheduler.PlatformScheduler$PlatformSchedulerService}
	 android.os.Parcel.createExceptionOrNull(Parcel.java:2378) 
	 android.os.Parcel.createException(Parcel.java:2358) 
	 android.os.Parcel.readException(Parcel.java:2341) 
	 android.os.Parcel.readException(Parcel.java:2283) 
	 android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308) 
	 android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47) 
	 z2.l.i(SourceFile:201) 
	 z2.l.<init>(SourceFile:19) 
	 androidx.media3.exoplayer.offline.DownloadService.onCreate(SourceFile:108) 
	 android.app.ActivityThread.handleCreateService(ActivityThread.java:4470) 
	 android.app.ActivityThread.access$1900(ActivityThread.java:257) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loop(Looper.java:268) 
	 android.app.ActivityThread.main(ActivityThread.java:8017) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
Caused by:	android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1169)
	at android.os.Binder.execTransact(Binder.java:1126)

2024-08-19T07:08:23.649:	java.lang.RuntimeException: Unable to create service it.fast4x.rimusic.service.MyDownloadService: java.lang.IllegalArgumentException: No such service ComponentInfo{it.fast4x.rimusic/androidx.media3.exoplayer.scheduler.PlatformScheduler$PlatformSchedulerService}
	 android.app.ActivityThread.handleCreateService(ActivityThread.java:4482) 
	 android.app.ActivityThread.access$1900(ActivityThread.java:257) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loop(Looper.java:268) 
	 android.app.ActivityThread.main(ActivityThread.java:8017) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
Caused by:	java.lang.IllegalArgumentException: No such service ComponentInfo{it.fast4x.rimusic/androidx.media3.exoplayer.scheduler.PlatformScheduler$PlatformSchedulerService}
	 android.os.Parcel.createExceptionOrNull(Parcel.java:2378) 
	 android.os.Parcel.createException(Parcel.java:2358) 
	 android.os.Parcel.readException(Parcel.java:2341) 
	 android.os.Parcel.readException(Parcel.java:2283) 
	 android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308) 
	 android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47) 
	 z2.l.i(SourceFile:201) 
	 z2.l.<init>(SourceFile:19) 
	 androidx.media3.exoplayer.offline.DownloadService.onCreate(SourceFile:108) 
	 android.app.ActivityThread.handleCreateService(ActivityThread.java:4470) 
	 android.app.ActivityThread.access$1900(ActivityThread.java:257) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loop(Looper.java:268) 
	 android.app.ActivityThread.main(ActivityThread.java:8017) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
Caused by:	android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1169)
	at android.os.Binder.execTransact(Binder.java:1126)

### RiMusic version

0.6.48

### Android version

Android 11

### Additional information

This will happen with every song. Whether is in a playlist or not.

The behavior didn't happened at first. It appeared all of a sudden. The battery optimization is off and all the permission were given

**Comment by fast4x** [comment]
Try custom version please

**Comment by victormld** [comment]
I keep having the same problem

**Comment by fast4x** [comment]
I can’t reproduce the problem, if you can give me some further clue
