### ISSUE TITLE
Music Won't play or download.

### ISSUE THREAD

**Issue by Cold1203** [fast4x/RiMusic#3344]
### Steps to reproduce the bug

1. Fresh install 
2. Go to any artist and add song to the Favorites
3. Go to favorites and press "download all"
4. Some track will download, others won't 
5. If you try to play any song that didn't download it won't 
6. If you search any song that is not in the Favorites, it won't play or download anymore. Just the ones downloaded.
7. This error doesn't happen instantly after download, it can happen right away or minutes after.

### Expected behavior

Song should play and download as always

### Actual behavior

If not downloaded before the bug, song won't play or download anymore

### Screenshots/Screen recordings

![Screenshot_2024-08-21-14-01-06-561_it fast4x rimusic](https://github.com/user-attachments/assets/228e0401-4f73-4820-bb54-59fb044d8317)
![Screenshot_2024-08-21-14-01-04-566_it fast4x rimusic](https://github.com/user-attachments/assets/241956db-e124-4050-b6d4-fc201e2ad378)

### Logs

2024-08-21 13:56:26:454 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-21 13:56:28:857 DEBUG: a - CheckMonthlyPlaylist false
2024-08-21 13:56:28:921 DEBUG: a - CheckMonthlyPlaylist true
2024-08-21 13:56:28:921 DEBUG: a - SongsMostPlayed null
2024-08-21 13:56:28:954 DEBUG: a - CheckMonthlyPlaylist true
2024-08-21 13:56:28:955 DEBUG: a - SongsMostPlayed 0
2024-08-21 13:56:41:927 DEBUG: a - CheckMonthlyPlaylist false
2024-08-21 13:56:41:953 DEBUG: a - CheckMonthlyPlaylist true
2024-08-21 13:56:41:953 DEBUG: a - SongsMostPlayed null
2024-08-21 13:56:41:960 DEBUG: a - CheckMonthlyPlaylist true
2024-08-21 13:56:41:961 DEBUG: a - SongsMostPlayed 0
2024-08-21 13:56:44:386 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-21 13:56:44:639 DEBUG: a - CheckMonthlyPlaylist false
2024-08-21 13:56:44:671 DEBUG: a - CheckMonthlyPlaylist true
2024-08-21 13:56:44:672 DEBUG: a - SongsMostPlayed null
2024-08-21 13:56:44:682 DEBUG: a - CheckMonthlyPlaylist true
2024-08-21 13:56:44:682 DEBUG: a - SongsMostPlayed 0
2024-08-21 13:56:48:893 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET qsTa-vPgt94, 0, -1, qsTa-vPgt94, 6]
2024-08-21 13:56:48:893 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId qsTa-vPgt94 all DataSpec[GET qsTa-vPgt94, 0, -1, qsTa-vPgt94, 6]
2024-08-21 13:56:48:893 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-08-21 13:56:48:893 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-08-21 13:56:48:893 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-08-21 13:56:48:894 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-08-21 13:56:48:894 INFO: q - PlayerService createDataSourceResolverFactory videoId qsTa-vPgt94
2024-08-21 13:56:49:292 ERROR: PlayerService - PlayerService onPlayerErrorChanged u2.h: Source error
	at u2.G.k(SourceFile:52)
	at u2.G.handleMessage(SourceFile:359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: D2.n: Unexpected c0
	at D2.j.run(SourceFile:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: z6.c0
	at z6.q.h(SourceFile:924)
	at q2.D.d(SourceFile:3)
	at q2.E.d(SourceFile:10)
	at B2.T.a(SourceFile:26)
	at D2.j.run(SourceFile:37)
	... 3 more

2024-08-21 13:56:49:292 ERROR: PlayerService - PlayerService onPlayerError u2.h: Source error
	at u2.G.k(SourceFile:52)
	at u2.G.handleMessage(SourceFile:359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: D2.n: Unexpected c0
	at D2.j.run(SourceFile:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: z6.c0
	at z6.q.h(SourceFile:924)
	at q2.D.d(SourceFile:3)
	at q2.E.d(SourceFile:10)
	at B2.T.a(SourceFile:26)
	at D2.j.run(SourceFile:37)
	... 3 more

2024-08-21 13:56:54:168 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET QnZYo3qrA4I, 0, -1, QnZYo3qrA4I, 6]
2024-08-21 13:56:54:169 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId QnZYo3qrA4I all DataSpec[GET QnZYo3qrA4I, 0, -1, QnZYo3qrA4I, 6]
2024-08-21 13:56:54:169 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-08-21 13:56:54:169 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache true
2024-08-21 13:56:54:169 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-08-21 13:56:54:169 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-08-21 13:56:54:170 ERROR: PlayerService - PlayerService onPlayerErrorChanged null
2024-08-21 13:56:57:251 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET bFlZVGGiI7Y, 0, -1, bFlZVGGiI7Y, 6]
2024-08-21 13:56:57:252 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId bFlZVGGiI7Y all DataSpec[GET bFlZVGGiI7Y, 0, -1, bFlZVGGiI7Y, 6]
2024-08-21 13:56:57:252 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-08-21 13:56:57:253 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-08-21 13:56:57:253 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-08-21 13:56:57:253 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-08-21 13:56:57:253 INFO: q - PlayerService createDataSourceResolverFactory videoId bFlZVGGiI7Y
2024-08-21 13:56:57:688 ERROR: PlayerService - PlayerService onPlayerErrorChanged u2.h: Source error
	at u2.G.k(SourceFile:52)
	at u2.G.handleMessage(SourceFile:359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: D2.n: Unexpected c0
	at D2.j.run(SourceFile:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: z6.c0
	at z6.q.h(SourceFile:924)
	at q2.D.d(SourceFile:3)
	at q2.E.d(SourceFile:10)
	at B2.T.a(SourceFile:26)
	at D2.j.run(SourceFile:37)
	... 3 more

2024-08-21 13:56:57:689 ERROR: PlayerService - PlayerService onPlayerError u2.h: Source error
	at u2.G.k(SourceFile:52)
	at u2.G.handleMessage(SourceFile:359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: D2.n: Unexpected c0
	at D2.j.run(SourceFile:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: z6.c0
	at z6.q.h(SourceFile:924)
	at q2.D.d(SourceFile:3)
	at q2.E.d(SourceFile:10)
	at B2.T.a(SourceFile:26)
	at D2.j.run(SourceFile:37)
	... 3 more

### RiMusic version

0.6.48

### Android version

Android 14

### Additional information

Device: Xiaomi 11T Pro on HyperOS 1.0.3.0 UKDMIXM
![Screenshot_2024-08-21-14-06-41-976_com android settings](https://github.com/user-attachments/assets/ea63de6f-8fbb-48dc-b3dd-f5f921a56bc1)

**Comment by fast4x** [comment]
Try  custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Cold1203** [comment]
> Try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

I tried the last custom version and it's giving me the same error, but now a red toast notification appears in the bottom of the screen saying "El identificador del video no se corresponde con el que se solicito" (I have the app in spanish and I don't want to miss translate) 
![Screenshot_2024-08-22-09-00-29-060_it fast4x rimusic](https://github.com/user-attachments/assets/7df2dc8f-88be-4279-b95f-6962d98efe45)

*Btw, I love the app, hope there is something we can do about this error

**Comment by fast4x** [comment]
There is a problem with songs source that not depend by RiMusic but by your geographic location.

**Comment by Cold1203** [comment]
> There is a problem with songs source that not depend by RiMusic but by your geographic location.

I will try a vpn and see if it works, I'm on South America. Thanks for the reply

**Comment by Cold1203** [comment]
I used a VPN and everything works flawlessly now, if anyone have this issue like me, use a VPN it may help
