### ISSUE TITLE
I cant search for music in my playlist 

### ISSUE THREAD

**Issue by Jcarz100204** [fast4x/RiMusic#3508]
### Description

I cant search any letters at my playlist, but numbers work for some reason

### Suggested Solution

Last update it was working i guess

**Comment by fast4x** [comment]
it work 
https://github.com/user-attachments/assets/ecfb2b19-1168-4cd2-8f53-223bb1ba38a7

**Comment by Jcarz100204** [comment]
https://github.com/user-attachments/assets/e87104f2-75ae-4afc-8f46-a27bb2373ca1

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings, after crash, reopen app and paste here crash log

**Comment by Jcarz100204** [comment]
2024-09-01 20:36:20:312 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-09-01 20:36:20:785 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:36:20:831 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:36:20:843 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:36:21:360 ERROR: d - Failed AsyncImage 1 in PlaylistItem java.io.FileNotFoundException: No thumbnails in Downloads directories
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:836)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2045)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1530)
	at J3.b.a(SourceFile:593)
	at K3.i.c(SourceFile:197)
	at K3.i.b(SourceFile:295)
	at K3.g.s(SourceFile:38)
	at m7.a.k(SourceFile:9)
	at F7.L.run(SourceFile:113)
	at F7.v0.run(SourceFile:195)
	at N7.k.run(SourceFile:3)
	at N7.a.run(SourceFile:96)

2024-09-01 20:37:33:687 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-09-01 20:37:34:110 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:34:163 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:34:507 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:34:625 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:34:637 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:35:221 ERROR: d - Failed AsyncImage 1 in PlaylistItem java.io.FileNotFoundException: No thumbnails in Downloads directories
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:836)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2045)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1530)
	at J3.b.a(SourceFile:593)
	at K3.i.c(SourceFile:197)
	at K3.i.b(SourceFile:295)
	at K3.g.s(SourceFile:38)
	at m7.a.k(SourceFile:9)
	at F7.L.run(SourceFile:113)
	at F7.v0.run(SourceFile:195)
	at N7.k.run(SourceFile:3)
	at N7.a.run(SourceFile:96)

2024-09-01 20:37:38:046 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:38:118 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:38:129 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:38:137 DEBUG: p - CheckMonthlyPlaylist false
2024-09-01 20:37:38:721 ERROR: d - Failed AsyncImage 1 in PlaylistItem java.io.FileNotFoundException: No thumbnails in Downloads directories
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:836)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2045)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1530)
	at J3.b.a(SourceFile:593)
	at K3.i.c(SourceFile:197)
	at K3.i.b(SourceFile:295)
	at K3.g.s(SourceFile:38)
	at m7.a.k(SourceFile:9)
	at F7.L.run(SourceFile:113)
	at F7.v0.run(SourceFile:195)
	at N7.k.run(SourceFile:3)
	at N7.a.run(SourceFile:96)

I cant copy crash log just the one that its down

**Comment by twistios** [comment]
You have to reproduce the crash before you are able to copy crash log.

**Comment by Jcarz100204** [comment]
I discovered that it i have like 350+ musics it starts laggin

**Comment by twistios** [comment]
> I discovered that it i have like 350+ musics it starts laggin

For me it (at least scrolling) is very smooth even with >2k songs.
Where do you experience the lag, what are you doing and what "does lag"?

**Comment by Jcarz100204** [comment]
There are some letters that i can write others not
