### ISSUE TITLE
Can't use the app in the new version

### ISSUE THREAD

**Issue by Jabwss** [fast4x/RiMusic#3929]
### Steps to reproduce the bug

1.Enter the app 2.Try to play anything 3.It close

### Expected behavior

Just play music and nothing else

### Actual behavior

It just get closed doesn't work 

### RiMusic version

Last version 0.6.56

### Android version

Android 12

**Comment by fast4x** [comment]
enable debug first.. restart app and after crash send log here

**Comment by OrangeZXZ** [comment]
Same issue on android 14 i will maybe send logs tomorow when ican.

https://github.com/user-attachments/assets/2bb7a89f-a258-4b97-90d4-e7b59a248741

**Comment by OrangeZXZ** [comment]
For information a new instalation of the app dosen't crash.

Just updating an existing one is creating the bug.

**Comment by Jabwss** [comment]
> enable debug first.. restart app and after crash send log here

I can't open the settings to enable debug

**Comment by twistios** [comment]
It seems that this is an error because of an incompatible setting of the previous version which was changed in the new version. Reinstalling the app should fix the issue. If you don't want to do that, then maybe there will be a fix for that but maybe also not (for example I could not find which setting causes the error).

**Comment by fast4x** [comment]
I'll try to find this issue

**Comment by Jacoblightning** [comment]
@fast4x here is a logcat if it helps: `FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 18284
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:353)
	at i8.u.M(SourceFile:33)
	at io.ktor.client.engine.cio.y.C1(SourceFile:527)
	at g8.k.h(SourceFile:136)
	at f0.b.h(SourceFile:52)
	at X.e.a(SourceFile:233)
	at h0.g.f(SourceFile:149)
	at g8.l.p(SourceFile:58)
	at f0.b.g(SourceFile:44)
	at f0.b.p(SourceFile:9)
	at K.n0.e(SourceFile:144)
	at f0.b.f(SourceFile:44)
	at f0.b.e(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1397)
	at v.e.h(SourceFile:269)
	at f0.b.h(SourceFile:52)
	at i4.l.b(SourceFile:937)
	at i4.l.a(SourceFile:228)
	at a8.U.e(SourceFile:531)
	at f0.b.f(SourceFile:44)
	at f0.b.e(SourceFile:9)
	at U.A.h(SourceFile:1089)
	at f0.b.h(SourceFile:52)
	at C.x.h(SourceFile:688)
	at f0.b.h(SourceFile:52)
	at X.e.N(SourceFile:15)
	at X.r.p(SourceFile:203)
	at X.v.k(SourceFile:34)
	at X.t0.a(SourceFile:44)
	at X.p.a(SourceFile:5)
	at X.p.a(SourceFile:5)
	at X.v.l(SourceFile:9)
	at H0.G.i(SourceFile:22)
	at H0.G.h(SourceFile:120)
	at H0.B.T(SourceFile:160)
	at U.A.h(SourceFile:880)
	at H0.D.a(SourceFile:74)
	at J0.u.a(SourceFile:38)
	at B6.g.a(SourceFile:1039)
	at i0.s.f(SourceFile:56)
	at i0.v.a(SourceFile:52)
	at i0.w.d(SourceFile:136)
	at J0.m0.a(SourceFile:3)
	at J0.L.s0(SourceFile:133)
	at J0.L.a(SourceFile:91)
	at C.v.a(SourceFile:85)
	at J0.u.a(SourceFile:38)
	at r0.V.i(SourceFile:1)
	at J0.A.a(SourceFile:15)
	at B6.g.a(SourceFile:1039)
	at i0.s.f(SourceFile:56)
	at i0.v.a(SourceFile:52)
	at i0.w.d(SourceFile:136)
	at J0.m0.a(SourceFile:3)
	at J0.L.s0(SourceFile:133)
	at J0.L.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.u.a(SourceFile:38)
	at v.H.i(SourceFile:246)
	at J0.A.a(SourceFile:15)
	at r0.o.i(SourceFile:1)
	at J0.A.a(SourceFile:15)
	at C.s0.e(SourceFile:30)
	at H0.x.i(SourceFile:8)
	at J0.A.a(SourceFile:15)
	at B6.g.a(SourceFile:1039)
	at i0.s.f(SourceFile:56)
	at i0.v.a(SourceFile:52)
	at i0.w.d(SourceFile:136)
	at J0.m0.a(SourceFile:3)
	at J0.L.s0(SourceFile:133)
	at J0.L.a(SourceFile:91)
	at v.h.a(SourceFile:58)
	at J0.u.a(SourceFile:38)
	at B6.g.a(SourceFile:1039)
	at i0.s.f(SourceFile:56)
	at i0.v.a(SourceFile:52)
	at i0.w.d(SourceFile:136)
	at J0.m0.a(SourceFile:3)
	at J0.L.s0(SourceFile:133)
	at J0.L.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.u.a(SourceFile:38)
	at v.H.i(SourceFile:246)
	at J0.A.a(SourceFile:15)
	at r0.o.i(SourceFile:1)
	at J0.A.a(SourceFile:15)
	at C.s0.e(SourceFile:30)
	at H0.x.i(SourceFile:8)
	at J0.A.a(SourceFile:15)
	at B6.g.a(SourceFile:1039)
	at i0.s.f(SourceFile:56)
	at i0.v.a(SourceFile:52)
	at i0.w.d(SourceFile:136)
	at J0.m0.a(SourceFile:3)
	at J0.L.s0(SourceFile:133)
	at J0.L.a(SourceFile:91)
	at v.h.a(SourceFile:58)
	at J0.u.a(SourceFile:38)
	at B6.g.a(SourceFile:1039)
	at i0.s.f(SourceFile:114)
	at i0.v.a(SourceFile:52)
	at i0.w.d(SourceFile:136)
	at J0.m0.a(SourceFile:3)
	at J0.L.s0(SourceFile:133)
	at J0.F.N(SourceFile:17)
	at J0.F.O(SourceFile:18)
	at J0.U.c(SourceFile:8)
	at J0.U.m(SourceFile:138)
	at J0.U.j(SourceFile:90)
	at K0.w.w(SourceFile:36)
	at K0.w.dispatchDraw(SourceFile:17)
	at android.view.View.draw(View.java:24630)
	at android.view.View.updateDisplayListIfDirty(View.java:23493)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5313)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4975)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4093)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)`

**Comment by Jacoblightning** [comment]
I understand that a debug build logcat would be more helpful but as I am unable to export my database, I dont want to uninstall.

**Comment by twistios** [comment]
It seems that fast4x found the problem. He will probably fix it tomorrow.

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion
