### ISSUE TITLE
App crash when opening song player or settings

### ISSUE THREAD

**Issue by AJ47793** [fast4x/RiMusic#3934]
### Steps to reproduce the bug

1. Click on the three bars at the top right corner and then on settings/click on the song currently playing 

### Expected behavior

Opening the settings / opening the song player

### Actual behavior

The app crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/43e62cba-6b58-4638-b38d-5bcce24b84da

### Logs

Unfortunately cant provide logs since i cant open the settings

### RiMusic version

0.6.56

### Android version

Android 13

### Additional information

The app can still play music, but only if the song player doesnt open

**Comment by Jabwss** [comment]
It happens to me too

**Comment by twistios** [comment]
If you can, reinstall the app. This should fix the issue.

**Comment by Jacoblightning** [comment]
Well you have debug mode enabled so maybe there is some way to get the logs without using the app. E.G. If they are stored on disk. If they are in memory, it would require a memory editor which would be complicated.

**Comment by twistios** [comment]
It seems that fast4x found the problem (if it is the same for everyone).

**Comment by ALMIGHTY-VC** [comment]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:331)
	at i8.u.M(SourceFile:33)
	at i4.o.g0(SourceFile:624)
	at C7.X.h(SourceFile:74)
	at f0.b.h(SourceFile:52)
	at C7.Y.e(SourceFile:180)
	at f0.b.f(SourceFile:44)
	at f0.b.e(SourceFile:9)
	at W7.g.e(SourceFile:338)
	at f0.b.f(SourceFile:44)
	at f0.b.e(SourceFile:9)
	at U.V0.h(SourceFile:394)
	at f0.b.h(SourceFile:52)
	at P.Z.h(SourceFile:170)
	at f0.b.h(SourceFile:52)
	at X.e.b(SourceFile:150)
	at U.X1.a(SourceFile:113)
	at U.Z0.b(SourceFile:45)
	at U.M0.h(SourceFile:219)
	at f0.b.h(SourceFile:52)
	at U.b1.h(SourceFile:260)
	at f0.b.h(SourceFile:52)
	at U.G0.a(SourceFile:52)
	at C.k.h(SourceFile:1124)
	at f0.b.h(SourceFile:52)
	at X.e.b(SourceFile:150)
	at K0.n0.a(SourceFile:395)
	at E.i.h(SourceFile:597)
	at f0.b.h(SourceFile:52)
	at X.e.b(SourceFile:150)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.a(SourceFile:617)
	at K0.v1.h(SourceFile:250)
	at f0.b.h(SourceFile:52)
	at X.e.a(SourceFile:233)
	at K0.v1.h(SourceFile:213)
	at f0.b.h(SourceFile:52)
	at X.e.N(SourceFile:15)
	at X.r.p(SourceFile:203)
	at X.v.k(SourceFile:34)
	at X.t0.a(SourceFile:44)
	at X.p.a(SourceFile:5)
	at X.p.a(SourceFile:5)
	at X.v.l(SourceFile:9)
	at X.v.c(SourceFile:3)
	at C.o0.b(SourceFile:834)
	at K0.w.setOnViewTreeOwnersAvailable(SourceFile:7)
	at K0.w1.c(SourceFile:10)
	at K0.w1.k(SourceFile:19)
	at androidx.lifecycle.w.a(SourceFile:23)
	at androidx.lifecycle.x.T0(SourceFile:216)
	at C.o0.b(SourceFile:803)
	at K0.w.onAttachedToWindow(SourceFile:120)
	at android.view.View.dispatchAttachedToWindow(View.java:19602)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3452)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2106)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1799)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7770)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)


Facing the same problem while playing music from miniplayer still works

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by AJ47793** [comment]
Thank you man youre the goat
