### ISSUE TITLE
Visualizers doesn't work

### ISSUE THREAD

**Issue by github-jl14** [fast4x/RiMusic#3988]
### Version of RiMusic

0.6.56.1

### Android version

11

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any track
3. Click on visualizer on player activity
4. no visualizers working (just blank space on where they are supposed to ne)

### What was your expectation?

Aside from visualizers getting f'ed up, nothing more than i can see

### What more can you tell us? (Optional)

The last 3 visualizers have the logo of the app displayed tho. doing the things the album cover should do in those viasializers

### Logs (Optional)

# Logs

- the fist type of log

2024-10-14 00:53:16:332 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:53:16:393 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:53:16:395 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:53:16:397 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:53:16:398 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:53:16:399 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:53:16:401 INFO: C - PlayerService createDataSourceResolverFactory videoId k0g04t7ZeSw
2024-10-14 00:54:33:532 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:33:533 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:33:534 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:54:33:536 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:54:33:537 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:54:33:538 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:54:33:540 INFO: C - PlayerService createDataSourceResolverFactory videoId k0g04t7ZeSw
2024-10-14 00:54:33:598 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: f3.l: Unexpected o0
	at f3.i.run(SourceFile:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: V7.o0
	at S3.C.h(SourceFile:440)
	at L2.F.b(SourceFile:3)
	at u8.l.b(SourceFile:178)
	at u8.l.b(SourceFile:17)
	at L2.G.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	... 3 more

2024-10-14 00:54:33:700 INFO: C - PlayerService createDataSourceResolverFactory bodyVideoId k0g04t7ZeSw videoId k0g04t7ZeSw
2024-10-14 00:54:33:702 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats available bitrate [video/mp4; codecs="avc1.640020", video/webm; codecs="vp9", video/mp4; codecs="avc1.64001f", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d401e", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d4015", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400c", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400b", video/webm; codecs="vp9", audio/mp4; codecs="mp4a.40.5", audio/mp4; codecs="mp4a.40.2", audio/webm; codecs="opus", audio/webm; codecs="opus", audio/webm; codecs="opus"]
2024-10-14 00:54:33:718 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats selected AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=151318, averageBitrate=136978, contentLength=3518658, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=205501, lastModified=1714793465221479, loudnessDb=0.63999987, audioSampleRate=48000, url=https://rr4---sn-jvhja5g3-hoael.googlevideo.com/videoplayback?expire=1728860074&ei=SvsLZ-S6BqaU1d8Pzvz8wAo&ip=120.29.78.95&id=o-ACuSETDJCJOFbKDdvL9Rn7dRwGv196x-4ihWRSmK82yT&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728838474%2C&mh=Id&mm=31%2C29&mn=sn-jvhja5g3-hoael%2Csn-jvhja5g3-hoaes&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=22&rms=au%2Cau&gcr=ph&initcwndbps=1251250&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=3518658&dur=205.501&lmt=1714793465221479&mt=1728838135&fvip=3&keepalive=yes&fexp=51300761&c=ANDROID_MUSIC&txp=2318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgUgP2hkQdXVz_wDJSkNYEd3sIwI8bExvMb5WKki8lA2sCIQDnDUB8OYljC95br0yIT6Xgne3nSk1YxaBRaxuTs9b4Qg%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRQIgAepOBQeUQHWRtLc-yannSb4AecIhiHz50i1VYCis7P4CIQD6OsXVclgWmgbh90jksW0V9RRBlaxuY2NDUbd7wCdimQ%3D%3D, width=null)
2024-10-14 00:54:34:310 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 524288, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:34:312 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 524288, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:34:313 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:54:34:314 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:54:34:314 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 true
2024-10-14 00:54:34:315 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:56:17:094 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 2883568, -1, k0g04t7ZeSw, 6]
2024-10-14 00:56:17:095 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 2883568, -1, k0g04t7ZeSw, 6]
2024-10-14 00:56:17:096 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:56:17:096 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:56:17:096 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 true
2024-10-14 00:56:17:097 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:56:17:509 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET 65xX7zyr-fA, 0, -1, 65xX7zyr-fA, 6]
2024-10-14 00:56:17:510 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId 65xX7zyr-fA all DataSpec[GET 65xX7zyr-fA, 0, -1, 65xX7zyr-fA, 6]
2024-10-14 00:56:17:511 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache true
2024-10-14 00:56:17:512 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:56:17:513 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:56:17:514 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:58:47:019 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET qFeKKGDoF2E, 0, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:47:020 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId qFeKKGDoF2E all DataSpec[GET qFeKKGDoF2E, 0, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:47:021 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:58:47:021 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:58:47:022 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:58:47:022 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:58:47:023 INFO: C - PlayerService createDataSourceResolverFactory videoId qFeKKGDoF2E
2024-10-14 00:58:47:584 INFO: C - PlayerService createDataSourceResolverFactory bodyVideoId qFeKKGDoF2E videoId qFeKKGDoF2E
2024-10-14 00:58:47:585 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats available bitrate [video/mp4; codecs="avc1.640020", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d401f", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d401e", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d4015", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400c", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400b", video/webm; codecs="vp9", audio/mp4; codecs="mp4a.40.5", audio/mp4; codecs="mp4a.40.2", audio/webm; codecs="opus", audio/webm; codecs="opus", audio/webm; codecs="opus"]
2024-10-14 00:58:47:594 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats selected AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=153641, averageBitrate=142698, contentLength=4842135, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=271461, lastModified=1714861405659597, loudnessDb=-1.0500002, audioSampleRate=48000, url=https://rr1---sn-jvhja5g3-hoar.googlevideo.com/videoplayback?expire=1728860327&ei=R_wLZ-uGN52p1d8P5MeQqA0&ip=120.29.78.95&id=o-AGIH81lif5X3K0ds1CwfbT291av56awTOiyUcIWxvCjy&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728838727%2C&mh=5M&mm=31%2C29&mn=sn-jvhja5g3-hoar%2Csn-jvhja5g3-hoaez&ms=au%2Crdu&mv=m&mvi=1&pl=22&rms=au%2Cau&gcr=ph&initcwndbps=1308750&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=4842135&dur=271.461&lmt=1714861405659597&mt=1728838372&fvip=3&keepalive=yes&fexp=51300761&c=ANDROID_MUSIC&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhALxtNsypTIWJ9OuPD3Nzegv7mIiVrQHpqjPAaKgzHLe0AiEAwGDZJYHNiu9oMvOFLLazegh-RKNxr28wAf_IxnTWzOA%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRgIhAPJnmUzETI1XxqDKBfdw-uT6sPRXpfQtAHzpZG0Knp1kAiEAptnGjraQ32JX6xYx70odGMoPkd9_rqpguJHL_egQAjw%3D, width=null)
2024-10-14 00:58:48:116 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET qFeKKGDoF2E, 524288, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:48:117 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId qFeKKGDoF2E all DataSpec[GET qFeKKGDoF2E, 524288, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:48:118 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:58:48:120 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:58:48:121 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:58:48:122 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 true

- "crash logs" (if necessary)

2024-10-14 00:53:16:332 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:53:16:393 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:53:16:395 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:53:16:397 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:53:16:398 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:53:16:399 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:53:16:401 INFO: C - PlayerService createDataSourceResolverFactory videoId k0g04t7ZeSw
2024-10-14 00:54:33:532 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:33:533 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 0, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:33:534 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:54:33:536 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:54:33:537 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:54:33:538 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:54:33:540 INFO: C - PlayerService createDataSourceResolverFactory videoId k0g04t7ZeSw
2024-10-14 00:54:33:598 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: f3.l: Unexpected o0
	at f3.i.run(SourceFile:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: V7.o0
	at S3.C.h(SourceFile:440)
	at L2.F.b(SourceFile:3)
	at u8.l.b(SourceFile:178)
	at u8.l.b(SourceFile:17)
	at L2.G.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	... 3 more

2024-10-14 00:54:33:700 INFO: C - PlayerService createDataSourceResolverFactory bodyVideoId k0g04t7ZeSw videoId k0g04t7ZeSw
2024-10-14 00:54:33:702 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats available bitrate [video/mp4; codecs="avc1.640020", video/webm; codecs="vp9", video/mp4; codecs="avc1.64001f", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d401e", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d4015", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400c", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400b", video/webm; codecs="vp9", audio/mp4; codecs="mp4a.40.5", audio/mp4; codecs="mp4a.40.2", audio/webm; codecs="opus", audio/webm; codecs="opus", audio/webm; codecs="opus"]
2024-10-14 00:54:33:718 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats selected AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=151318, averageBitrate=136978, contentLength=3518658, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=205501, lastModified=1714793465221479, loudnessDb=0.63999987, audioSampleRate=48000, url=https://rr4---sn-jvhja5g3-hoael.googlevideo.com/videoplayback?expire=1728860074&ei=SvsLZ-S6BqaU1d8Pzvz8wAo&ip=120.29.78.95&id=o-ACuSETDJCJOFbKDdvL9Rn7dRwGv196x-4ihWRSmK82yT&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728838474%2C&mh=Id&mm=31%2C29&mn=sn-jvhja5g3-hoael%2Csn-jvhja5g3-hoaes&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=22&rms=au%2Cau&gcr=ph&initcwndbps=1251250&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=3518658&dur=205.501&lmt=1714793465221479&mt=1728838135&fvip=3&keepalive=yes&fexp=51300761&c=ANDROID_MUSIC&txp=2318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgUgP2hkQdXVz_wDJSkNYEd3sIwI8bExvMb5WKki8lA2sCIQDnDUB8OYljC95br0yIT6Xgne3nSk1YxaBRaxuTs9b4Qg%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRQIgAepOBQeUQHWRtLc-yannSb4AecIhiHz50i1VYCis7P4CIQD6OsXVclgWmgbh90jksW0V9RRBlaxuY2NDUbd7wCdimQ%3D%3D, width=null)
2024-10-14 00:54:34:310 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 524288, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:34:312 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 524288, -1, k0g04t7ZeSw, 6]
2024-10-14 00:54:34:313 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:54:34:314 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:54:34:314 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 true
2024-10-14 00:54:34:315 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:56:17:094 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET k0g04t7ZeSw, 2883568, -1, k0g04t7ZeSw, 6]
2024-10-14 00:56:17:095 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId k0g04t7ZeSw all DataSpec[GET k0g04t7ZeSw, 2883568, -1, k0g04t7ZeSw, 6]
2024-10-14 00:56:17:096 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:56:17:096 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:56:17:096 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 true
2024-10-14 00:56:17:097 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:56:17:509 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET 65xX7zyr-fA, 0, -1, 65xX7zyr-fA, 6]
2024-10-14 00:56:17:510 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId 65xX7zyr-fA all DataSpec[GET 65xX7zyr-fA, 0, -1, 65xX7zyr-fA, 6]
2024-10-14 00:56:17:511 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache true
2024-10-14 00:56:17:512 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:56:17:513 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:56:17:514 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:58:47:019 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET qFeKKGDoF2E, 0, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:47:020 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId qFeKKGDoF2E all DataSpec[GET qFeKKGDoF2E, 0, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:47:021 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:58:47:021 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:58:47:022 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:58:47:022 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-14 00:58:47:023 INFO: C - PlayerService createDataSourceResolverFactory videoId qFeKKGDoF2E
2024-10-14 00:58:47:584 INFO: C - PlayerService createDataSourceResolverFactory bodyVideoId qFeKKGDoF2E videoId qFeKKGDoF2E
2024-10-14 00:58:47:585 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats available bitrate [video/mp4; codecs="avc1.640020", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d401f", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d401e", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d4015", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400c", video/webm; codecs="vp9", video/mp4; codecs="avc1.4d400b", video/webm; codecs="vp9", audio/mp4; codecs="mp4a.40.5", audio/mp4; codecs="mp4a.40.2", audio/webm; codecs="opus", audio/webm; codecs="opus", audio/webm; codecs="opus"]
2024-10-14 00:58:47:594 INFO: C - PlayerService createDataSourceResolverFactory adaptiveFormats selected AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=153641, averageBitrate=142698, contentLength=4842135, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=271461, lastModified=1714861405659597, loudnessDb=-1.0500002, audioSampleRate=48000, url=https://rr1---sn-jvhja5g3-hoar.googlevideo.com/videoplayback?expire=1728860327&ei=R_wLZ-uGN52p1d8P5MeQqA0&ip=120.29.78.95&id=o-AGIH81lif5X3K0ds1CwfbT291av56awTOiyUcIWxvCjy&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728838727%2C&mh=5M&mm=31%2C29&mn=sn-jvhja5g3-hoar%2Csn-jvhja5g3-hoaez&ms=au%2Crdu&mv=m&mvi=1&pl=22&rms=au%2Cau&gcr=ph&initcwndbps=1308750&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=4842135&dur=271.461&lmt=1714861405659597&mt=1728838372&fvip=3&keepalive=yes&fexp=51300761&c=ANDROID_MUSIC&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhALxtNsypTIWJ9OuPD3Nzegv7mIiVrQHpqjPAaKgzHLe0AiEAwGDZJYHNiu9oMvOFLLazegh-RKNxr28wAf_IxnTWzOA%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRgIhAPJnmUzETI1XxqDKBfdw-uT6sPRXpfQtAHzpZG0Knp1kAiEAptnGjraQ32JX6xYx70odGMoPkd9_rqpguJHL_egQAjw%3D, width=null)
2024-10-14 00:58:48:116 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET qFeKKGDoF2E, 524288, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:48:117 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId qFeKKGDoF2E all DataSpec[GET qFeKKGDoF2E, 524288, -1, qFeKKGDoF2E, 6]
2024-10-14 00:58:48:118 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-14 00:58:48:120 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-14 00:58:48:121 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-14 00:58:48:122 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 true

**Comment by NOBELLIST** [comment]
It works on my android 12, i wonder if it might be your device or android version.

**Comment by twistios** [comment]
Maybe the activation of the permission did not work.
