### ISSUE TITLE
Media cannot be played

### ISSUE THREAD

**Issue by Yeby2ihviih** [fast4x/RiMusic#4059]
### Version of RiMusic

0.6.56.1

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

When I want to play any song, most of the time doesnt play and show me a "media cannot be play" message. I used to use a older version and this issue doesnt exist

### What was your expectation?

Fix it

**Comment by PedroH654** [comment]
This problem also occurs with me! We are all waiting for a correction!

**Comment by stickboiadah** [comment]
This issue persists on the new update for me aswell 🙁

**Comment by fast4x** [comment]
click on play again when error

**Comment by Samiul30** [comment]
This was also happened with me 
The bug :
r0 false
2024-10-19 12:29:36:950 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 true
2024-10-19 12:29:41:938 INFO: C - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET -Uw97CvOgKU, 0, -1, -Uw97CvOgKU, 6]
2024-10-19 12:29:41:940 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId -Uw97CvOgKU all DataSpec[GET -Uw97CvOgKU, 0, -1, -Uw97CvOgKU, 6]
2024-10-19 12:29:41:940 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-10-19 12:29:41:941 INFO: C - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-10-19 12:29:41:941 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-10-19 12:29:41:941 INFO: C - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-10-19 12:29:41:941 INFO: C - PlayerService createDataSourceResolverFactory videoId -Uw97CvOgKU
2024-10-19 12:29:43:118 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
 at P2.O.j(SourceFile:17)
 at P2.O.handleMessage(SourceFile:386)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: f3.l: Unexpected o0
 at f3.i.run(SourceFile:137)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: V7.o0
 at S3.C.h(SourceFile:440)
 at L2.F.b(SourceFile:3)
 at u8.l.b(SourceFile:178)
 at u8.l.b(SourceFile:17)
 at L2.G.b(SourceFile:10)
 at b3.M.d(SourceFile:26)
 at f3.i.run(SourceFile:37)
 ... 3 more

2024-10-19 12:29:43:135 ERROR: k - Playback error: V7.o0
2024-10-19 12:29:43:139 ERROR: k - Playback error: V7.o0
2024-10-19 12:29:43:283 ERROR: k - Playback error: V7.o0
2024-10-19 12:29:43:289 ERROR: k - Playback error: V7.o0
2024-10-19 12:29:49:988 ERROR: k - Playback error: V7.o0

OS: Android 14, arch 64

**Comment by MysioPysio017** [comment]
> click on play again when error 

It works only sometimes, sometimes it shows the error message again and sometimes it plays

**Comment by fast4x** [comment]
Try this custom version please 

https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Samiul30** [comment]
> Try this custom version please 
> 
> https://github.com/fast4x/RiMusic/tree/master/customVersion

I will let you know soon after tryig

**Comment by MysioPysio017** [comment]
> Try this custom version please 
> 
> https://github.com/fast4x/RiMusic/tree/master/customVersion

Working fine for now, I'll after using a while 😇

**Comment by goskum** [comment]
> Try this custom version please
> 
> https://github.com/fast4x/RiMusic/tree/master/customVersion

Thank you so much!, it's working for me too.
