### ISSUE TITLE
Song can't be played, again...

### ISSUE THREAD

**Issue by Elevere** [fast4x/RiMusic#4106]
### Version of RiMusic

0.6.57.1 Official

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a music
3. Boom! Music can't be played

### Submit a video

Can't screen record, but here is a screenshot
![Screenshot_20241024_095333](https://github.com/user-attachments/assets/ab9c86fe-d58f-4fc4-883d-f2f5b9ff93c2)

### What was your expectation?

Should be playing normally like yesterday

### What more can you tell us? (Optional)

Yesterday was dandy, today is lousy 😔
Checked YT Music and it worked perfectly

### Logs (Optional)

2024-10-24 09:59:16:390 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-24 09:59:21:862 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 09:59:21:882 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:23:913 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:25:471 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:26:416 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:27:118 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:070 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 09:59:38:083 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:087 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:142 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:245 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:273 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:305 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:320 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:349 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:362 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:382 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:394 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:416 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:429 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:450 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:464 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:483 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:494 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:516 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:528 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:549 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:563 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:582 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:594 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:616 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:628 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:649 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:661 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:683 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:696 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:716 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:730 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:752 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:766 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:782 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:795 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:815 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:826 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:849 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:860 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:883 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:896 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:917 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:930 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:949 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:962 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:982 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:38:996 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:027 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:037 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:060 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:087 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:115 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:153 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:183 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:207 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:237 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:257 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:282 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:317 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:349 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:367 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:384 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:400 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:426 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:445 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:471 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:490 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:515 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:532 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:560 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:578 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:604 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:617 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:637 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:651 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:671 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:684 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:704 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:716 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:738 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:754 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:772 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:784 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:804 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:818 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:837 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:851 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:871 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:883 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:904 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:916 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:938 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:952 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:970 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:39:983 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:004 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:018 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:037 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:051 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:071 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:083 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:104 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:117 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:190 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:205 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:227 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:241 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:259 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:270 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:293 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:306 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:326 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:339 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:359 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:374 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:393 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:406 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:427 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:439 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:460 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:472 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:492 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:504 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:526 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:542 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:559 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:574 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:592 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:610 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:636 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:666 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:692 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:709 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:742 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:757 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:777 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:792 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:814 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:829 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:847 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:864 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:883 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:907 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:927 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:938 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:959 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:970 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:40:993 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:005 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:027 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:040 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:059 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:072 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:092 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:104 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:125 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:138 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:159 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:172 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:193 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:206 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:226 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:239 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:259 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:272 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:292 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:304 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:326 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:340 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:359 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:374 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:392 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:411 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:437 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:450 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:470 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:483 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:503 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:515 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:536 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:548 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:570 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:582 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:603 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:622 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:647 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:670 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:694 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:712 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:736 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:752 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:781 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:799 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:825 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:840 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:860 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:881 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:903 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:916 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:936 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:41:981 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:003 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:019 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:047 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:063 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:081 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:102 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:147 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:191 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:214 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:230 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:247 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:258 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:281 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:291 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:314 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:326 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:347 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:359 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:381 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:392 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:414 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:425 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:447 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:458 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:482 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:494 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:514 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:528 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:547 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:558 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:581 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:591 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:614 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:628 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:647 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:659 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:680 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:692 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:714 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:724 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:747 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:758 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:781 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:792 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:814 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:825 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:847 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:858 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:880 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:892 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:42:914 ERROR: Q1 - Playback error: java.lang.NullPointerException: uriString
2024-10-24 09:59:45:580 ERROR: n - Playback error: java.lang.NullPointerException: uriString

**Comment by aneesh1122** [comment]
Man my thumbs hurt just by scrolling through that log 

Anyways, all the yt music apps where you don't login are affected

**Comment by Elevere** [comment]
> Man my thumbs hurt just by scrolling through that log
> 
> Anyways, all the yt music apps where you don't login are affected

Which means?

**Comment by PoPo-7** [comment]
I’m dealing with this too. Rimusic is definitely the best one I’ve tried, and I really hope it doesn’t just stop working! 😭

**Comment by Nandkishor01** [comment]
> Which means?

Yt music is trying to push Login to everyone so every app that used to play songs using ytmusic api without logging in are affected.

**Comment by Elevere** [comment]
> > Which means?
> 
> Yt music is trying to push Login to everyone so every app that used to play songs using ytmusic api without logging in are affected.
> 
> I hope Devs could fix this soon.

Thanks for the info!

**Comment by fast4x** [comment]
Working progress

**Comment by fast4x** [comment]
> I’m dealing with this too. Rimusic is definitely the best one I’ve tried, and I really hope it doesn’t just stop working! 😭

wait for fix

**Comment by Elevere** [comment]
> > I’m dealing with this too. Rimusic is definitely the best one I’ve tried, and I really hope it doesn’t just stop working! 😭
> 
> wait for fix

Thanks!
