### ISSUE TITLE
Problem with downloading and playing music 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4119]
### Version of RiMusic

0.6.57.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

First of all, I would like to congratulate you on your excellent work. Among so many applications, your application is unique! Simply unique, different from the ordinary. Even Even though Ri Music may have errors, the app is still incredible. I am in awe of this app. 

Now speaking about bugs, it is now clear that the music download bug is not due to YouTube blocking. I have already downloaded some songs without any problems, but later (a day or hours later), these same songs that were downloaded are as if I had not downloaded them. In other words, it goes back to normal and I have to download it again.

Another issue I've been experiencing is playing some songs. I have already played certain songs normally, but when I try to search for X song, it doesn't play anything. Likewise, the music that was previously possible to hear normally no longer plays. 

Other than that, the app is wonderful. I only face these "problems", bugs. 

### Submit a video

https://github.com/user-attachments/assets/e291d8d0-c0ea-4877-a782-76cb182dfb22

### What was your expectation?

Play the songs you always listened to and download works

### What more can you tell us? (Optional)

Just thank you for the great work and if you can (you are able) fix these bugs. 

### Logs (Optional)

2024-10-24 15:08:28:537 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-24 15:08:29:096 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:08:29:136 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:08:29:145 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:08:29:145 DEBUG: q - SongsMostPlayed null
2024-10-24 15:08:29:154 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:08:29:155 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:08:35:224 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:08:35:255 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:08:35:257 DEBUG: q - SongsMostPlayed null
2024-10-24 15:08:35:283 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:08:35:285 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:09:16:526 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:09:16:562 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:16:563 DEBUG: q - SongsMostPlayed null
2024-10-24 15:09:16:584 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:16:585 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:09:31:030 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:09:31:062 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:31:063 DEBUG: q - SongsMostPlayed null
2024-10-24 15:09:31:082 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:31:082 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:09:39:695 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:09:39:716 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:39:716 DEBUG: q - SongsMostPlayed null
2024-10-24 15:09:39:733 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:39:734 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:09:43:834 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:09:43:860 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:43:861 DEBUG: q - SongsMostPlayed null
2024-10-24 15:09:43:876 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:09:43:876 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:09:57:409 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:09:57:429 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:13:719 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:10:13:737 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:17:962 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:10:18:019 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:10:18:020 DEBUG: q - SongsMostPlayed null
2024-10-24 15:10:18:045 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:10:18:048 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:10:19:108 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:10:19:126 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:19:128 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:20:383 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:30:194 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:10:30:220 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:39:579 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:10:39:593 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:40:063 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:10:40:089 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:40:178 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:10:40:179 DEBUG: q - SongsMostPlayed null
2024-10-24 15:10:40:208 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:10:40:209 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:10:44:425 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:45:665 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:10:45:668 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:45:699 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:10:45:700 DEBUG: q - SongsMostPlayed null
2024-10-24 15:10:45:715 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:10:45:717 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:10:46:095 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:10:58:821 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:10:58:832 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:11:07:058 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:11:07:079 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:11:26:552 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:11:26:635 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:11:26:637 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:11:26:659 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:11:26:660 DEBUG: q - SongsMostPlayed null
2024-10-24 15:11:26:716 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:11:26:717 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:11:30:438 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:14:31:854 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:14:31:870 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:14:31:902 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:14:31:903 DEBUG: q - SongsMostPlayed null
2024-10-24 15:14:31:945 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:14:31:945 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:14:33:438 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:14:53:101 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:14:53:111 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:14:55:095 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:14:55:105 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:14:55:174 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:14:55:175 DEBUG: q - SongsMostPlayed null
2024-10-24 15:14:55:222 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:14:55:223 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:14:55:909 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:15:10:651 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:15:10:661 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:15:24:410 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:16:29:360 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:16:29:624 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:16:31:411 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:31:34:142 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:31:34:165 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:31:34:227 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:31:34:227 DEBUG: q - SongsMostPlayed null
2024-10-24 15:31:34:302 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:31:34:302 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:31:37:427 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:31:37:464 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:31:37:465 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:31:37:472 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:31:37:473 DEBUG: q - SongsMostPlayed null
2024-10-24 15:31:37:502 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:31:37:502 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:31:48:898 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:32:08:430 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:32:08:475 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:32:08:477 DEBUG: q - SongsMostPlayed null
2024-10-24 15:32:08:525 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:32:08:526 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:32:09:624 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:32:09:638 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:32:10:527 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:32:10:531 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:32:10:570 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:32:10:570 DEBUG: q - SongsMostPlayed null
2024-10-24 15:32:10:582 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:32:10:583 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:32:10:958 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:32:13:066 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:32:21:881 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:32:21:929 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:32:21:929 DEBUG: q - SongsMostPlayed null
2024-10-24 15:32:21:942 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:

**Comment by knighthat** [comment]
YT is actively blocking third-party clients, that's why you get this message. I just pushed #4122, let's hope that the owner accept it

**Comment by bauldihr** [comment]
Some songs are from YouTube, but others are not.
