### ISSUE TITLE
Some music doesn't want to be play

### ISSUE THREAD

**Issue by Ask1ew** [fast4x/RiMusic#4227]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

When i want to play some music. Sometimes, some titles doesn't want to play. See error message bollow

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

To play everything without a problem

### Logs (Optional)

2024-10-27 00:12:08:479 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-27 00:12:09:428 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:09:473 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:09:528 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:24:873 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.o0
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.o0
	at v7.c.L(SourceFile:452)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:12:24:882 ERROR: c - Playback error: W7.o0
2024-10-27 00:12:24:961 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:24:966 ERROR: c - Playback error: W7.o0
2024-10-27 00:12:27:904 ERROR: c - Playback error: W7.o0

**Comment by Ask1ew** [comment]
For example, the title: Garçon de mon âge from TheFeenchKrid

**Comment by fast4x** [comment]
try to login...

**Comment by Ask1ew** [comment]
I'm already log on

**Comment by Ask1ew** [comment]
I log out ans log in again, I close the app and try again the song, see bellow the logs:

2024-10-27 00:12:08:479 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-27 00:12:09:428 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:09:473 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:09:528 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:24:873 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.o0
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.o0
	at v7.c.L(SourceFile:452)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:12:24:882 ERROR: c - Playback error: W7.o0
2024-10-27 00:12:24:961 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:24:966 ERROR: c - Playback error: W7.o0
2024-10-27 00:12:27:904 ERROR: c - Playback error: W7.o0
2024-10-27 00:23:39:217 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:23:39:254 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:23:39:316 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:23:43:139 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.o0
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.o0
	at v7.c.L(SourceFile:452)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:23:43:151 ERROR: c - Playback error: W7.o0
2024-10-27 00:23:48:613 ERROR: f - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-10-27 00:23:50:121 ERROR: f - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-10-27 00:23:51:267 ERROR: f - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-10-27 00:23:53:049 ERROR: c - Playback error: W7.o0
2024-10-27 00:23:57:937 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.i
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.i
	at v7.c.L(SourceFile:467)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:23:57:947 ERROR: c - Playback error: W7.i
2024-10-27 00:24:04:438 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.i
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.i
	at v7.c.L(SourceFile:467)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:24:04:447 ERROR: c - Playback error: W7.i

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Ask1ew** [comment]
Find below the debug log :

2024-10-27 00:12:08:479 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-27 00:12:09:428 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:09:473 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:09:528 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:24:873 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.o0
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.o0
	at v7.c.L(SourceFile:452)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:12:24:882 ERROR: c - Playback error: W7.o0
2024-10-27 00:12:24:961 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:12:24:966 ERROR: c - Playback error: W7.o0
2024-10-27 00:12:27:904 ERROR: c - Playback error: W7.o0
2024-10-27 00:23:39:217 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:23:39:254 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:23:39:316 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:23:43:139 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.o0
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.o0
	at v7.c.L(SourceFile:452)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:23:43:151 ERROR: c - Playback error: W7.o0
2024-10-27 00:23:48:613 ERROR: f - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-10-27 00:23:50:121 ERROR: f - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-10-27 00:23:51:267 ERROR: f - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-10-27 00:23:53:049 ERROR: c - Playback error: W7.o0
2024-10-27 00:23:57:937 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.i
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.i
	at v7.c.L(SourceFile:467)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:23:57:947 ERROR: c - Playback error: W7.i
2024-10-27 00:24:04:438 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.i
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.i
	at v7.c.L(SourceFile:467)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:24:04:447 ERROR: c - Playback error: W7.i
2024-10-27 00:25:45:758 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.i
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.i
	at v7.c.L(SourceFile:467)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 00:25:45:769 ERROR: c - Playback error: W7.i
2024-10-27 00:25:50:642 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:25:50:647 ERROR: c - Playback error: W7.i
2024-10-27 00:25:50:658 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:25:50:659 ERROR: c - Playback error: W7.i
2024-10-27 00:27:25:055 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:27:25:073 ERROR: c - Playback error: W7.i
2024-10-27 00:27:25:092 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:27:25:093 ERROR: c - Playback error: W7.i
2024-10-27 00:27:29:580 ERROR: c - Playback error: W7.i
2024-10-27 00:27:42:223 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:27:42:228 ERROR: c - Playback error: W7.i
2024-10-27 00:27:42:285 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:27:42:286 ERROR: c - Playback error: W7.i
2024-10-27 00:27:52:797 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:27:54:958 ERROR: c - Playback error: W7.i
2024-10-27 00:28:14:464 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:28:14:469 ERROR: c - Playback error: W7.i
2024-10-27 00:28:14:529 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 00:28:14:530 ERROR: c - Playback error: W7.i
2024-10-27 17:23:12:856 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-27 17:23:13:106 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 17:23:13:253 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 17:23:13:325 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 17:23:25:540 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.o0
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.o0
	at v7.c.L(SourceFile:452)
	at W7.h.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 17:23:25:551 ERROR: c - Playback error: W7.o0
2024-10-27 17:31:25:812 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 17:31:25:820 ERROR: c - Playback error: W7.o0
2024-10-27 17:31:26:073 DEBUG: c - CheckMonthlyPlaylist false
2024-10-27 17:31:26:074 ERROR: c - Playback error: W7.o0
2024-10-27 17:38:46:219 ERROR: c - Playback error: W7.o0
2024-10-29 10:55:29:412 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-29 10:55:31:051 DEBUG: G - CheckMonthlyPlaylist false
2024-10-29 10:55:31:162 DEBUG: G - CheckMonthlyPlaylist false
2024-10-29 10:55:31:265 DEBUG: G - CheckMonthlyPlaylist false
2024-10-29 10:55:46:001 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.P.j(SourceFile:17)
	at P2.P.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.t0
	at C5.m.i(SourceFile:134)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.b(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.t0
	at w8.e0.R(SourceFile:259)
	at W7.k.v(SourceFile:11)
	at D8.a.k(SourceFile:9)
	at X8.N.run(SourceFile:107)
	at X8.Z.B0(SourceFile:76)
	at X8.G.C(SourceFile:105)
	at C5.m.i(SourceFile:109)
	... 7 more

2024-10-29 10:55:46:014 ERROR: x - Playback error: W7.t0
2024-10-29 10:56:01:534 DEBUG: G - CheckMonthlyPlaylist false
2024-10-29 10:56:05:042 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.P.j(SourceFile:17)
	at P2.P.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: W7.t0
	at C5.m.i(SourceFile:134)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.b(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: W7.t0
	at w8.e0.R(SourceFile:259)
	at W7.k.v(SourceFile:11)
	at D8.a.k(SourceFile:9)
	at X8.N.run(SourceFile:107)
	at X8.Z.B0(SourceFile:76)
	at X8.G.C(SourceFile:105)
	at C5.m.i(SourceFile:109)
	... 7 more

2024-10-29 10:56:05:050 ERROR: x - Playback error: W7.t0
2024-10-29 10:56:08:843 ERROR: x - Playback error: W7.t0
