### ISSUE TITLE
Error in playback in RiMusic

### ISSUE THREAD

**Issue by EduardoMusic** [fast4x/RiMusic#4251]
### Version of RiMusic

0.6.58.1

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on search 
3. Click on music
4. Boom! Crash happens

### Submit a video

Hello, When I open RiMusic and search for music in the Search Engine, a message automatically appears stating that it does not play, "An error occurred while playing" That's the message, and it also doesn't download songs to have them without a Wi-Fi connection. I hope they fix this little problem, the design is all right.

### What was your expectation?

none

### What more can you tell us? (Optional)

Please fix it and I congratulate you for creating such a good APK.

### Logs (Optional)

2024-10-27 12:24:20:004 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-27 12:24:33:217 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:507)
	at android.net.Uri$StringUri.<init>(Uri.java:497)
	at android.net.Uri.parse(Uri.java:469)
	at v7.c.E(SourceFile:198)
	at W7.f.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 12:24:37:238 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:507)
	at android.net.Uri$StringUri.<init>(Uri.java:497)
	at android.net.Uri.parse(Uri.java:469)
	at v7.c.E(SourceFile:198)
	at W7.f.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

2024-10-27 12:24:41:540 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:68)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:507)
	at android.net.Uri$StringUri.<init>(Uri.java:497)
	at android.net.Uri.parse(Uri.java:469)
	at v7.c.E(SourceFile:198)
	at W7.f.v(SourceFile:11)
	at C8.a.i(SourceFile:9)
	at W8.M.run(SourceFile:107)
	at W8.Y.A0(SourceFile:76)
	at W8.F.C(SourceFile:105)
	at C5.m.k(SourceFile:43)
	... 7 more

**Comment by fast4x** [comment]
Try to login with YT

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion
