### ISSUE TITLE
Playback errors with some songs

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#4321]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Since the introduction of the YTM registration, some songs from my library are no longer played,

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

x

### Logs (Optional)

2024-11-01 20:30:20:711 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-01 20:30:20:901 ERROR: PlayerService - Failed onDestroy in PlayerService java.lang.IllegalArgumentException: Receiver not registered: W7.F@b0ca43e
 at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1691)
 at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1883)
 at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:831)
 at it.fast4x.rimusic.service.PlayerService.onDestroy(SourceFile:44)
 at android.app.ActivityThread.handleStopService(ActivityThread.java:5083)
 at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.app.ActivityThread.main(ActivityThread.java:8763)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-11-01 20:30:35:791 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
 at P2.O.j(SourceFile:17)
 at P2.O.handleMessage(SourceFile:386)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
 at C5.m.k(SourceFile:68)
 at L2.E.b(SourceFile:3)
 at L2.F.b(SourceFile:10)
 at b3.M.d(SourceFile:26)
 at f3.i.run(SourceFile:37)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
 at android.net.Uri$StringUri.<init>(Uri.java:504)
 at android.net.Uri$StringUri.<init>(Unknown Source:0)
 at android.net.Uri.parse(Uri.java:466)
 at v7.c.E(SourceFile:198)
 at W7.f.v(SourceFile:11)
 at C8.a.i(SourceFile:9)
 at W8.M.run(SourceFile:107)
 at W8.Y.A0(SourceFile:76)
 at W8.F.C(SourceFile:105)
 at C5.m.k(SourceFile:43)
 ... 7 more

2024-11-01 20:30:35:805 ERROR: c - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:35:809 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:35:857 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:35:954 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:35:978 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:014 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:035 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:061 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:083 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:108 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:136 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:174 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:195 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:227 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:252 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:291 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:307 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:341 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:358 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:392 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:415 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:445 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:466 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:497 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:519 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:549 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:569 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:593 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:618 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:648 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:669 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:700 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:721 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:759 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:779 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:810 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:830 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:862 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:888 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:918 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:932 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:976 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:36:999 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:030 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:050 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:080 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:102 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:133 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:155 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:185 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:200 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:241 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:256 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:301 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:321 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:351 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:366 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:408 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:423 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:460 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:482 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:513 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:534 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:565 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:589 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:620 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:635 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:676 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:690 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:727 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:749 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:780 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:801 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:831 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:857 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:966 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:37:985 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:014 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:042 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:078 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:099 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:129 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:150 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:185 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:207 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:245 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:266 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:299 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:321 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:349 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:365 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:412 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:429 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:462 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:480 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:513 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:534 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:566 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:593 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:630 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:650 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:681 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:705 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:735 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:756 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:788 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:810 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:847 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:867 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:898 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:918 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:949 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:38:970 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:003 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:024 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:055 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:076 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:106 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:128 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:164 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:184 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:215 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:235 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:266 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:287 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:317 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:338 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:368 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:392 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:423 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:444 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:474 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:495 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:532 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:552 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:582 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:603 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:634 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:654 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:685 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:706 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:736 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:760 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:791 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:812 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:842 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:865 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:938 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:959 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:39:989 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:011 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:050 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:071 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:100 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:129 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:159 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:184 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:217 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:238 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:269 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:292 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:323 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:345 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:376 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:404 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:436 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:457 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:488 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:513 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:551 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:570 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:601 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:618 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:651 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:668 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:701 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:718 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:751 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:769 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:818 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:835 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:868 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:888 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:919 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:40:939 ERROR: R1 - Playback error: java.lang.NullPointerException: uriString
2024-11-01 20:30:43:163 ERROR: c - Playback error: java.lang.NullPointerException: uriString

**Comment by twistios** [comment]
Have you tried to clear the android app cache?

**Comment by twistios** [comment]
Does it also fail for cached/downloaded songs?

**Comment by siggi1984** [comment]
> Have you tried to clear the android app cache?

Cleared cache, reinstalled, error remains.

**Comment by siggi1984** [comment]
> There is a similar error when not logged in. You may not be logged in correctly

The songs work in the latest debug version. I'll wait for the next update.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.59
