### ISSUE TITLE
App Crashes at Start

### ISSUE THREAD

**Issue by skyGtm** [fast4x/RiMusic#4326]
### Version of RiMusic

0.6.58.1

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Boom! Crash happens

### What was your expectation?

App should open.

### What more can you tell us? (Optional)

After installing the latest version of the app 0.6.58.1, app doesn't open. And the Scoop app captures crash log.
I tried uninstalling, and reinstalling the app.

### Logs (Optional)

Crash log captured by Scoop:

```
FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 1186
java.lang.RuntimeException: Unable to start activity ComponentInfo{it.fast4x.rimusic/it.fast4x.rimusic.MainActivity}: android.content.res.Resources$NotFoundException: Drawable it.fast4x.rimusic:drawable/compat_splash_screen with resource ID #0x7f0800bf
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2804)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: android.content.res.Resources$NotFoundException: Drawable it.fast4x.rimusic:drawable/compat_splash_screen with resource ID #0x7f0800bf
Caused by: android.content.res.Resources$NotFoundException: Drawable it.fast4x.rimusic:mipmap/ic_logo with resource ID #0x7f0f0003
Caused by: android.content.res.Resources$NotFoundException: Resource "it.fast4x.rimusic:mipmap/ic_logo" (7f0f0003) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0f0003 a=-1 r=0x7f0f0003}
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:897)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
	at android.content.res.Resources.loadDrawable(Resources.java:921)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:983)
	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:391)
	at android.graphics.drawable.LayerDrawable.applyTheme(LayerDrawable.java:230)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:778)
	at android.content.res.Resources.getDrawable(Resources.java:834)
	at android.content.Context.getDrawable(Context.java:529)
	at B1.a.b(SourceFile:1)
	at q.N0.g(SourceFile:237)
	at k.z.q(SourceFile:55)
	at k.z.z(SourceFile:17)
	at k.z.e(SourceFile:8)
	at k.h.a(SourceFile:21)
	at androidx.activity.ComponentActivity.onCreate(SourceFile:33)
	at androidx.fragment.app.FragmentActivity.onCreate(SourceFile:1)
	at it.fast4x.rimusic.MainActivity.onCreate(SourceFile:2)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by skyGtm** [comment]
this issue looks similar to https://github.com/fast4x/RiMusic/issues/4275 but it doesnot have crash log.

**Comment by fast4x** [comment]
Nice log, I'll check it thanks

**Comment by fast4x** [comment]
It seems to be solved in next version 0.6.59, report if it work after release, thanks

**Comment by skyGtm** [comment]
I just installed github release  version:0.6.59
The problem has not been solved. Stll get the same crash log.

```
FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 28069
java.lang.RuntimeException: Unable to start activity ComponentInfo{it.fast4x.rimusic/it.fast4x.rimusic.MainActivity}: android.content.res.Resources$NotFoundException: Drawable it.fast4x.rimusic:drawable/compat_splash_screen with resource ID #0x7f0800c2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2804)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: android.content.res.Resources$NotFoundException: Drawable it.fast4x.rimusic:drawable/compat_splash_screen with resource ID #0x7f0800c2
Caused by: android.content.res.Resources$NotFoundException: Drawable it.fast4x.rimusic:mipmap/ic_launcher_splash with resource ID #0x7f0f0003
Caused by: android.content.res.Resources$NotFoundException: Resource "it.fast4x.rimusic:mipmap/ic_launcher_splash" (7f0f0003) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0f0003 a=-1 r=0x7f0f0003}
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:897)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
	at android.content.res.Resources.loadDrawable(Resources.java:921)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:983)
	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:391)
	at android.graphics.drawable.LayerDrawable.applyTheme(LayerDrawable.java:230)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:778)
	at android.content.res.Resources.getDrawable(Resources.java:834)
	at android.content.Context.getDrawable(Context.java:529)
	at F1.a.b(SourceFile:1)
	at q.O0.g(SourceFile:237)
	at k.z.q(SourceFile:55)
	at k.z.z(SourceFile:17)
	at k.z.e(SourceFile:8)
	at k.i.a(SourceFile:21)
	at androidx.activity.ComponentActivity.onCreate(SourceFile:33)
	at androidx.fragment.app.FragmentActivity.onCreate(SourceFile:1)
	at it.fast4x.rimusic.MainActivity.onCreate(SourceFile:2)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by skyGtm** [comment]
Last version v0.6.60 did not work.
Just installed latest version "v0.6.61", now the app opens. No issues so far.
Thank you for your hard work.
