### ISSUE TITLE
The player closes abruptly

### ISSUE THREAD

**Issue by filipemanuelofs** [fast4x/RiMusic#4391]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song in a playlist
3. The song doesn't start
4. The player closes abruptly

### Submit a video

https://github.com/user-attachments/assets/7b412741-5945-48fa-b3a3-a6b1d4d4015d

### What was your expectation?

That the music plays and the player doesn't close.

### Logs (Optional)

2024-11-08 17:17:49:099 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-08 17:17:56:124 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-08 17:17:56:254 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:17:56:298 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:17:56:324 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:18:01:853 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:18:04:192 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:18:16:804 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at a.a.s0(SourceFile:173)
	at b8.g.v(SourceFile:11)
	at H8.a.k(SourceFile:9)
	at h9.q.x(SourceFile:7)
	at b9.a.k(SourceFile:23)
	at H8.a.k(SourceFile:32)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more

2024-11-08 17:24:27:033 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-08 17:24:31:374 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:24:31:422 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:25:42:461 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:25:42:482 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:25:56:170 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: K6.a: No suitable converter found for TypeInfo(type=class R9.f (Kotlin reflection is not available), reifiedType=class R9.f, kotlinType=R9.f (Kotlin reflection is not available))
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: K6.a: No suitable converter found for TypeInfo(type=class R9.f (Kotlin reflection is not available), reifiedType=class R9.f, kotlinType=R9.f (Kotlin reflection is not available))
	at W8.o.z(SourceFile:136)
	at K6.h.b(SourceFile:244)
	at C6.b.v(SourceFile:358)
	at C6.b.h(SourceFile:80)
	at j7.k.f(SourceFile:36)
	at j7.k.c(SourceFile:28)
	at C6.d.v(SourceFile:633)
	at C6.d.h(SourceFile:198)
	at j7.k.f(SourceFile:36)
	at j7.k.c(SourceFile:28)
	at j7.k.d(SourceFile:8)
	at C6.b.v(SourceFile:706)
	at C6.b.h(SourceFile:107)
	at j7.k.f(SourceFile:36)
	at j7.k.c(SourceFile:28)
	at j7.k.d(SourceFile:8)
	at C6.b.v(SourceFile:841)
	at C6.b.h(SourceFile:161)
	at j7.k.f(SourceFile:36)
	at j7.k.c(SourceFile:28)
	at j7.k.a(SourceFile:24)
	at j7.d.a(SourceFile:196)
	at D6.c.a(SourceFile:178)
	at Q9.b.v(SourceFile:240)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more

2024-11-08 17:26:20:971 DEBUG: F - CheckMonthlyPlaylist false
2024-11-08 17:26:40:331 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at a.a.s0(SourceFile:173)
	at b8.g.v(SourceFile:11)
	at H8.a.k(SourceFile:9)
	at h9.q.x(SourceFile:7)
	at b9.a.k(SourceFile:23)
	at H8.a.k(SourceFile:32)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more

**Comment by fast4x** [comment]
Error is source error, try to disconnect yt account and restart

**Comment by filipemanuelofs** [comment]
Disconnected and the songs finally started. Tried about 7-8 songs, all of them played.
