### ISSUE TITLE
It is completely impossible to use Ri Music

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4396]
### Version of RiMusic

0.6.59

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

It all starts when I want to play a song, out of nowhere it starts changing songs randomly. Bug. In addition to playing randomly, there is no sound and it stays in this infinite loop. Furthermore, when I click on something other than music, a song opens without any sound, an endless change of music.

As well as the theme I had chosen as color and everything, music layout and etc. 

### Submit a video

https://github.com/user-attachments/assets/20cae10a-7f26-4bd8-ad63-7bc5c14b0738

### What was your expectation?

Listen to music without interruption by the bug

### Logs (Optional)

2024-11-08 18:56:08:429 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-08 18:56:15:214 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 13967: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"199133"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 13967: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"199133"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 13967: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"199133"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:56:30:818 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16398: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"213320"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16398: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"213320"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16398: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"213320"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:56:38:732 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16328: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"210360"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16328: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"210360"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16328: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"210360"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:56:43:760 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17523: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"240000"},{"itag":278,"url":"https://rr1---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 17523: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"240000"},{"itag":278,"url":"https://rr1---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 17523: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"240000"},{"itag":278,"url":"https://rr1---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:56:49:553 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17512: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"274280"},{"itag":278,"url":"https://rr1---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 17512: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"274280"},{"itag":278,"url":"https://rr1---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 17512: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"274280"},{"itag":278,"url":"https://rr1---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:56:54:620 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17222: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"173760"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 17222: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"173760"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 17222: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"173760"},{"itag":278,"url":"https://rr4---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:56:59:774 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 14023: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"282999"},{"itag":278,"url":"https://rr3---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 14023: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"282999"},{"itag":278,"url":"https://rr3---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 14023: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"282999"},{"itag":278,"url":"https://rr3---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:57:04:690 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16373: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"227520"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16373: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"227520"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16373: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"227520"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-08 18:57:09:592 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17251: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"171400"},{"itag":278,"url":"https://rr2---sn-cg51p.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.j

**Comment by twistios** [comment]
This "Unexpected JSON token" bug I also had. It might be related to YTM login. Disable it. If it does not work without login, then currently there is no solution for that.

**Comment by PedroH654** [comment]
> Esse bug "Token JSON inesperado" eu também tive. Pode estar relacionado ao login do YTM. Desative-o. Se não funcionar sem login, atualmente não há solução para isso.

But, the devs will look for a solution soon to use the app with the YTM login, right? Because, with the login activated, I couldn't download the songs either.

**Comment by twistios** [comment]
I said that you should try if it works with login disabled.

**Comment by PedroH654** [comment]
> I said that you should try if it works with login disabled.

For me, I was able to use it with the login disabled, it went back to downloading the songs and playing them normally. 
But, out of curiosity, I reactivated the login while listening to music, cleared my queue and restarted the app, and I was able to use it with the login activated, not if it was a bug I ended up doing or if I can fix the bug on my deviceBut, out of curiosity, I reactivated the login while listening to music, cleared my queue and restarted the app, and I was able to use it with the login activated, not if it was a bug I ended up doing or if I can fix the bug on my device 😅🤣

**Comment by fast4x** [comment]
Fixed Ubyte error, I hope I have fixed the bug, available from version 0.6.60
