### ISSUE TITLE
Doesnt work at al

### ISSUE THREAD

**Issue by KABYb34** [fast4x/RiMusic#4397]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Crashes
3. Doesnt work at al
4. 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Open and play songs

**Comment by twistios** [comment]
If you are using YTM login, then disable it (currently there seems to be problems with beeing logged in). If it does not work without login, then there currently not really is a solution.

**Comment by Vishcot** [comment]
facing same issue. getting crashed on each song play

**Comment by Vishcot** [comment]
@fast4x 
https://github.com/user-attachments/assets/01bb19cb-9a0e-40a9-8460-33ebc4d620d9

**Comment by fast4x** [comment]
log please I'm not a magician

**Comment by KABYb34** [comment]
Where can I find the log?

**Comment by KABYb34** [comment]
2024-11-09T14:07:18.741:	java.lang.RuntimeException: Unable to start service it.fast4x.rimusic.service.modern.PlayerServiceModern@cd68177 with Intent { act=android.intent.action.MEDIA_BUTTON dat=W3.W0:/... cmp=it.fast4x.rimusic/.service.modern.PlayerServiceModern (has extras) }: java.lang.IllegalArgumentException: session is already released
	 android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286) 
	 android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
Caused by:	java.lang.IllegalArgumentException: session is already released
	 M2.c.c(SourceFile:10) 
	 androidx.media3.session.MediaSessionService.c(SourceFile:11) 
	 androidx.media3.session.MediaSessionService.onStartCommand(SourceFile:110) 
	 android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268) 
	 android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by fast4x** [comment]
Great thanks for log

**Comment by fast4x** [comment]
This error show when app start, or when use a Bluetooth device?

**Comment by KABYb34** [comment]
This is when I click on a song from yt not ytm

**Comment by fast4x** [comment]
you mean when share song from yt?

**Comment by Vishcot** [comment]
> you mean when share song from yt?

it means, just open app l, start any song..it will crash..anyway. the whole player screen..play another song again it will crash.

**Comment by GabubuAvailable** [comment]
Heyo! I'm also another "victim" on this lol. So yeah I found that it happens one I am logged in with my YouTube account. Every song I try to play I get the error and the player crashes. The fix for me is to disable the "YouTube Music login" option and deal with that. Some songs won't let you play since some artists are restricting users to login in order to play it.

Here's my log when I tried with option enabled then disabled and tried again:

`2024-11-11 21:01:17:497 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-11 21:01:30:682 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-11 21:01:31:670 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-11 21:01:43:733 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16666: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"169880"},{"itag":278,"url":"https://rr1---sn-vg5ob.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16666: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"169880"},{"itag":278,"url":"https://rr1---sn-vg5ob.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16666: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"169880"},{"itag":278,"url":"https://rr1---sn-vg5ob.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

`

Hope my words and this log helps you! :P

**Comment by fast4x** [comment]
Hello Victim, ahahaha tomorrow try new automatic custom version form release versions page.

**Comment by GabubuAvailable** [comment]
> Hello Victim, ahahaha tomorrow try new automatic custom version form release versions page.

Ahahah 😂
Gotcha. Thanks for reply man! 🙂

**Comment by GabubuAvailable** [comment]
I come back with an update. I tried the custom version now and looks like I am able to use it properly without any issue with my YT Music account. Good to know so I will mostly wait for the new release from Friday. Thanks again! :)
