### ISSUE TITLE
Theme is bugged

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4408]
### Version of RiMusic

0.6.59

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

The problem is in the theme. The player control is correct, now the songs and colors do not follow the "modern black" theme. In the music player, the color palettes also don't stay true to the "modern black" theme. 

I have a comparison of the versions, the old one (0.6.58.1) and the current one (0.6.59). I'll upload the first video of version 0.6.58.1 to compare with the current 0.6.59:

### Submit a video

Versão 0.6.58.1

https://github.com/user-attachments/assets/e707427b-ba35-48de-90e1-d03e955bacb8

Versão 0.6.59

https://github.com/user-attachments/assets/8a9c459e-1d7e-458d-8e2a-e28a092fd408

The bug changes the colors of the player and menu, as if I had changed the theme. 

### What was your expectation?

As for the colors of the main menu, the colors and palettes must faithfully follow the "modern black" option. 

### Logs (Optional)

2024-10-24 15:55:00:033 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:55:00:043 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:55:00:070 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:55:00:070 DEBUG: q - SongsMostPlayed null
2024-10-24 15:55:00:125 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:55:00:126 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:55:03:304 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:55:10:631 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:55:10:640 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:55:20:773 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

**Comment by fast4x** [comment]
Disconnect ytm account please

**Comment by bauldihr** [comment]
> Desconecte a conta ytm por favor

But, it's not because of the account. Whether it's connected or disconnected, the bug remains.

**Comment by fast4x** [comment]
disconnect, disable and restart

**Comment by fast4x** [comment]
Fixed, available from version 0.6.61
