### ISSUE TITLE
No puedo oir música en linea 

### ISSUE THREAD

**Issue by Pandoby01** [fast4x/RiMusic#4415]
### Version of RiMusic

0.6.59

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abrí la app
2. Busque una canción en línea que no he descargado 
3. La canción aparece pero no se reproduce 
4. El reproductor se cierra sin darme un mensaje de error 

https://github.com/user-attachments/assets/cf129240-e40f-43ba-8e68-661b82b99928

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Hice click en la canción por lo que espere que se reprodujera como lo haia antes 

### What more can you tell us? (Optional)

La pantalla se torna de un tono oscuro y el reproductor se cierra automático, lo intente con la app conectada y desconectada a Yt Music, sincronizado a Piped y sin sincronizacion, e incluso he reiniciado la app más de una vez 

### Logs (Optional)

2024-11-09 10:06:41:206 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-09 10:06:53:977 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16785: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"307400"},{"itag":278,"url":"https://rr1---sn-oxuu2.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16785: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"307400"},{"itag":278,"url":"https://rr1---sn-oxuu2.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16785: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"307400"},{"itag":278,"url":"https://rr1---sn-oxuu2.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-09 10:07:02:492 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16778: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"176720"},{"itag":278,"url":"https://rr2---sn-oxuu2.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16778: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"176720"},{"itag":278,"url":"https://rr2---sn-oxuu2.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16778: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"176720"},{"itag":278,"url":"https://rr2---sn-oxuu2.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

**Comment by Pandoby01** [comment]
Posdata: Gracias por su trabajo apesar del error estoy sumamente agradecido con las personas agregadas al proyecto

**Comment by fast4x** [comment]
Thanks to you, I hope I have fixed the bug. Fixed available from version 0.6.60

P.s. error occur with all songs?

**Comment by TitanBlood01** [comment]
In my case I recently update RiMusic and yes, The issue occur in all my songs except my downlodad songs, by the way I am sure that all the developers could fixed that, I love this app.

**Comment by Pandoby01** [comment]
Me pasa lo mismo
