### ISSUE TITLE
Problema de reproducción de inicio de sesión de YouTube 

### ISSUE THREAD

**Issue by Aetherimpact802** [fast4x/RiMusic#4420]
### Version of RiMusic

0.6.59

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Abre RiMusic
2. Inicio en Youtube 
3. Click en una música 
4. No reproduce ninguna música 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/f7fec8ec-2a7c-41d5-b102-07a62a5a7078

### What was your expectation?

Que se reprodusca la música 

### What more can you tell us? (Optional)

Por favor reparar este error en esta versión 

### Logs (Optional)

2024-11-09 11:48:31:424 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-09 11:48:47:683 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:201)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17591: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"120080"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 17591: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"120080"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 17591: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"120080"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-09 11:48:53:002 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:201)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17590: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"161320"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 17590: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"161320"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 17590: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"161320"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-09 11:48:57:802 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:201)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 17518: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"178845"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 17518: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"178845"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 17518: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"178845"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-09 11:49:03:251 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:201)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 14075: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"166499"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 14075: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"166499"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 14075: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[9].itag
JSON input: .....ationMs":"166499"},{"itag":278,"url":"https://rr1---sn-uxajv.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
