### ISSUE TITLE
No songs play. 

### ISSUE THREAD

**Issue by Xyxhxx** [fast4x/RiMusic#4432]
### Version of RiMusic

0.6.59

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Choose any song
3. Boom! Crash happens

For reason after the update whenever I choose a song it opens the play like it's going to load and start playing but instead the player crashes/disappears. There's no error toast message the pops up. 

It happens on every song. 

I didn't check downloaded songs as I have no songs downloaded to test it on.

I'm using a pixel 9 on the latest stable release of graphene OS 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

That the song would play as it always has in previous versions of the app.

### Logs (Optional)

2024-11-09 18:42:15:374 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-09 18:42:29:319 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16536: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"205760"},{"itag":278,"url":"https://rr5---sn-a5mek.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16536: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"205760"},{"itag":278,"url":"https://rr5---sn-a5mek.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16536: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"205760"},{"itag":278,"url":"https://rr5---sn-a5mek.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

2024-11-09 18:43:00:350 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.Q.j(SourceFile:17)
	at T2.Q.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: java.io.IOException: b7.f: Illegal input: Unexpected JSON token at offset 16542: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"205760"},{"itag":278,"url":"https://rr2---sn-a5mse.....
	at G5.k.j(SourceFile:68)
	at P2.E.b(SourceFile:3)
	at P2.F.b(SourceFile:10)
	at f3.M.c(SourceFile:26)
	at j3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: b7.f: Illegal input: Unexpected JSON token at offset 16542: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"205760"},{"itag":278,"url":"https://rr2---sn-a5mse.....
	at c7.j.a(SourceFile:261)
	at c7.c.v(SourceFile:13)
	at H8.a.k(SourceFile:9)
	at b9.N.run(SourceFile:107)
	at b9.Z.B0(SourceFile:76)
	at b9.G.D(SourceFile:105)
	at G5.k.j(SourceFile:43)
	... 7 more
Caused by: z9.l: Unexpected JSON token at offset 16542: Failed to parse type 'UByte' for input '278' at path: $.streamingData.adaptiveFormats[11].itag
JSON input: .....ationMs":"205760"},{"itag":278,"url":"https://rr2---sn-a5mse.....
	at z9.q.d(SourceFile:37)
	at z9.q.e(SourceFile:35)
	at n3.i.q(SourceFile:61)
	at n3.i.r(SourceFile:13)
	at z9.k.w(SourceFile:60)
	at x9.s0.c(SourceFile:12)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.l4.c(SourceFile:62)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at x9.r.j(SourceFile:8)
	at x9.a.i(SourceFile:35)
	at x9.a.c(SourceFile:6)
	at z9.A.j(SourceFile:285)
	at d8.V1.l(SourceFile:11)
	at z9.A.l(SourceFile:52)
	at v7.k4.c(SourceFile:56)
	at z9.A.j(SourceFile:285)
	at d8.V1.p(SourceFile:30)
	at v7.Z3.c(SourceFile:60)
	at z9.A.j(SourceFile:285)
	at y9.d.a(SourceFile:30)
	at c7.j.a(SourceFile:207)
	... 13 more

**Comment by fast4x** [comment]
This is fixed and available in next version
