### ISSUE TITLE
"Some songs don't play" problem persists

### ISSUE THREAD

**Issue by qpzmc** [fast4x/RiMusic#4545]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Some songs still don't play (no YTM login)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/8dfa55d7-f0ec-4587-9bb7-26155154d58b

### What was your expectation?

The song playing

### What more can you tell us? (Optional)

I'm very sorry for opening the same ticket again, but the new version still didn't fix it 😞😞😞 Thank you very much once again for your time and patience on Rimusic, please don't overwork yourselves ❤️❤️❤️

### Logs (Optional)

2024-11-15 21:21:21:050 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-15 21:21:29:005 ERROR: PlayerServiceModern - PlayerService onPlayerError T2.m: Source error
	at T2.P.j(SourceFile:17)
	at T2.P.handleMessage(SourceFile:353)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: P2.x: java.io.IOException: java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to rr1---sn-45nuoxu-bg0l.googlevideo.com/127.1.1.1:443
	at R2.a.a(SourceFile:432)
	at P2.o.a(SourceFile:312)
	at P2.G.a(SourceFile:3)
	at Q2.g.c(SourceFile:278)
	at Q2.g.a(SourceFile:168)
	at Q2.g.c(SourceFile:278)
	at Q2.g.a(SourceFile:168)
	at P2.E.a(SourceFile:164)
	at P2.F.a(SourceFile:10)
	at f3.M.b(SourceFile:26)
	at j3.i.run(SourceFile:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to rr1---sn-45nuoxu-bg0l.googlevideo.com/127.1.1.1:443
	at R2.a.a(SourceFile:419)
	... 13 more
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to rr1---sn-45nuoxu-bg0l.googlevideo.com/127.1.1.1:443
	at N5.o.g(SourceFile:21)
	at N5.o.get(SourceFile:103)
	at R2.a.a(SourceFile:252)
	... 13 more
Caused by: java.net.ConnectException: Failed to connect to rr1---sn-45nuoxu-bg0l.googlevideo.com/127.1.1.1:443
	at ea.j.e(SourceFile:136)
	at ea.j.c(SourceFile:136)
	at ea.d.d(SourceFile:324)
	at ea.a.a(SourceFile:60)
	at E.B.f(SourceFile:128)
	at ca.b.a(SourceFile:155)
	at E.B.f(SourceFile:128)
	at fa.a.a(SourceFile:585)
	at E.B.f(SourceFile:128)
	at fa.a.a(SourceFile:153)
	at E.B.f(SourceFile:128)
	at ea.h.g(SourceFile:97)
	at ea.e.run(SourceFile:42)
	... 3 more
Caused by: java.net.ConnectException: failed to connect to rr1---sn-45nuoxu-bg0l.googlevideo.com/127.1.1.1 (port 443) from /127.0.0.1 (port 59260) after 16000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:347)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at ia.n.e(SourceFile:6)
	at ea.j.e(SourceFile:71)
	... 15 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:334)
	... 25 more

**Comment by twistios** [comment]
I don't know the exact version you where playing, but I found one that is the same song: https://m.youtube.com/watch?v=e7RXSVAhlng
It is the same artist and song name, but for me, the name shows including (japanese? not sure) symboles in addition to the romanization. The artist name is "KikuoHana (Kituo to Hanatan)" so also the artist name is different for me.

Please do these things:

1. Update the song. For this, use the song menu.
2. Try if the song (via my link, use search by link) plays

**Comment by qpzmc** [comment]
> I don't know the exact version you where playing, but I found one that is the same song: https://m.youtube.com/watch?v=e7RXSVAhlng It is the same artist and song name, but for me, the name shows including (japanese? not sure) symboles in addition to the romanization. The artist name is "KikuoHana (Kituo to Hanatan)" so also the artist name is different for me.
> 
> Please do these things:
> 
>     1. Update the song. For this, use the song menu. Also please send the song link (you can get it via "Listen on" button in the song menu).
> 
>     2. Try if the song (via my link, use search by link) plays

hello, I updated some of the songs that had this problem but it continued, some of them:
https://music.youtube.com/watch?v=S87Fk_N8H3w

https://music.youtube.com/watch?v=9CfgJjEYL2E

https://music.youtube.com/watch?v=t84D5lx_YVs

https://music.youtube.com/watch?v=Kn_f1D9U7HA

https://music.youtube.com/watch?v=dEfl-ObuapA

https://music.youtube.com/watch?v=DEBHeQ_L9xM


also the link you sent was from another song from the same album 😭😭😭 but thank you very much for going out of your way to search it

**Comment by twistios** [comment]
All these songs (links) you have send, work for me. Are you using YTM login or not?

**Comment by qpzmc** [comment]
> All these songs (links) you have send, work for me. Are you using YTM login or not?

I'm not, I have no idea why it's not working 😞😞😞 I already uninstalled the old version before installing this one

**Comment by qpzmc** [comment]
> All these songs (links) you have send, work for me. Are you using YTM login or not?

I went to check it out once more and suddenly it started working...? I'm very sorry for the inconvenience I caused, thank you very much for your time and comprehension
![Screenshot_20241116_011906](https://github.com/user-attachments/assets/6377cf36-8848-4507-b1df-f4eb3155fb15)
