### ISSUE TITLE
After toggling Android Auto on and off, the cache settings are cleared and the player won't launch

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4625]
### Version of RiMusic

0.6.61

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2.  Open the Android Auto option
3. Then close the Android Auto option. An bug occurred
4. Cleared cache settings in misc section. Also, if you want to play songs, the player does not open

**This problem is not fixed without uninstalling and reinstalling the app**

### Submit a video

https://github.com/user-attachments/assets/6ae1e4bd-16d2-419b-b858-85f3c73675fc

### What was your expectation?

Android Auto on/off should not prevent the player from opening and the player should open. Don't delete cache settings

### What more can you tell us? (Optional)

No error. Just a bug

### Logs (Optional)

2024-11-24 09:29:57:053 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-24 09:29:57:340 ERROR: f - RememberPreference RelatedPage Error: E9.o: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'n' instead at path: $
JSON input: null
	at E9.v.d(SourceFile:35)
	at E9.v.e(SourceFile:35)
	at E9.a.q(SourceFile:61)
	at E9.a.r(SourceFile:13)
	at E9.a.s(SourceFile:73)
	at E9.a.H(SourceFile:48)
	at E9.K.h(SourceFile:43)
	at E9.H.d(SourceFile:65)
	at Z7.v.a(SourceFile:5)
	at E9.H.p(SourceFile:283)
	at D9.d.a(SourceFile:30)
	at e7.f.e(SourceFile:386)
	at j8.b.l(SourceFile:1127)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at X.C.a(SourceFile:231)
	at h0.j.a(SourceFile:150)
	at j8.c.n(SourceFile:324)
	at f0.h.h(SourceFile:46)
	at f0.h.n(SourceFile:9)
	at K.n0.j(SourceFile:155)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1400)
	at v.e.l(SourceFile:279)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at d8.e0.b(SourceFile:914)
	at d8.e0.a(SourceFile:227)
	at H9.d.j(SourceFile:891)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at C.w.l(SourceFile:654)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at C.w.l(SourceFile:797)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at f0.u.a(SourceFile:15)
	at X.m.n(SourceFile:80)
	at X.w.m(SourceFile:35)
	at X.T0.a(SourceFile:25)
	at X.m$b.a(SourceFile:5)
	at X.m$b.a(SourceFile:5)
	at X.w.n(SourceFile:12)
	at H0.F.i(SourceFile:28)
	at H0.F.h(SourceFile:116)
	at H0.A.j0(SourceFile:160)
	at U.v1.l(SourceFile:526)
	at H0.C.a(SourceFile:72)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at J0.t.a(SourceFile:38)
	at r0.Y.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.t.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.y.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.t.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.y.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at C.w.l(SourceFile:1193)
	at H0.C.a(SourceFile:72)
	at J0.t.a(SourceFile:38)
	at C.H.h(SourceFile:99)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at H0.b0.a(SourceFile:39)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:114)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.E.M(SourceFile:17)
	at J0.T.c(SourceFile:3)
	at J0.T.o(SourceFile:23)
	at J0.T.l(SourceFile:65)
	at K0.u.onMeasure(SourceFile:123)
	at android.view.View.measure(View.java:27129)
	at K0.a.h(SourceFile:64)
	at K0.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4536)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3533)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62
