### ISSUE TITLE
Bug when switching music via notifications 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4645]
### Version of RiMusic

0.6.61

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

The bug happens when I change music through cell phone notifications. When I change music, the music I had already changed returns. Example:

Music X

Music Y

Music X

Instead of going to Z, it goes back to X (illustrating example)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

That when changing music, I don't return to the one I already heard. 

### Logs (Optional)

2024-10-24 15:55:00:033 DEBUG: q - CheckMonthlyPlaylist false
2024-10-24 15:55:00:043 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:55:00:070 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:55:00:070 DEBUG: q - SongsMostPlayed null
2024-10-24 15:55:00:125 DEBUG: q - CheckMonthlyPlaylist true
2024-10-24 15:55:00:126 DEBUG: q - SongsMostPlayed 0
2024-10-24 15:55:03:304 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:55:10:631 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-10-24 15:55:10:640 ERROR: n - Playback error: java.lang.NullPointerException: uriString
2024-10-24 15:55:20:773 ERROR: PlayerService - PlayerService onPlayerError P2.m: Source error
	at P2.O.j(SourceFile:17)
	at P2.O.handleMessage(SourceFile:386)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException: uriString
	at C5.m.k(SourceFile:48)
	at L2.E.b(SourceFile:3)
	at L2.F.b(SourceFile:10)
	at b3.M.d(SourceFile:26)
	at f3.i.run(SourceFile:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:504)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:466)
	at T3.i.t(SourceFile:198)
	at V7.d.r(SourceFile:11)
	at B8.a.g(SourceFile:9)
	at V8.N.run(SourceFile:107)
	at V8.Z.A0(SourceFile:76)
	at V8.G.C(SourceFile:105)
	at C5.m.k(SourceFile:23)
	... 7 more

2024-11-24 23:54:01:688 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-24 23:54:02:522 DEBUG: c - CheckMonthlyPlaylist false
2024-11-24 23:54:02:760 DEBUG: c - CheckMonthlyPlaylist false
2024-11-24 23:54:03:142 DEBUG: c - CheckMonthlyPlaylist true
2024-11-24 23:54:03:143 DEBUG: c - SongsMostPlayed null
2024-11-24 23:54:03:246 DEBUG: c - CheckMonthlyPlaylist true
2024-11-24 23:54:03:246 DEBUG: c - SongsMostPlayed 0
2024-11-24 23:54:37:785 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 67 newPosition 67 reason 1
2024-11-24 23:55:33:512 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 67 newPosition 67 reason 1
2024-11-24 23:55:45:526 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 67 newPosition 67 reason 1
2024-11-24 23:56:05:059 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 67 newPosition 67 reason 1
2024-11-24 23:56:50:719 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 67 newPosition 55 reason 4
2024-11-25 00:01:27:823 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 55 newPosition 56 reason 0
2024-11-25 00:03:54:916 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 56 newPosition 57 reason 1
2024-11-25 00:03:55:033 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 57 newPosition 57 reason 2
2024-11-25 00:06:59:244 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 57 newPosition 58 reason 0
2024-11-25 00:08:25:512 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 58 newPosition 0 reason 4
2024-11-25 11:58:01:870 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-25 11:58:02:737 DEBUG: c - CheckMonthlyPlaylist false
2024-11-25 11:58:02:970 DEBUG: c - CheckMonthlyPlaylist false
2024-11-25 11:58:03:300 DEBUG: c - CheckMonthlyPlaylist true
2024-11-25 11:58:03:301 DEBUG: c - SongsMostPlayed null
2024-11-25 11:58:03:398 DEBUG: c - CheckMonthlyPlaylist true
2024-11-25 11:58:03:398 DEBUG: c - SongsMostPlayed 0
2024-11-25 19:31:58:703 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-25 19:31:59:587 DEBUG: c - CheckMonthlyPlaylist false
2024-11-25 19:31:59:837 DEBUG: c - CheckMonthlyPlaylist false
2024-11-25 19:32:00:164 DEBUG: c - CheckMonthlyPlaylist true
2024-11-25 19:32:00:165 DEBUG: c - SongsMostPlayed null
2024-11-25 19:32:00:260 DEBUG: c - CheckMonthlyPlaylist true
2024-11-25 19:32:00:261 DEBUG: c - SongsMostPlayed 0

**Comment by twistios** [comment]
Duplicate/same as #4624.

**Comment by aneesh1122** [comment]
use essential player
