### ISSUE TITLE
Player closes every time a song is paused 

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#4679]
Whenever a song is paused, the player disappears. Tappint the screen does nothing, and one can only interact with the applifation after pressing the back button in the android navigation menu.
The song also disappears; the player can't be brought back

**Comment by fast4x** [comment]
I think your version is too old, update

**Comment by privacyfreak84** [comment]
Happening on 0.6.61

**Comment by fast4x** [comment]
much strange

**Comment by privacyfreak84** [comment]
Has been happening since at least 2-3 versions ago

**Comment by privacyfreak84** [comment]
Will logs help?

**Comment by fast4x** [comment]
yep send log if possible please

**Comment by privacyfreak84** [comment]
OK

**Comment by privacyfreak84** [comment]
After updating to 0.6.62, the player doesn't close when the song is paused, but the song can't be restarted with the play /pause button (pressing it does nothing)

**Comment by privacyfreak84** [comment]
Logs:
```
2024-11-30 09:57:06:062 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-30 09:57:06:526 ERROR: f - RememberPreference ChartsPage Error: E9.o: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'n' instead at path: $
JSON input: null
	at E9.v.d(SourceFile:35)
	at E9.v.e(SourceFile:35)
	at E9.a.q(SourceFile:61)
	at E9.a.r(SourceFile:13)
	at E9.a.s(SourceFile:73)
	at E9.a.H(SourceFile:48)
	at E9.K.h(SourceFile:43)
	at E9.H.d(SourceFile:65)
	at u7.h.a(SourceFile:3)
	at E9.H.p(SourceFile:283)
	at D9.d.a(SourceFile:30)
	at e7.f.e(SourceFile:776)
	at j8.b.l(SourceFile:1127)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at X.C.a(SourceFile:231)
	at h0.j.a(SourceFile:150)
	at j8.c.n(SourceFile:324)
	at f0.h.h(SourceFile:46)
	at f0.h.n(SourceFile:9)
	at K.n0.j(SourceFile:155)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1400)
	at v.e.l(SourceFile:279)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at d8.e0.b(SourceFile:914)
	at d8.e0.a(SourceFile:227)
	at H9.d.j(SourceFile:891)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at C.w.l(SourceFile:654)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at C.w.l(SourceFile:797)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at f0.u.a(SourceFile:15)
	at X.m.n(SourceFile:80)
	at X.w.m(SourceFile:35)
	at X.T0.a(SourceFile:25)
	at X.m$b.a(SourceFile:5)
	at X.m$b.a(SourceFile:5)
	at X.w.n(SourceFile:12)
	at H0.F.i(SourceFile:28)
	at H0.F.h(SourceFile:116)
	at H0.A.j0(SourceFile:160)
	at U.v1.l(SourceFile:526)
	at H0.C.a(SourceFile:72)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at J0.t.a(SourceFile:38)
	at r0.Y.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.t.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.y.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.t.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.y.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at C.w.l(SourceFile:1193)
	at H0.C.a(SourceFile:72)
	at J0.t.a(SourceFile:38)
	at C.H.h(SourceFile:99)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at H0.b0.a(SourceFile:39)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:114)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.E.M(SourceFile:17)
	at J0.T.c(SourceFile:3)
	at J0.T.o(SourceFile:23)
	at J0.T.l(SourceFile:65)
	at K0.u.onMeasure(SourceFile:123)
	at android.view.View.measure(View.java:27131)
	at K0.a.h(SourceFile:64)
	at K0.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1175)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4187)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2936)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-11-30 09:57:06:925 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:57:07:251 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 4
2024-11-30 09:58:19:568 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-30 09:58:19:859 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:58:21:299 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 4
2024-11-30 09:58:40:125 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-30 09:58:46:095 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:58:49:518 DEBUG: d0 - Success loadData in QuickPicsModern
2024-11-30 09:58:56:326 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 4
2024-11-30 09:58:56:573 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:58:56:608 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:58:58:213 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:58:58:299 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:59:02:179 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:59:08:060 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 4
2024-11-30 09:59:08:988 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:59:10:638 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:59:14:813 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:59:17:142 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-30 09:59:20:314 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
```

**Comment by privacyfreak84** [comment]
Why is the issue closed?

**Comment by fast4x** [comment]
Unfortunately isn't reproducible

**Comment by privacyfreak84** [comment]
So is it impossible to solve the issue? Listening to songs is now very cumbersome, as to continue listening to a song after pausing it, you must replay the song from the beginning
