### ISSUE TITLE
RiMusic crashes on Android Auto

### ISSUE THREAD

**Issue by Mickael81** [fast4x/RiMusic#4680]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Hello,
I have version 0.6.61 on my device.
Since the last update, I noticed that I could no longer listen to songs on Android Auto. (Android Auto is activated on RiMusic)
However, the application works perfectly on my smartphone.
I tried clearing the application cache but, unfortunately, this does not solve the problem.
Could you fix this bug?
Thanks a lot 

### What was your expectation?

I hope I can listen to music via Android Auto again.

### What more can you tell us? (Optional)

I did not uninstall and reinstall the application because I fear losing all my data (albums, artists and favorite playlists)

**Comment by twistios** [comment]
Please provide crash logs. Since you are on 0.6.61, you can try if it works to copy the crash log via the app context menu: Hold the app icon on the android launcher to show the context options: Select "Copy Crashlog in Clipboard" (or similar) and paste it here.

**Comment by Mickael81** [comment]
Thanks for your feedback.
I did what you told me but RiMusic tells me that there is no crash.
I looked in my vehicle but this feature is not available on Android Auto.
So unfortunately I can't provide you with a crash log.
The only songs that remain playable on Android Auto are the ones that are cached on the app, almost as if I had downloaded them.

https://github.com/user-attachments/assets/e81e3b9c-4b35-436e-a5fc-ee135bc1aed5

![20241128_214148](https://github.com/user-attachments/assets/bbb7d17a-3044-4ddd-aeac-cc87095f9af9)

**Comment by twistios** [comment]
"Song not loading" is not a crash so it makes sense that crash log does not have an entry for this. This is something that can be possibly found in the debug log.

**Comment by fast4x** [comment]
Also login to ytm from miscellaneous settings

**Comment by LeandroPelegrini** [comment]
Try to unlock your phone and play the music. That worked for me... But, that's a big, need to work with phone locked...

**Comment by Mickael81** [comment]
I see that you have closed the topic but it is clear that the problem is absolutely not solved!
If the application works perfectly on my smartphone, there are however failures on Android Auto where listening to music is totally impossible.
This feature may not be a priority but I nevertheless preferred to report it to you.
I hope that a solution will be found fairly quickly. Kind regards

**Comment by fast4x** [comment]
send crash log please

**Comment by Mickael81** [comment]
2024-12-02 13:14:35:956 ERROR: i - Playback error: java.lang.NullPointerException
2024-12-02 13:14:40:286 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-12-02 13:41:14:441 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-12-02 13:41:28:102 DEBUG: a - BitmapProvider load method being called
2024-12-02 13:41:31:441 ERROR: PlayerServiceModern - PlayerService onPlayerError S2.n: Source error
	at S2.O.k(SourceFile:17)
	at S2.O.handleMessage(SourceFile:339)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.IOException: java.lang.NullPointerException
	at O2.D.h(SourceFile:72)
	at O2.E.h(SourceFile:10)
	at e3.O.b(SourceFile:26)
	at i3.j.run(SourceFile:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException
	at l8.K.a(SourceFile:127)
	at u7.T.e(SourceFile:21)
	at d8.B.V(SourceFile:177)
	at z7.b.i0(SourceFile:87)
	at z7.b.L(SourceFile:211)
	at c8.a.t(SourceFile:50)
	at I8.a.k(SourceFile:9)
	at d9.L.run(SourceFile:107)
	at d9.X.v0(SourceFile:76)
	at d9.E.E(SourceFile:105)
	at O2.D.h(SourceFile:47)
	... 6 more

2024-12-02 13:42:46:556 ERROR: i - Playback error: java.lang.NullPointerException
2024-12-02 13:42:46:736 ERROR: i - Playback error: java.lang.NullPointerException
2024-12-02 13:42:51:603 ERROR: i - Playback error: java.lang.NullPointerException
2024-12-02 13:42:59:790 ERROR: i - Playback error: java.lang.NullPointerException

**Comment by fast4x** [comment]
This is not a crash log bit debug log, copy crash log please
