### ISSUE TITLE
"start radio" and "remove queue" button gave errors for a song that is not cached (Close network)

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4841]
### Version of RiMusic

0.6.63.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Turn off the network
3. Play a non-cache song from the Songs section
4. **Press "start radio" from the 3-dot selection or "delete" button to delete the queue**
5. **Boom! Crash happens**

### Submit a video

1. **Queue cleanup error for uncacheable song**

https://github.com/user-attachments/assets/2149adb0-bd53-4816-b3e9-f12763d55d6d

2. The "start radio" button gives an error for a song that is not cached

https://github.com/user-attachments/assets/0a04528d-0288-48ff-88e0-7ee34a7e7499

### What was your expectation?

Fix (start radio button and delete button) error

### What more can you tell us? (Optional)

1. **Queue cleanup error for uncacheable song**

2024-12-08T04:31:24.865:	java.lang.IndexOutOfBoundsException
	 L2.c.f(SourceFile:8) 
	 e3.d0.n(SourceFile:6) 
	 e3.r.n(SourceFile:3) 
	 e3.T.n(SourceFile:1) 
	 e3.v.n(SourceFile:3) 
	 e3.r.n(SourceFile:3) 
	 S2.k0.n(SourceFile:6) 
	 S2.l0.n(SourceFile:21) 
	 B2.b.h1(SourceFile:14) 
	 d8.t.r(SourceFile:1407) 
	 q8.i0.l(SourceFile:60) 
	 X.m.J(SourceFile:579) 
	 X.m.R(SourceFile:137) 
	 X.m.n(SourceFile:119) 
	 X.m.H(SourceFile:31) 
	 X.w.y(SourceFile:20) 
	 X.T0.t(SourceFile:93) 
	 X.d1.a(SourceFile:529) 
	 K0.b0.doFrame(SourceFile:7) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2. **The "start radio" button gives an error for a song that is not cached**

2024-12-08T04:33:04.377:	java.lang.IndexOutOfBoundsException
	 L2.c.f(SourceFile:8) 
	 e3.d0.n(SourceFile:6) 
	 e3.r.n(SourceFile:3) 
	 e3.T.n(SourceFile:1) 
	 e3.v.n(SourceFile:3) 
	 S2.l0.n(SourceFile:21) 
	 B2.b.h1(SourceFile:14) 
	 d8.t.r(SourceFile:1407) 
	 G7.e0.l(SourceFile:80) 
	 f0.h.e(SourceFile:46) 
	 f0.h.l(SourceFile:9) 
	 G7.f0.j(SourceFile:792) 
	 f0.h.g(SourceFile:46) 
	 f0.d.l(SourceFile:20) 
	 X.m.J(SourceFile:579) 
	 X.m.R(SourceFile:137) 
	 X.m.n(SourceFile:119) 
	 X.m.H(SourceFile:31) 
	 X.w.y(SourceFile:20) 
	 X.T0.t(SourceFile:93) 
	 X.d1.a(SourceFile:529) 
	 K0.b0.doFrame(SourceFile:7) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

### Logs (Optional)

No

**Comment by sajkbflksadbfkasdjf** [comment]
+1, but for me the network may remain active.
Exception: 
```
    type: crash
    osVersion: google/husky/husky:15/<redacted>
    flags: dev options enabled
    package: it.fast4x.rimusic:74, targetSdk 35
    process: it.fast4x.rimusic
    processUptime: 582403 + 375 ms
    installer: dev.imranr.obtainium.fdroid

    java.lang.IndexOutOfBoundsException
    	at L2.c.f(SourceFile:8)
    	at e3.d0.n(SourceFile:6)
    	at e3.v.n(SourceFile:3)
    	at S2.l0.n(SourceFile:21)
    	at B2.b.h1(SourceFile:14)
    	at d8.t.r(SourceFile:1407)
    	at G7.e0.l(SourceFile:80)
    	at f0.h.e(SourceFile:46)
    	at f0.h.l(SourceFile:9)
    	at G7.f0.j(SourceFile:792)
    	at f0.h.g(SourceFile:46)
    	at f0.d.l(SourceFile:20)
    	at X.m.J(SourceFile:579)
    	at X.m.R(SourceFile:137)
    	at X.m.n(SourceFile:119)
    	at X.m.H(SourceFile:31)
    	at X.w.y(SourceFile:20)
    	at X.T0.t(SourceFile:93)
    	at X.d1.a(SourceFile:529)
    	at K0.b0.doFrame(SourceFile:7)
    	at K0.Z.doFrame(SourceFile:48)
    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
    	at android.view.Choreographer.doFrame(Choreographer.java:941)
    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
    	at android.os.Handler.handleCallback(Handler.java:959)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loopOnce(Looper.java:232)
    	at android.os.Looper.loop(Looper.java:317)
    	at android.app.ActivityThread.main(ActivityThread.java:8744)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
    	Suppressed: j9.e: [X.D0@38f86e3, K0.z0@5c7c8e0, v0{Cancelling}@284f799, a0@f643a5e]
```
Logs:
```
--------- switch to crash
12-08 15:25:59.930  9863  9863 E AndroidRuntime: FATAL EXCEPTION: main
12-08 15:25:59.930  9863  9863 E AndroidRuntime: Process: it.fast4x.rimusic, PID: 9863
12-08 15:25:59.930  9863  9863 E AndroidRuntime: java.lang.IndexOutOfBoundsException
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at L2.c.f(SourceFile:8)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at e3.d0.n(SourceFile:6)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at e3.v.n(SourceFile:3)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at S2.l0.n(SourceFile:21)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at B2.b.h1(SourceFile:14)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at d8.t.r(SourceFile:1407)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at G7.e0.l(SourceFile:80)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at f0.h.e(SourceFile:46)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at f0.h.l(SourceFile:9)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at G7.f0.j(SourceFile:792)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at f0.h.g(SourceFile:46)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at f0.d.l(SourceFile:20)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.m.J(SourceFile:579)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.m.R(SourceFile:137)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.m.n(SourceFile:119)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.m.H(SourceFile:31)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.w.y(SourceFile:20)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.T0.t(SourceFile:93)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at X.d1.a(SourceFile:529)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at K0.b0.doFrame(SourceFile:7)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at K0.Z.doFrame(SourceFile:48)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:941)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8744)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
12-08 15:25:59.930  9863  9863 E AndroidRuntime: 	Suppressed: j9.e: [X.D0@38f86e3, K0.z0@5c7c8e0, v0{Cancelling}@284f799, a0@f643a5e]
--------- switch to main
12-08 15:26:06.053 12443 12443 E .fast4x.rimusic: Not starting debugger since process cannot load the jdwp agent.
12-08 15:26:06.174 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.167 12443 12443 W app_process64: type=1400 audit(0.0:8044): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.206 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.206 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.199 12443 12443 W app_process64: type=1400 audit(0.0:8045): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.203 12443 12443 W app_process64: type=1400 audit(0.0:8046): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.208 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.203 12443 12443 W .fast4x.rimusic: type=1400 audit(0.0:8047): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.218 12443 12443 W libc    : Access denied finding property "odsign.verification.success"
12-08 15:26:06.211 12443 12443 W .fast4x.rimusic: type=1400 audit(0.0:8048): avc:  denied  { read } for  name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=286 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.215 12443 12443 W .fast4x.rimusic: type=1400 audit(0.0:8049): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.218 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.220 12443 12443 E cutils-trace: Error opening trace file: No such file or directory (2)
12-08 15:26:06.219 12443 12443 W .fast4x.rimusic: type=1400 audit(0.0:8050): avc:  denied  { getattr } for  path="/apex/apex-info-list.xml" dev="tmpfs" ino=91 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:apex_info_file:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.224 12443 12443 W it.fast4x.rimusic: ART APEX data files are untrusted.
12-08 15:26:06.420 12443 12443 W libc    : Access denied finding property "ro.product.name_for_attestation"
12-08 15:26:06.420 12443 12443 W libc    : Access denied finding property "ro.product.device_for_attestation"
12-08 15:26:06.415 12443 12443 W main    : type=1400 audit(0.0:8051): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=110 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.420 12443 12443 W libc    : Access denied finding property "ro.product.manufacturer_for_attestation"
12-08 15:26:06.415 12443 12443 W main    : type=1400 audit(0.0:8052): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=110 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.420 12443 12443 W libc    : Access denied finding property "ro.product.brand_for_attestation"
12-08 15:26:06.421 12443 12443 W libc    : Access denied finding property "ro.product.model_for_attestation"
12-08 15:26:06.415 12443 12443 W main    : type=1400 audit(0.0:8053): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=110 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.415 12443 12443 W main    : type=1400 audit(0.0:8054): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=110 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.415 12443 12443 W main    : type=1400 audit(0.0:8055): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=110 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.422 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.415 12443 12443 W main    : type=1400 audit(0.0:8056): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.462 12443 12443 E it.fast4x.rimusic: Unable to find pattern file or unable to map it for am
12-08 15:26:06.487 12443 12443 W binder:12443_2: type=1400 audit(0.0:8057): avc:  denied  { read } for  name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=309 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.491 12443 12443 W binder:12443_2: type=1400 audit(0.0:8058): avc:  denied  { read } for  name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=309 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.494 12443 12461 W libc    : Access denied finding property "qemu.sf.lcd_density"
12-08 15:26:06.494 12443 12461 W libc    : Access denied finding property "qemu.sf.lcd_density"
12-08 15:26:06.658 12443 12443 W libc    : Access denied finding property "ro.debuggable"
12-08 15:26:06.651 12443 12443 W .fast4x.rimusic: type=1400 audit(0.0:8059): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
12-08 15:26:06.901 12443 12480 W System.err: SLF4J(W): No SLF4J providers were found.
12-08 15:26:06.901 12443 12480 W System.err: SLF4J(W): Defaulting to no-operation (NOP) logger implementation
12-08 15:26:06.901 12443 12480 W System.err: SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
12-08 15:26:07.301 12443 12493 W it.fast4x.rimusic: AIBinder_linkToDeath is being called with a non-null cookie and no onUnlink callback set. This might not be intended. AIBinder_DeathRecipient_setOnUnlinked should be called first.
12-08 15:26:57.482 12443 12443 E PersistMap: Tried to reference uninitialized PersistMap, stacktrace:
12-08 15:26:57.482 12443 12443 W System.err: java.lang.IllegalStateException: Stack:
12-08 15:26:57.482 12443 12443 W System.err: 	at q8.o0.b(SourceFile:594)
12-08 15:26:57.482 12443 12443 W System.err: 	at C8.q.getValue(SourceFile:21)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.i0.a(SourceFile:3)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.E.a(SourceFile:18)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.m.k(SourceFile:5)
12-08 15:26:57.482 12443 12443 W System.err: 	at d8.i.o(SourceFile:57)
12-08 15:26:57.482 12443 12443 W System.err: 	at d8.O.h(SourceFile:222)
12-08 15:26:57.482 12443 12443 W System.err: 	at g8.c.n(SourceFile:32)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.h(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.n(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at C.w.l(SourceFile:435)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.C.a(SourceFile:231)
12-08 15:26:57.482 12443 12443 W System.err: 	at h0.j.a(SourceFile:150)
12-08 15:26:57.482 12443 12443 W System.err: 	at Ka.h.i(SourceFile:214)
12-08 15:26:57.482 12443 12443 W System.err: 	at C.w.l(SourceFile:477)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.C.b(SourceFile:152)
12-08 15:26:57.482 12443 12443 W System.err: 	at Ka.h.g(SourceFile:120)
12-08 15:26:57.482 12443 12443 W System.err: 	at Z3.y.n(SourceFile:254)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.h(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.n(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at K.n0.j(SourceFile:155)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.g(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.j(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at androidx.compose.animation.a.a(SourceFile:1444)
12-08 15:26:57.482 12443 12443 W System.err: 	at v.e.l(SourceFile:279)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at d4.Z.c(SourceFile:914)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.support.v4.media.a.c(SourceFile:2282)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.support.v4.media.a.d(SourceFile:338)
12-08 15:26:57.482 12443 12443 W System.err: 	at d8.B.a(SourceFile:365)
12-08 15:26:57.482 12443 12443 W System.err: 	at G7.i0.l(SourceFile:1938)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.C.b(SourceFile:152)
12-08 15:26:57.482 12443 12443 W System.err: 	at G7.j0.j(SourceFile:509)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.g(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.j(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at e8.z.l(SourceFile:93)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.C.a(SourceFile:231)
12-08 15:26:57.482 12443 12443 W System.err: 	at h0.j.a(SourceFile:150)
12-08 15:26:57.482 12443 12443 W System.err: 	at e8.A.n(SourceFile:48)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.h(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.n(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at K.n0.j(SourceFile:155)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.g(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.j(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at androidx.compose.animation.a.a(SourceFile:1444)
12-08 15:26:57.482 12443 12443 W System.err: 	at v.e.l(SourceFile:279)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at d4.Z.c(SourceFile:914)
12-08 15:26:57.482 12443 12443 W System.err: 	at d4.Z.b(SourceFile:227)
12-08 15:26:57.482 12443 12443 W System.err: 	at d8.t.h(SourceFile:153)
12-08 15:26:57.482 12443 12443 W System.err: 	at G7.m0.j(SourceFile:601)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.g(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.j(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at C.w.l(SourceFile:1238)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at C.w.l(SourceFile:797)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.e(SourceFile:46)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.h.l(SourceFile:9)
12-08 15:26:57.482 12443 12443 W System.err: 	at f0.u.a(SourceFile:15)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.m.n(SourceFile:80)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.w.m(SourceFile:35)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.T0.a(SourceFile:25)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.m$b.a(SourceFile:5)
12-08 15:26:57.482 12443 12443 W System.err: 	at X.w.n(SourceFile:12)
12-08 15:26:57.482 12443 12443 W System.err: 	at H0.F.i(SourceFile:28)
12-08 15:26:57.482 12443 12443 W System.err: 	at H0.F.h(SourceFile:116)
12-08 15:26:57.482 12443 12443 W System.err: 	at H0.A.j0(SourceFile:160)
12-08 15:26:57.482 12443 12443 W System.err: 	at C.w.l(SourceFile:1185)
12-08 15:26:57.482 12443 12443 W System.err: 	at H0.C.a(SourceFile:72)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.t.a(SourceFile:38)
12-08 15:26:57.482 12443 12443 W System.err: 	at C.H.h(SourceFile:99)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.y.a(SourceFile:11)
12-08 15:26:57.482 12443 12443 W System.err: 	at C0.b.b(SourceFile:296)
12-08 15:26:57.482 12443 12443 W System.err: 	at i0.k$a.c(SourceFile:56)
12-08 15:26:57.482 12443 12443 W System.err: 	at i0.J$a.a(SourceFile:58)
12-08 15:26:57.482 12443 12443 W System.err: 	at i0.J.e(SourceFile:121)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.l0.a(SourceFile:3)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.K.q0(SourceFile:131)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.K.a(SourceFile:91)
12-08 15:26:57.482 12443 12443 W System.err: 	at H0.b0.a(SourceFile:39)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.t.a(SourceFile:38)
12-08 15:26:57.482 12443 12443 W System.err: 	at C0.b.b(SourceFile:296)
12-08 15:26:57.482 12443 12443 W System.err: 	at i0.k$a.c(SourceFile:114)
12-08 15:26:57.482 12443 12443 W System.err: 	at i0.J$a.a(SourceFile:58)
12-08 15:26:57.482 12443 12443 W System.err: 	at i0.J.e(SourceFile:121)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.l0.a(SourceFile:3)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.K.q0(SourceFile:131)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.E.M(SourceFile:17)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.T.d(SourceFile:3)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.T.p(SourceFile:23)
12-08 15:26:57.482 12443 12443 W System.err: 	at J0.T.m(SourceFile:65)
12-08 15:26:57.482 12443 12443 W System.err: 	at K0.v.onMeasure(SourceFile:123)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.View.measure(View.java:28122)
12-08 15:26:57.482 12443 12443 W System.err: 	at K0.a.h(SourceFile:64)
12-08 15:26:57.482 12443 12443 W System.err: 	at K0.a.onMeasure(SourceFile:4)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.View.measure(View.java:28122)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-08 15:26:57.482 12443 12443 W System.err: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.View.measure(View.java:28122)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.View.measure(View.java:28122)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.View.measure(View.java:28122)
12-08 15:26:57.482 12443 12443 W System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
1
```
Please let me know if any further information is required.
Best regards!

**Comment by sajkbflksadbfkasdjf** [comment]
> If the nature of the issue is different, open a new and detailed issue. It is not understood here🙂

From the crash logs, we can see the same trace and therefore probably the same bug. Thus it's more appropriate to comment here and let the maintainers get all the info for this particular bug in one place.
