### ISSUE TITLE
Song stops playing in Android Auto

### ISSUE THREAD

**Issue by leo-sakh** [fast4x/RiMusic#4875]
### Version of RiMusic

0.6.63.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Start playing any song in a playlist
2. Song will stop playing after some random amount of time. This could be the first song or multiple songs into the playlist
3. Cannot start playing another song once this happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

For songs to continue playing unless I stop/pause palyback

### What more can you tell us? (Optional)

This has been happening for the past ~5 build versions of the app

### Logs (Optional)

2024-12-08 09:48:54:231 ERROR: PlayerServiceModern - PlayerService onPlayerError S2.n: Source error
	at S2.O.k(SourceFile:17)
	at S2.O.handleMessage(SourceFile:339)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: java.io.IOException: java.lang.NullPointerException
	at O2.D.h(SourceFile:72)
	at O2.E.h(SourceFile:10)
	at e3.O.b(SourceFile:26)
	at i3.j.run(SourceFile:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException
	at l8.L.a(SourceFile:127)
	at u7.S.e(SourceFile:21)
	at d8.B.V(SourceFile:177)
	at z7.b.g0(SourceFile:87)
	at z7.b.L(SourceFile:211)
	at c8.a.t(SourceFile:50)
	at I8.a.k(SourceFile:9)
	at d9.L.run(SourceFile:107)
	at d9.X.v0(SourceFile:76)
	at d9.E.E(SourceFile:105)
	at O2.D.h(SourceFile:47)
	... 6 more

2024-12-08 09:48:54:277 ERROR: i - Playback error: java.lang.NullPointerException
2024-12-08 09:48:56:048 ERROR: i - Playback error: java.lang.NullPointerException
2024-12-08 09:49:03:808 ERROR: e - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-12-08 09:49:04:506 ERROR: e - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-12-08 09:49:05:557 ERROR: e - Error YoutubeLogin: java.lang.NullPointerException.stackTraceToString()
2024-12-08 09:49:09:508 ERROR: i - Playback error: java.lang.NullPointerException

**Comment by fast4x** [comment]
Hi, login to youtube music please and try again

**Comment by leo-sakh** [comment]
This was all while logged in to Youtube

**Comment by leo-sakh** [comment]
The issue appears to be resolved in the latest release (this is without logging into YouTube Music): v0.6.69
