### ISSUE TITLE
Song won't play

### ISSUE THREAD

**Issue by SmoothButt** [fast4x/RiMusic#4880]
### Version of RiMusic

0.6.63.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

To be able to listen to any music

### What more can you tell us? (Optional)

I did log in and out of YTM but it doesn't change anything. 

### Logs (Optional)

2024-11-24 12:13:03:969 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:13:04:377 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 1 newPosition 0 reason 4
2024-11-24 12:13:09:348 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:13:09:392 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:13:10:507 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:13:10:977 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 1 reason 1
2024-11-24 12:13:11:064 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 1 newPosition 1 reason 2
2024-11-24 12:13:17:588 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:13:46:935 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:14:16:938 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:14:29:631 INFO: m -  DeviceListSongs colums idIdx 0
2024-11-24 12:14:29:631 INFO: m -  DeviceListSongs colums nameIdx 1
2024-11-24 12:14:29:632 INFO: m -  DeviceListSongs colums durationIdx 2
2024-11-24 12:14:29:632 INFO: m -  DeviceListSongs colums artistIdx 3
2024-11-24 12:14:29:632 INFO: m -  DeviceListSongs colums albumIdIdx 4
2024-11-24 12:14:29:633 INFO: m -  DeviceListSongs colums relativePathIdx 5
2024-11-24 12:14:29:633 INFO: m -  DeviceListSongs colums titleIdx 6
2024-11-24 12:14:29:633 INFO: m -  DeviceListSongs colums isMusicIdx 7
2024-11-24 12:14:29:633 INFO: m -  DeviceListSongs colums mimeTypeIdx 8
2024-11-24 12:14:29:634 INFO: m -  DeviceListSongs colums bitrateIdx 10
2024-11-24 12:14:29:634 INFO: m -  DeviceListSongs colums fileSizeIdx 11
2024-11-24 12:14:29:634 INFO: m -  DeviceListSongs colums dateModifiedIdx 9
2024-11-24 12:14:29:635 INFO: m -  DeviceListSongs SDK 34 initialize columns complete
2024-11-24 12:14:29:635 INFO: m -  DeviceListSongs trackName grom loaded
2024-11-24 12:14:29:638 INFO: m -  DeviceListSongs trackName bigos binted loaded
2024-11-24 12:14:29:641 INFO: m -  DeviceListSongs trackName AUD-20210111-WA0000 loaded
2024-11-24 12:14:29:642 INFO: m -  DeviceListSongs trackName AUD-20210111-WA0001 loaded
2024-11-24 12:14:29:644 INFO: m -  DeviceListSongs trackName AUD-20210123-WA0018 loaded
2024-11-24 12:14:29:648 INFO: m -  DeviceListSongs trackName Over the Horizon loaded
2024-11-24 12:14:34:901 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 1 newPosition 0 reason 4
2024-11-24 12:14:35:017 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:14:46:938 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:14:47:968 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 1
2024-11-24 12:14:49:277 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 1
2024-11-24 12:14:50:728 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 1
2024-11-24 12:14:53:025 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 1
2024-11-24 12:14:56:534 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 1
2024-11-24 12:14:58:782 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 1 reason 4
2024-11-24 12:14:58:929 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:15:16:938 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:15:46:939 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:16:16:940 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:16:46:941 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:17:16:942 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:17:46:944 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:18:16:944 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:18:46:943 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:19:16:858 ERROR: f - RememberPreference ChartsPage Error: E9.o: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'n' instead at path: $
JSON input: null
	at E9.v.d(SourceFile:35)
	at E9.v.e(SourceFile:35)
	at E9.a.q(SourceFile:61)
	at E9.a.r(SourceFile:13)
	at E9.a.s(SourceFile:73)
	at E9.a.H(SourceFile:48)
	at E9.K.h(SourceFile:43)
	at E9.H.d(SourceFile:65)
	at u7.h.a(SourceFile:3)
	at E9.H.p(SourceFile:283)
	at D9.d.a(SourceFile:30)
	at e7.f.e(SourceFile:776)
	at j8.b.l(SourceFile:1127)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at X.C.a(SourceFile:231)
	at h0.j.a(SourceFile:150)
	at j8.c.n(SourceFile:324)
	at f0.h.h(SourceFile:46)
	at f0.h.n(SourceFile:9)
	at K.n0.j(SourceFile:155)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1400)
	at v.e.l(SourceFile:279)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at d8.e0.b(SourceFile:914)
	at d8.e0.a(SourceFile:227)
	at H9.d.j(SourceFile:891)
	at f0.h.g(SourceFile:46)
	at f0.d.l(SourceFile:20)
	at X.m.J(SourceFile:579)
	at X.m.R(SourceFile:137)
	at X.m.n(SourceFile:119)
	at X.m.H(SourceFile:31)
	at X.w.y(SourceFile:20)
	at X.T0.t(SourceFile:93)
	at X.d1.b(SourceFile:529)
	at K0.a0.doFrame(SourceFile:7)
	at K0.Y.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1669)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1680)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1191)
	at android.view.Choreographer.doFrame(Choreographer.java:1057)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1650)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

2024-11-24 12:19:16:953 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:19:31:429 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 1 newPosition 0 reason 4
2024-11-24 12:19:31:548 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:19:32:754 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:19:41:206 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:19:41:666 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 0 newPosition 0 reason 4
2024-11-24 12:30:23:379 ERROR: f - RememberPreference ChartsPage Error: E9.o: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'n' instead at path: $
JSON input: null
	at E9.v.d(SourceFile:35)
	at E9.v.e(SourceFile:35)
	at E9.a.q(SourceFile:61)
	at E9.a.r(SourceFile:13)
	at E9.a.s(SourceFile:73)
	at E9.a.H(SourceFile:48)
	at E9.K.h(SourceFile:43)
	at E9.H.d(SourceFile:65)
	at u7.h.a(SourceFile:3)
	at E9.H.p(SourceFile:283)
	at D9.d.a(SourceFile:30)
	at e7.f.e(SourceFile:776)
	at j8.b.l(SourceFile:1127)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at X.C.a(SourceFile:231)
	at h0.j.a(SourceFile:150)
	at j8.c.n(SourceFile:324)
	at f0.h.h(SourceFile:46)
	at f0.h.n(SourceFile:9)
	at K.n0.j(SourceFile:155)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1400)
	at v.e.l(SourceFile:279)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at d8.e0.b(SourceFile:914)
	at d8.e0.a(SourceFile:227)
	at H9.d.j(SourceFile:891)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at C.w.l(SourceFile:654)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at C.w.l(SourceFile:797)
	at f0.h.a(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at f0.u.a(SourceFile:15)
	at X.m.n(SourceFile:80)
	at X.w.m(SourceFile:35)
	at X.T0.a(SourceFile:25)
	at X.m$b.a(SourceFile:5)
	at X.m$b.a(SourceFile:5)
	at X.w.n(SourceFile:12)
	at H0.F.i(SourceFile:28)
	at H0.F.h(SourceFile:116)
	at H0.A.j0(SourceFile:160)
	at U.v1.l(SourceFile:526)
	at H0.C.a(SourceFile:72)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at J0.t.a(SourceFile:38)
	at r0.Y.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.t.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.y.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.t.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.y.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.y.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at C.w.l(SourceFile:1193)
	at H0.C.a(SourceFile:72)
	at J0.t.a(SourceFile:38)
	at C.H.h(SourceFile:99)
	at J0.y.a(SourceFile:11)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.K.a(SourceFile:91)
	at H0.b0.a(SourceFile:39)
	at J0.t.a(SourceFile:38)
	at C0.b.c(SourceFile:296)
	at i0.k$a.c(SourceFile:114)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.l0.a(SourceFile:3)
	at J0.K.q0(SourceFile:131)
	at J0.E.M(SourceFile:17)
	at J0.T.c(SourceFile:3)
	at J0.T.o(SourceFile:23)
	at J0.T.l(SourceFile:65)
	at K0.u.onMeasure(SourceFile:123)
	at android.view.View.measure(View.java:28192)
	at K0.a.h(SourceFile:64)
	at K0.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:28192)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:28192)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28192)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28192)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28192)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:837)
	at android.view.View.measure(View.java:28192)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4822)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3315)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3676)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3014)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1671)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1680)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1191)
	at android.view.Choreographer.doFrame(Choreographer.java:1063)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1650)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

2024-11-24 12:30:31:070 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:31:111 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:36:409 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:36:419 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:37:556 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:47:768 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:50:637 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:53:129 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:30:54:711 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:31:23:079 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:31:53:079 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:32:23:080 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:32:53:083 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:33:23:083 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:33:53:083 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:34:23:085 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:34:53:086 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:35:23:087 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:35:53:091 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:36:23:090 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:36:34:687 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 2 newPosition 3 reason 0
2024-11-24 12:36:53:092 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:37:23:092 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:37:53:094 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:38:23:095 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:38:53:096 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:39:23:097 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:39:53:097 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:40:21:723 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 3 newPosition 4 reason 0
2024-11-24 12:40:23:098 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:40:53:101 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:41:23:101 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:41:53:102 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:42:23:103 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:42:53:104 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:43:23:105 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:43:53:106 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:44:23:111 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:44:53:109 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:45:23:138 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:45:53:151 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:45:55:300 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:46:23:131 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:46:50:457 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 5 newPosition 6 reason 0
2024-11-24 12:46:53:112 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:47:23:114 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:47:53:116 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:48:23:116 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:48:53:118 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:49:23:117 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:49:53:119 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:50:23:121 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:50:48:370 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 6 newPosition 7 reason 0
2024-11-24 12:50:53:123 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:51:23:124 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:51:53:127 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:52:23:128 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:52:53:128 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:53:23:129 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:53:53:130 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:54:23:131 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:54:52:213 DEBUG: PlayerServiceModern - PlayerServiceModern onPositionDiscontinuity oldPosition 7 newPosition 8 reason 0
2024-11-24 12:54:53:183 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:54:55:984 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-24 12:54:56:496 DEBUG: PlayerServiceModern - PlayerServiceModern o

**Comment by fast4x** [comment]
Send crash log not debug log
