### ISSUE TITLE
Impossible de redémarrer l'application

### ISSUE THREAD

**Issue by ptdphnnf** [fast4x/RiMusic#5028]
### Version of RiMusic

0.6.64

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I can't reboot RiMusic, but i have reboot m'y phone, the app, and i've done a forced reboot (phone and app). But the app is saying to me : "reboot the app", and it is no reboot button.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

À pouvoir lire des titres et à ce que l'appli ne me demande plus de la redémarrer.

### Logs (Optional)

2024-12-22 10:46:28:105 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-12-22 10:46:28:611 ERROR: h - RememberPreference RelatedPage Error: K9.n: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'n' instead at path: $
JSON input: null
	at K9.s.d(SourceFile:35)
	at K9.s.e(SourceFile:35)
	at K9.a.q(SourceFile:61)
	at K9.a.r(SourceFile:13)
	at K9.a.s(SourceFile:73)
	at K9.a.H(SourceFile:48)
	at K9.G.h(SourceFile:43)
	at K9.D.y(SourceFile:65)
	at b8.v.e(SourceFile:5)
	at K9.D.j(SourceFile:283)
	at J9.d.a(SourceFile:30)
	at e8.h.l(SourceFile:387)
	at D8.l0.l(SourceFile:914)
	at f0.h.d(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at X.C.a(SourceFile:231)
	at h0.j.b(SourceFile:150)
	at D8.m0.m(SourceFile:216)
	at f0.h.h(SourceFile:46)
	at f0.h.m(SourceFile:9)
	at K.m0.j(SourceFile:155)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at androidx.compose.animation.a.a(SourceFile:1444)
	at v.e.l(SourceFile:279)
	at f0.h.d(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at e8.I.c(SourceFile:914)
	at e8.I.b(SourceFile:227)
	at B8.N.j(SourceFile:643)
	at f0.h.g(SourceFile:46)
	at f0.h.j(SourceFile:9)
	at C.w.l(SourceFile:654)
	at f0.h.d(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at C.w.l(SourceFile:797)
	at f0.h.d(SourceFile:46)
	at f0.h.l(SourceFile:9)
	at f0.u.a(SourceFile:15)
	at X.m.n(SourceFile:80)
	at X.w.m(SourceFile:35)
	at X.T0.a(SourceFile:25)
	at X.m$b.a(SourceFile:5)
	at X.m$b.a(SourceFile:5)
	at X.w.n(SourceFile:12)
	at H0.F.i(SourceFile:28)
	at H0.F.h(SourceFile:116)
	at H0.A.I(SourceFile:160)
	at U.x1.l(SourceFile:526)
	at H0.C.a(SourceFile:72)
	at J0.u.a(SourceFile:38)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at J0.u.a(SourceFile:38)
	at r0.Y.h(SourceFile:1)
	at J0.z.a(SourceFile:11)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.u.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.z.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.z.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.z.a(SourceFile:11)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.u.a(SourceFile:38)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at v.o.a(SourceFile:24)
	at J0.u.a(SourceFile:38)
	at v.G.h(SourceFile:246)
	at J0.z.a(SourceFile:11)
	at r0.o.h(SourceFile:1)
	at J0.z.a(SourceFile:11)
	at C.s0.j(SourceFile:30)
	at H0.w.h(SourceFile:8)
	at J0.z.a(SourceFile:11)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at v.h.a(SourceFile:60)
	at J0.u.a(SourceFile:38)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at C.u.a(SourceFile:85)
	at C.w.l(SourceFile:1193)
	at H0.C.a(SourceFile:72)
	at J0.u.a(SourceFile:38)
	at C.H.h(SourceFile:99)
	at J0.z.a(SourceFile:11)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:56)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.L.a(SourceFile:91)
	at H0.b0.a(SourceFile:39)
	at J0.u.a(SourceFile:38)
	at C0.b.b(SourceFile:303)
	at i0.k$a.c(SourceFile:114)
	at i0.J$a.a(SourceFile:58)
	at i0.J.e(SourceFile:121)
	at J0.m0.a(SourceFile:3)
	at J0.L.q0(SourceFile:131)
	at J0.F.M(SourceFile:17)
	at J0.U.d(SourceFile:3)
	at J0.U.p(SourceFile:23)
	at J0.U.m(SourceFile:65)
	at K0.x.onMeasure(SourceFile:123)
	at android.view.View.measure(View.java:25953)
	at K0.a.h(SourceFile:64)
	at K0.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:25953)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7055)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:25953)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7055)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25953)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7055)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25953)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7055)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25953)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7055)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:761)
	at android.view.View.measure(View.java:25953)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3795)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2518)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2803)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2237)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9027)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1105)
	at android.view.Choreographer.doCallbacks(Choreographer.java:896)
	at android.view.Choreographer.doFrame(Choreographer.java:815)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1090)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7900)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

2024-12-22 10:46:29:957 DEBUG: h - Success loadData in QuickPicsModern

**Comment by Ask1ew** [comment]
Essaie de mettre à jour l'appli et de faire une capture du bug stp.
Ça les aidera à corriger l'appli

**Comment by Ask1ew** [comment]
La 0.6.65.1 va sortir dans la nuit
