### ISSUE TITLE
The song is not playing

### ISSUE THREAD

**Issue by odamaasio** [fast4x/RiMusic#5075]
### Version of RiMusic

v0.6.65.1 

### Android version

14

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. select a song
3. Boom! The bug happens.

![Screenshot_20241225_190312](https://github.com/user-attachments/assets/6376d523-a862-495b-80c0-d1fe2231b13b)

### What was your expectation?

.

**Comment by jksekai** [comment]
you can click on the three dots and click "update" and close the song and play it again

**Comment by misterhackerman** [comment]
I tried doing that "three dots and update", didn't work, keeps saying "An unknown playback error has occurred" and then "Song cannot be played"

```
2024-12-26 19:17:22:867 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-12-26 19:17:23:027 ERROR: h - RememberPreference RelatedPage Error: K9.n: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'n' instead at path: $
JSON input: null
 at K9.s.d(SourceFile:35)
 at K9.s.e(SourceFile:35)
 at K9.a.q(SourceFile:61)
 at K9.a.r(SourceFile:13)
 at K9.a.s(SourceFile:73)
 at K9.a.H(SourceFile:48)
 at K9.G.h(SourceFile:43)
 at K9.D.y(SourceFile:65)
 at b8.v.e(SourceFile:5)
 at K9.D.j(SourceFile:283)
 at J9.d.a(SourceFile:30)
 at e8.h.l(SourceFile:387)
 at D8.l0.l(SourceFile:914)
 at f0.h.d(SourceFile:46)
 at f0.h.l(SourceFile:9)
 at X.C.a(SourceFile:231)
 at h0.j.b(SourceFile:150)
 at D8.m0.m(SourceFile:216)
 at f0.h.h(SourceFile:46)
 at f0.h.m(SourceFile:9)
 at K.m0.j(SourceFile:155)
 at f0.h.g(SourceFile:46)
 at f0.h.j(SourceFile:9)
 at androidx.compose.animation.a.a(SourceFile:1444)
 at v.e.l(SourceFile:279)
 at f0.h.d(SourceFile:46)
 at f0.h.l(SourceFile:9)
 at e8.I.c(SourceFile:914)
 at e8.I.b(SourceFile:227)
 at B8.N.j(SourceFile:643)
 at f0.h.g(SourceFile:46)
 at f0.h.j(SourceFile:9)
 at C.w.l(SourceFile:654)
 at f0.h.d(SourceFile:46)
 at f0.h.l(SourceFile:9)
 at C.w.l(SourceFile:797)
 at f0.h.d(SourceFile:46)
 at f0.h.l(SourceFile:9)
 at f0.u.a(SourceFile:15)
 at X.m.n(SourceFile:80)
 at X.w.m(SourceFile:35)
 at X.T0.a(SourceFile:25)
 at X.m$b.a(SourceFile:5)
 at X.m$b.a(SourceFile:5)
 at X.w.n(SourceFile:12)
 at H0.F.i(SourceFile:28)
 at H0.F.h(SourceFile:116)
 at H0.A.I(SourceFile:160)
 at U.x1.l(SourceFile:526)
 at H0.C.a(SourceFile:72)
 at J0.u.a(SourceFile:38)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at C.u.a(SourceFile:85)
 at J0.u.a(SourceFile:38)
 at r0.Y.h(SourceFile:1)
 at J0.z.a(SourceFile:11)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at v.o.a(SourceFile:24)
 at J0.u.a(SourceFile:38)
 at v.G.h(SourceFile:246)
 at J0.z.a(SourceFile:11)
 at r0.o.h(SourceFile:1)
 at J0.z.a(SourceFile:11)
 at C.s0.j(SourceFile:30)
 at H0.w.h(SourceFile:8)
 at J0.z.a(SourceFile:11)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at v.h.a(SourceFile:60)
 at J0.u.a(SourceFile:38)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at v.o.a(SourceFile:24)
 at J0.u.a(SourceFile:38)
 at v.G.h(SourceFile:246)
 at J0.z.a(SourceFile:11)
 at r0.o.h(SourceFile:1)
 at J0.z.a(SourceFile:11)
 at C.s0.j(SourceFile:30)
 at H0.w.h(SourceFile:8)
 at J0.z.a(SourceFile:11)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at v.h.a(SourceFile:60)
 at J0.u.a(SourceFile:38)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at C.u.a(SourceFile:85)
 at C.w.l(SourceFile:1193)
 at H0.C.a(SourceFile:72)
 at J0.u.a(SourceFile:38)
 at C.H.h(SourceFile:99)
 at J0.z.a(SourceFile:11)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:56)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.L.a(SourceFile:91)
 at H0.b0.a(SourceFile:39)
 at J0.u.a(SourceFile:38)
 at C0.b.b(SourceFile:303)
 at i0.k$a.c(SourceFile:114)
 at i0.J$a.a(SourceFile:58)
 at i0.J.e(SourceFile:121)
 at J0.m0.a(SourceFile:3)
 at J0.L.q0(SourceFile:131)
 at J0.F.M(SourceFile:17)
 at J0.U.d(SourceFile:3)
 at J0.U.p(SourceFile:23)
 at J0.U.m(SourceFile:65)
 at K0.x.onMeasure(SourceFile:123)
 at android.view.View.measure(View.java:27149)
 at K0.a.h(SourceFile:64)
 at K0.a.onMeasure(SourceFile:4)
 at android.view.View.measure(View.java:27149)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
 at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
 at android.view.View.measure(View.java:27149)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
 at android.view.View.measure(View.java:27149)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
 at android.view.View.measure(View.java:27149)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
 at android.view.View.measure(View.java:27149)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:843)
 at android.view.View.measure(View.java:27149)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4376)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3018)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3327)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2725)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9812)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1505)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513)
 at android.view.Choreographer.doCallbacks(Choreographer.java:1128)
 at android.view.Choreographer.doFrame(Choreographer.java:1042)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8503)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

2024-12-26 19:17:24:279 DEBUG: h - Success loadData in QuickPicsModern
2024-12-26 19:17:37:590 ERROR: PlayerServiceModern - PlayerService onPlayerError S2.n: Source error
 at S2.O.k(SourceFile:17)
 at S2.O.handleMessage(SourceFile:353)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: O2.y: Response code: 403
 at Q2.b.h(SourceFile:358)
 at O2.o.h(SourceFile:312)
 at O2.F.h(SourceFile:3)
 at P2.g.c(SourceFile:278)
 at P2.g.h(SourceFile:168)
 at P2.g.c(SourceFile:278)
 at P2.g.h(SourceFile:168)
 at O2.D.h(SourceFile:168)
 at O2.E.h(SourceFile:10)
 at e3.O.b(SourceFile:26)
 at i3.j.run(SourceFile:35)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
2024-12-26 19:17:37:598 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:601 ERROR: k - Playback error: null
2024-12-26 19:17:37:621 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:663 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:668 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:684 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:693 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:708 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:716 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:733 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:742 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:756 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:766 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:781 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:794 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:808 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:816 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:829 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:839 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:853 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:864 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:879 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:889 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:903 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:911 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:928 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:942 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:961 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:971 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:985 ERROR: F1 - Playback error: null
2024-12-26 19:17:37:994 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:010 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:021 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:037 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:047 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:065 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:075 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:089 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:098 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:113 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:121 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:136 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:146 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:159 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:168 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:184 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:195 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:210 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:221 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:239 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:248 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:262 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:271 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:287 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:296 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:312 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:323 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:336 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:345 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:359 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:368 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:382 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:391 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:408 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:420 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:440 ERROR: F1 - Playback error: null
2024-12-26 19:17:38:455 ERROR: F1 - Playback error: null`
```

**Comment by Morello230** [comment]
Saya sejak kemarin mengalami masalah yang sama.
Dan sampai sekarang tidak dapat memainkan lagu di aplikasi RI MUSIC versi 6.65.1.

**Comment by fast4x** [comment]
download latest release
