### ISSUE TITLE
ViMusic database restored in RiMusic

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#558]
### Description

I would like to switch from like ViMusic to RiMusic but unfortunately the database from ViMusic cannot be restored in RiMusic. Since RiMusic is a fork of and ViMusic, I had assumed that this would work without any problems.

### Suggested Solution

Maybe you can make it work

**Comment by Radtrix** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#-is-there-a-way-to-transfer-playlists-and-favourites-from-vimusic

**Comment by fast4x** [comment]
Database Restore is totally compatible with original ViMusic backup.
This because data strutture is same only with original.

**Comment by siggi1984** [comment]
> Database Restore is totally compatible with original ViMusic backup. This because data strutture is same only with original.

RiMusic always crashes after I have restored ViMusic, see video.


https://github.com/fast4x/RiMusic/assets/103368536/561d0787-8b70-41d3-8e25-890e2fe91137

**Comment by fast4x** [comment]
ok, also i'll check it, thanks for video

**Comment by fast4x** [comment]
Confirmed, it's a bug in Restore. Thanks

**Comment by fast4x** [comment]
Sorry, my error, the restore works. The fact that closes RiMusic is not a bug or a crash. It closes without warning after restoring the backup.

**Comment by siggi1984** [comment]
> Sorry, my error, the restore works. The fact that closes RiMusic is not a bug or a crash. It closes without warning after restoring the backup.

Yes, that is correct, but RiMusic can no longer be started after the restore, it always crashes immediately.

**Comment by fast4x** [comment]
But not depending by RiMusic. Can you share your db for analysis?

**Comment by siggi1984** [comment]
> But not depending by RiMusic. Can you share your db for analysis?

FATAL EXCEPTION: arch_disk_io_0
Process: it.fast4x.rimusic, PID: 16530
java.lang.IllegalStateException: A migration from 27 to 23 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
	at t4.z.f(SourceFile:408)
	at t4.z.d(SourceFile:1)
	at y4.e.onDowngrade(SourceFile:1)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:512)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:413)
	at y4.e.f(SourceFile:1)
	at y4.e.w(SourceFile:1)
	at y4.e.b(SourceFile:1)
	at y4.f.getWritableDatabase(SourceFile:10)
	at t4.y.b(SourceFile:5)
	at z7.r.F(SourceFile:1)
	at z7.a.F(SourceFile:1)
	at g8.q.a(SourceFile:89)
	at g8.q.i(SourceFile:13)
	at androidx.compose.ui.platform.u.run(SourceFile:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by siggi1984** [comment]
> But not depending by RiMusic. Can you share your db for analysis?

[vimusic_20240131164911.zip](https://github.com/fast4x/RiMusic/files/14116792/vimusic_20240131164911.zip)

**Comment by siggi1984** [comment]
FATAL EXCEPTION: arch_disk_io_0
Process: it.fast4x.rimusic, PID: 21481
java.lang.IllegalStateException: A migration from 27 to 23 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
	at t4.z.f(SourceFile:408)
	at t4.z.d(SourceFile:1)
	at y4.e.onDowngrade(SourceFile:1)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:512)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:413)
	at y4.e.f(SourceFile:1)
	at y4.e.w(SourceFile:1)
	at y4.e.b(SourceFile:1)
	at y4.f.getWritableDatabase(SourceFile:10)
	at t4.y.b(SourceFile:5)
	at z7.r.F(SourceFile:1)
	at z7.a.F(SourceFile:1)
	at g8.q.a(SourceFile:89)
	at g8.q.i(SourceFile:13)
	at androidx.compose.ui.platform.u.run(SourceFile:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by fast4x** [comment]
Your backup it's from ViMusic fork by https://github.com/25huizengek1/ViMusic

Db Recover work without errors in ViMusic fork.

Isn't compatible with original ViMusic and/or  RiMusic, i'm afraid.

**Comment by fast4x** [comment]
![Screenshot_2024-01-31-21-29-51-900_it.vfsfitvnm.vimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/6085da33-ad33-4148-b690-4d6f1589c78d)

Recovered in ViMusic fork

**Comment by siggi1984** [comment]
> ![Screenshot_2024-01-31-21-29-51-900_it.vfsfitvnm.vimusic.jpg](https://private-user-images.githubusercontent.com/1484476/301300493-6085da33-ad33-4148-b690-4d6f1589c78d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzQwMjYsIm5iZiI6MTcwNjczMzcyNiwicGF0aCI6Ii8xNDg0NDc2LzMwMTMwMDQ5My02MDg1ZGEzMy1hZDMzLTQxNDgtYjY5MC00ZDZmMTU4OWM3OGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMjA0MjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM3MWRjNzQ5ZGIzZjM0NTc1MmU3ZDcyY2M4NzZiYzE2NzlmZDFjOGNkMWFmMDUzZjJkZTI3YTEzNTA5NGVmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mfxjU3hTp0AI05KANa_dC3iZm08F2feugHsfjdLxnuA)
> 
> Recovered in ViMusic fork

Okay, thanks for the help.

**Comment by fast4x** [comment]
Happy to help!
