### ISSUE TITLE
App crashes reliably when being closed

### ISSUE THREAD

**Issue by matterharz** [fast4x/RiMusic#896]
### Steps to reproduce the bug

This happens both with the current version and pretty much every version before that, which is to say the bug wasn't introduced in recent weeks.

Doesn't matter whether battery optimizations and the invincible service mode are enabled or disabled.

1. Open app
2. Close app (in this case by swiping up in the app overview)
3. Crash

### Expected behavior

It shouldn't crash.

### Actual behavior

It crashes.

### Logs

```
FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 14075
java.lang.RuntimeException: Unable to stop service it.vfsfitvnm.vimusic.service.PlayerService@291e564: java.lang.IllegalArgumentException: Receiver not registered: y8.t@fb53f01
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4756)
	at android.app.ActivityThread.access$2100(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: y8.t@fb53f01
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1555)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1798)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:771)
	at it.vfsfitvnm.vimusic.service.PlayerService.onDestroy(SourceFile:273)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4736)
	... 9 more
```

### RiMusic version

<=0.6.24

### Android version

LineageOS 19.1

### Additional information

Phone: OnePlus 5t

**Comment by claxcian** [comment]
Me too. 0.6.24

**Comment by dAtA-TRoN** [comment]
Hm, can't reproduce.

**Comment by matterharz** [comment]
It no longer happens when I clear the user data, i.e. start anew with a clean slate. Once I import my backed-up data, the crashes reoccur. It's possible the data is so old that it stems from ViMusic which might lead to complications.

Not closing as this apparently concerns others as well.
